// Generated by CoffeeScript 1.5.0
(function() {

  $.fn.isOnScreen = function(scrollTop, scrollLeft, windowWidth, windowHeight) {
    var bounds, scrollBottom, scrollRight;
    scrollRight = scrollLeft + windowWidth;
    scrollBottom = scrollTop + windowHeight;
    bounds = this.offset();
    if (this.is(':visible')) {
      bounds.right = bounds.left + this.outerWidth();
      bounds.bottom = bounds.top + this.outerHeight();
    } else {
      bounds.right = bounds.left;
      bounds.bottom = bounds.top;
    }
    return !(scrollRight < bounds.left || scrollLeft > bounds.right || scrollBottom < bounds.top || scrollTop > bounds.bottom);
  };

}).call(this);
