            ##
            # Author: Autogenerated on 2013-11-29 01:20:08
            # gitHash: 10810480518d43dd720690e729d2f3b9a0f8eba7
            # SEED: 7977475956795433203
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            complexFilterTest_uis_83 <- function(conn) {
                Log.info("A munge-task R unit test on data <uis> testing the functional unit <['!', '<', '&', '>=', '&', '<=']> ")
                Log.info("Uploading uis")
                hex <- h2o.uploadFile(conn, locate("../../smalldata/logreg/umass_statdata/uis.dat"), "ruis.hex")
            Log.info("Performing compound task !( ( hex[,c(8)] < 0.432836596563 ) & ( hex[,c(1)] >= 38.621259327 ) & ( ( hex[,c(6)] <= 0.973877296575 )) ) on dataset <uis>")
                     filterHex <- hex[!( ( hex[,c(8)] < 0.432836596563 ) & ( hex[,c(1)] >= 38.621259327 ) & ( ( hex[,c(6)] <= 0.973877296575 )) ),]
            Log.info("Performing compound task !( ( hex[,c(1)] < 316.678218022 ) & ( hex[,c(8)] >= 0.113806173221 ) & ( ( hex[,c(1)] <= 288.267653181 )) ) on dataset uis, and also subsetting columns.")
                     filterHex <- hex[!( ( hex[,c(1)] < 316.678218022 ) & ( hex[,c(8)] >= 0.113806173221 ) & ( ( hex[,c(1)] <= 288.267653181 )) ), c(1,3,2,4,6,8)]
                Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[!( ( hex[,c(1)] < 316.678218022 ) & ( hex[,c(8)] >= 0.113806173221 ) & ( ( hex[,c(1)] <= 288.267653181 )) ), c(5,7)]
            Log.info("End of test")
            PASSS <<- TRUE
            }
            PASSS <- FALSE
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("compoundFilterTest_ on data uis", complexFilterTest_uis_83(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            if (!PASSS) FAIL("Did not reach the end of test. Check Rsandbox/errors.log for warnings and errors.")
            PASS()
