            ##
            # Author: Autogenerated on 2013-12-05 22:49:50
            # gitHash: dbc23230f6666890a6cb7c4234e68e540e096e0c
            # SEED: 779905237530228736
            ##
            source('./findNSourceUtils.R')
            simpleFilterTest_iris_18 <- function(conn) {
                Log.info("A munge-task R unit test on data <iris> testing the functional unit <>> ")
                Log.info("Uploading iris")
                hex <- h2o.uploadFile(conn, locate("../../smalldata/iris/iris.xls"), "riris.hex")
                Log.info("Filtering out rows by > from dataset iris and column \"petal_len\" using value 6.18407545869")
                     filterHex <- hex[hex[,c("petal_len")] > 6.18407545869,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"petal_len" > 6.18407545869,]
                    Log.info("Filtering out rows by > from dataset iris and column \"petal_len\" using value 3.09712296868, and also subsetting columns.")
                     filterHex <- hex[hex[,c("petal_len")] > 3.09712296868, c("petal_len")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("petal_len")] > 3.09712296868, c("petal_wid","sepal_wid","class","petal_len","sepal_len")]
            testEnd()
            }
            doTest("simpleFilterTest_ on data iris unit= >", simpleFilterTest_iris_18)
