            ##
            # Author: Autogenerated on 2013-11-27 17:26:17
            # gitHash: a4fe16d99eb5f003dd7c7d0da17f29e1712eda0f
            # SEED: 8586424275721420395
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            complexFilterTest_arit_158 <- function(conn) {
                Log.info("A munge-task R unit test on data <arit> testing the functional unit <['!', '==', '&', '>', '|', '>=']> ")
                Log.info("Uploading arit")
                hex <- h2o.uploadFile(conn, locate("../../smalldata/test/arit.csv"), "rarit.hex")
            Log.info("Performing compound task !( ( hex[,c(1)] == 619224.374189 ) & ( hex[,c(1)] > 31.2664801811 ) | ( ( hex[,c(1)] >= 507696.6135 )) ) on dataset <arit>")
                     filterHex <- hex[!( ( hex[,c(1)] == 619224.374189 ) & ( hex[,c(1)] > 31.2664801811 ) | ( ( hex[,c(1)] >= 507696.6135 )) ),]
            Log.info("Performing compound task !( ( hex[,c(1)] == 5.80620142183 ) & ( hex[,c(1)] > 13.4229170752 ) | ( ( hex[,c(1)] >= 5.78074305145 )) ) on dataset arit, and also subsetting columns.")
                     filterHex <- hex[!( ( hex[,c(1)] == 5.80620142183 ) & ( hex[,c(1)] > 13.4229170752 ) | ( ( hex[,c(1)] >= 5.78074305145 )) ), c(1)]
                Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[!( ( hex[,c(1)] == 5.80620142183 ) & ( hex[,c(1)] > 13.4229170752 ) | ( ( hex[,c(1)] >= 5.78074305145 )) ), c(1)]
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("compoundFilterTest_ on data arit", complexFilterTest_arit_158(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
