            ##
            # Author: Autogenerated on 2013-12-05 22:49:50
            # gitHash: dbc23230f6666890a6cb7c4234e68e540e096e0c
            # SEED: 779905237530228736
            ##
            source('./findNSourceUtils.R')
            complexFilterTest_test_44 <- function(conn) {
                Log.info("A munge-task R unit test on data <test> testing the functional unit <['', '<=', '&', '<=', '&', '<=']> ")
                Log.info("Uploading test")
                hex <- h2o.uploadFile(conn, locate("../../smalldata/chess/chess_2x2x200/R/test.csv"), "rtest.hex")
            Log.info("Performing compound task ( hex[,c(\"x\")] <= 0.579137574384 ) & ( hex[,c(\"y\")] <= 0.105106021962 ) & ( ( hex[,c(\"y\")] <= 0.743869451701 ))  on dataset <test>")
                     filterHex <- hex[( hex[,c("x")] <= 0.579137574384 ) & ( hex[,c("y")] <= 0.105106021962 ) & ( ( hex[,c("y")] <= 0.743869451701 )) ,]
            Log.info("Performing compound task ( hex[,c(\"y\")] <= 1.05013035477 ) & ( hex[,c(\"y\")] <= 0.411324126065 ) & ( ( hex[,c(\"y\")] <= 0.2405756481 ))  on dataset test, and also subsetting columns.")
                     filterHex <- hex[( hex[,c("y")] <= 1.05013035477 ) & ( hex[,c("y")] <= 0.411324126065 ) & ( ( hex[,c("y")] <= 0.2405756481 )) , c("x","y")]
                Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[( hex[,c("y")] <= 1.05013035477 ) & ( hex[,c("y")] <= 0.411324126065 ) & ( ( hex[,c("y")] <= 0.2405756481 )) , c("color")]
            testEnd()
            }
            doTest("compoundFilterTest_ on data test unit= ['', '<=', '&', '<=', '&', '<=']", complexFilterTest_test_44)
