            ##
            # Author: Autogenerated on 2013-11-27 18:13:58
            # gitHash: c4ad841105ba82f4a3979e4cf1ae7e20a5905e59
            # SEED: 4663640625336856642
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            sliceTest_HEX_287_small_files_17 <- function(conn) {
                Log.info("A munge-task R unit test on data <HEX_287_small_files> testing the functional unit <[> ")
                Log.info("Uploading HEX_287_small_files")
                hex <- h2o.uploadFile(conn, locate("../../smalldata/test/HEX-287-small-files.data"), "rHEX_287_small_files.hex")
                    Log.info("Performing a 1-by-1 column slice of HEX-287-small-files using these columns: ")
                    Log.info("Performing a 1-by-1 row slice of HEX-287-small-files using these rows: ")
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("sliceTest_ on data HEX-287-small-files", sliceTest_HEX_287_small_files_17(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
