            ##
            # Author: Autogenerated on 2013-11-29 01:20:07
            # gitHash: 10810480518d43dd720690e729d2f3b9a0f8eba7
            # SEED: 7977475956795433203
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            simpleFilterTest_test_13 <- function(conn) {
                Log.info("A munge-task R unit test on data <test> testing the functional unit <<> ")
                Log.info("Uploading test")
                hex <- h2o.uploadFile(conn, locate("../../smalldata/chess/chess_2x2x1000/R/test.csv"), "rtest.hex")
                Log.info("Filtering out rows by < from dataset test and column \"x\" using value 1.74302982463")
                     filterHex <- hex[hex[,c("x")] < 1.74302982463,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"x" < 1.74302982463,]
                    Log.info("Filtering out rows by < from dataset test and column \"y\" using value 1.2590856644, and also subsetting columns.")
                     filterHex <- hex[hex[,c("y")] < 1.2590856644, c("y")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("y")] < 1.2590856644, c("color","x","y")]
            Log.info("End of test")
            PASSS <<- TRUE
            }
            PASSS <- FALSE
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("simpleFilterTest_ on data test", simpleFilterTest_test_13(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            if (!PASSS) FAIL("Did not reach the end of test. Check Rsandbox/errors.log for warnings and errors.")
            PASS()
