            ##
            # Author: Autogenerated on 2013-11-29 01:20:08
            # gitHash: 10810480518d43dd720690e729d2f3b9a0f8eba7
            # SEED: 7977475956795433203
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            complexFilterTest_pros_68 <- function(conn) {
                Log.info("A munge-task R unit test on data <pros> testing the functional unit <['', '==']> ")
                Log.info("Uploading pros")
                hex <- h2o.uploadFile(conn, locate("../../smalldata/logreg/umass_statdata/pros.dat"), "rpros.hex")
            Log.info("Performing compound task ( ( hex[,c(7)] == 67.7604155314 ))  on dataset <pros>")
                     filterHex <- hex[( ( hex[,c(7)] == 67.7604155314 )) ,]
            Log.info("Performing compound task ( ( hex[,c(5)] == 1.29331912166 ))  on dataset pros, and also subsetting columns.")
                     filterHex <- hex[( ( hex[,c(5)] == 1.29331912166 )) , c(8,5)]
                Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[( ( hex[,c(5)] == 1.29331912166 )) , c(1,3,2,4,7,6)]
            Log.info("End of test")
            PASSS <<- TRUE
            }
            PASSS <- FALSE
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("compoundFilterTest_ on data pros", complexFilterTest_pros_68(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            if (!PASSS) FAIL("Did not reach the end of test. Check Rsandbox/errors.log for warnings and errors.")
            PASS()
