            ##
            # Author: Autogenerated on 2013-11-27 17:26:17
            # gitHash: a4fe16d99eb5f003dd7c7d0da17f29e1712eda0f
            # SEED: 8586424275721420395
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            complexFilterTest_uis_156 <- function(conn) {
                Log.info("A munge-task R unit test on data <uis> testing the functional unit <['!', '==', '&', '>', '|', '>=']> ")
                Log.info("Uploading uis")
                hex <- h2o.uploadFile(conn, locate("../../smalldata/logreg/umass_statdata/uis.dat"), "ruis.hex")
            Log.info("Performing compound task !( ( hex[,c(8)] == 0.329671457695 ) & ( hex[,c(6)] > 0.324511248682 ) | ( ( hex[,c(7)] >= 0.79088096827 )) ) on dataset <uis>")
                     filterHex <- hex[!( ( hex[,c(8)] == 0.329671457695 ) & ( hex[,c(6)] > 0.324511248682 ) | ( ( hex[,c(7)] >= 0.79088096827 )) ),]
            Log.info("Performing compound task !( ( hex[,c(4)] == 21.330050476 ) & ( hex[,c(4)] > 23.5193547132 ) | ( ( hex[,c(7)] >= 0.0443570084551 )) ) on dataset uis, and also subsetting columns.")
                     filterHex <- hex[!( ( hex[,c(4)] == 21.330050476 ) & ( hex[,c(4)] > 23.5193547132 ) | ( ( hex[,c(7)] >= 0.0443570084551 )) ), c(1,2,5,4,7,8)]
                Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[!( ( hex[,c(4)] == 21.330050476 ) & ( hex[,c(4)] > 23.5193547132 ) | ( ( hex[,c(7)] >= 0.0443570084551 )) ), c(3,6)]
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("compoundFilterTest_ on data uis", complexFilterTest_uis_156(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
