            ##
            # Author: Autogenerated on 2013-11-29 01:20:08
            # gitHash: 10810480518d43dd720690e729d2f3b9a0f8eba7
            # SEED: 7977475956795433203
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            complexFilterTest_tnc6_71 <- function(conn) {
                Log.info("A munge-task R unit test on data <tnc6> testing the functional unit <['', '==']> ")
                Log.info("Uploading tnc6")
                hex <- h2o.uploadFile(conn, locate("../../smalldata/tnc6.csv"), "rtnc6.hex")
            Log.info("Performing compound task ( ( hex[,c(\"cabin\")] == -1.0 ))  on dataset <tnc6>")
                     filterHex <- hex[( ( hex[,c("cabin")] == -1.0 )) ,]
            Log.info("Performing compound task ( ( hex[,c(\"ticket\")] == 571029.074235 ))  on dataset tnc6, and also subsetting columns.")
                     filterHex <- hex[( ( hex[,c("ticket")] == 571029.074235 )) , c("boat","fare","ticket","survived","cabin","home.dest","body")]
                Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[( ( hex[,c("ticket")] == 571029.074235 )) , c("embarked")]
            Log.info("End of test")
            PASSS <<- TRUE
            }
            PASSS <- FALSE
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("compoundFilterTest_ on data tnc6", complexFilterTest_tnc6_71(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            if (!PASSS) FAIL("Did not reach the end of test. Check Rsandbox/errors.log for warnings and errors.")
            PASS()
