            ##
            # Author: Autogenerated on 2013-11-27 03:20:00
            # gitHash: 25eb0cfd1269362ae85d0f073d9abde2a68ac0e4
            # SEED: 4617575514352894151
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            complexFilterTest_TwoBedrooms_Rent_Neighborhoods_190 <- function(conn) {
                Log.info("A munge-task R unit test on data <TwoBedrooms_Rent_Neighborhoods> testing the functional unit <['!', '!=', '|', '<', '|', '>=']> ")
                Log.info("Uploading TwoBedrooms_Rent_Neighborhoods")
                hex <- h2o.uploadFile(conn, "../../smalldata/categoricals/TwoBedrooms_Rent_Neighborhoods.csv.gz", "rTwoBedrooms_Rent_Neighborhoods.hex")
            Log.info("Performing compound task !( ( hex[,c(\"count39\")] != 91390.6917161 ) | ( hex[,c(\"count64\")] < 4222.16287388 ) | ( ( hex[,c(\"count86\")] >= 2207.66327115 )) ) on dataset <TwoBedrooms_Rent_Neighborhoods>")
                     filterHex <- hex[!( ( hex[,c("count39")] != 91390.6917161 ) | ( hex[,c("count64")] < 4222.16287388 ) | ( ( hex[,c("count86")] >= 2207.66327115 )) ),]
            Log.info("Performing compound task !( ( hex[,c(\"count37\")] != 159453.944732 ) | ( hex[,c(\"count23\")] < 479585.845873 ) | ( ( hex[,c(\"count65\")] >= 10318.6797238 )) ) on dataset TwoBedrooms_Rent_Neighborhoods, and also subsetting columns.")
                     filterHex <- hex[!( ( hex[,c("count37")] != 159453.944732 ) | ( hex[,c("count23")] < 479585.845873 ) | ( ( hex[,c("count65")] >= 10318.6797238 )) ), c("mcd","metro","count81","count28","count27","count42","count9","count3","count76","count99","count52","count59","Rent_Type","count20","count63","count36","count45","place","county","count67","count97","count79","count95","count34","count65","count6","count50","count4","count39","count29","medrent","count53","sumlevel","count73","count77","count41","count37","count16","count21","count33","count70","count61","count44","count12","count56","count86","count23","count94","count96","count35")]
                Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[!( ( hex[,c("count37")] != 159453.944732 ) | ( hex[,c("count23")] < 479585.845873 ) | ( ( hex[,c("count65")] >= 10318.6797238 )) ), c("count72","count1","count5","count54","count7","count93","count30","count89","count40","count46","count71","count18","count68","count74","count15","count26","count69","count49","count24","count32","count8","count57","areaname","count91","count38","count13","count83","count17","count87","count11","count85","count22","count92","state","count75","count58","count19","count80","count88","count47","count51","count43","count62","count2","count60","count31","count14","count98","count25","count78","count84","count82","count66","count90","count55","count48","count64","count10")]
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("compoundFilterTest_ on data TwoBedrooms_Rent_Neighborhoods", complexFilterTest_TwoBedrooms_Rent_Neighborhoods_190(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
