            ##
            # Author: Autogenerated on 2013-11-27 18:13:58
            # gitHash: c4ad841105ba82f4a3979e4cf1ae7e20a5905e59
            # SEED: 4663640625336856642
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            simpleFilterTest_Test_Arabic_Digit_short_98 <- function(conn) {
                Log.info("A munge-task R unit test on data <Test_Arabic_Digit_short> testing the functional unit <>=> ")
                Log.info("Uploading Test_Arabic_Digit_short")
                hex <- h2o.uploadFile(conn, locate("../../smalldata/Test_Arabic_Digit_short.data"), "rTest_Arabic_Digit_short.hex")
                Log.info("Filtering out rows by >= from dataset Test_Arabic_Digit_short and column \"3\" using value -2.90599780963")
                     filterHex <- hex[hex[,c(3)] >= -2.90599780963,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"3" >= -2.90599780963,]
                Log.info("Filtering out rows by >= from dataset Test_Arabic_Digit_short and column \"4\" using value 0.837141652739")
                     filterHex <- hex[hex[,c(4)] >= 0.837141652739,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"4" >= 0.837141652739,]
                Log.info("Filtering out rows by >= from dataset Test_Arabic_Digit_short and column \"10\" using value -0.568552343997")
                     filterHex <- hex[hex[,c(10)] >= -0.568552343997,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"10" >= -0.568552343997,]
                Log.info("Filtering out rows by >= from dataset Test_Arabic_Digit_short and column \"10\" using value -1.83599967671")
                     filterHex <- hex[hex[,c(10)] >= -1.83599967671,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"10" >= -1.83599967671,]
                Log.info("Filtering out rows by >= from dataset Test_Arabic_Digit_short and column \"7\" using value 0.750612678565")
                     filterHex <- hex[hex[,c(7)] >= 0.750612678565,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"7" >= 0.750612678565,]
                Log.info("Filtering out rows by >= from dataset Test_Arabic_Digit_short and column \"2\" using value -0.0475916961243")
                     filterHex <- hex[hex[,c(2)] >= -0.0475916961243,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"2" >= -0.0475916961243,]
                Log.info("Filtering out rows by >= from dataset Test_Arabic_Digit_short and column \"1\" using value -5.6701736967")
                     filterHex <- hex[hex[,c(1)] >= -5.6701736967,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"1" >= -5.6701736967,]
                Log.info("Filtering out rows by >= from dataset Test_Arabic_Digit_short and column \"5\" using value -0.477127448778")
                     filterHex <- hex[hex[,c(5)] >= -0.477127448778,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"5" >= -0.477127448778,]
                Log.info("Filtering out rows by >= from dataset Test_Arabic_Digit_short and column \"3\" using value -2.21032631953")
                     filterHex <- hex[hex[,c(3)] >= -2.21032631953,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"3" >= -2.21032631953,]
                Log.info("Filtering out rows by >= from dataset Test_Arabic_Digit_short and column \"1\" using value -8.14262076218")
                     filterHex <- hex[hex[,c(1)] >= -8.14262076218,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"1" >= -8.14262076218,]
                Log.info("Filtering out rows by >= from dataset Test_Arabic_Digit_short and column \"2\" using value 1.02696229104")
                     filterHex <- hex[hex[,c(2)] >= 1.02696229104,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"2" >= 1.02696229104,]
                Log.info("Filtering out rows by >= from dataset Test_Arabic_Digit_short and column \"0\" using value 1.97047300691")
                     filterHex <- hex[hex[,c(1)] >= 1.97047300691,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"0" >= 1.97047300691,]
                Log.info("Filtering out rows by >= from dataset Test_Arabic_Digit_short and column \"10\" using value -1.74485444681")
                     filterHex <- hex[hex[,c(10)] >= -1.74485444681,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"10" >= -1.74485444681,]
                Log.info("Filtering out rows by >= from dataset Test_Arabic_Digit_short and column \"11\" using value -0.733135598667")
                     filterHex <- hex[hex[,c(11)] >= -0.733135598667,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"11" >= -0.733135598667,]
                Log.info("Filtering out rows by >= from dataset Test_Arabic_Digit_short and column \"12\" using value 0.0225784340377")
                     filterHex <- hex[hex[,c(12)] >= 0.0225784340377,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"12" >= 0.0225784340377,]
                Log.info("Filtering out rows by >= from dataset Test_Arabic_Digit_short and column \"6\" using value 1.1871473754")
                     filterHex <- hex[hex[,c(6)] >= 1.1871473754,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"6" >= 1.1871473754,]
                Log.info("Filtering out rows by >= from dataset Test_Arabic_Digit_short and column \"10\" using value -0.600746280943")
                     filterHex <- hex[hex[,c(10)] >= -0.600746280943,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"10" >= -0.600746280943,]
                Log.info("Filtering out rows by >= from dataset Test_Arabic_Digit_short and column \"9\" using value -0.681238436432")
                     filterHex <- hex[hex[,c(9)] >= -0.681238436432,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"9" >= -0.681238436432,]
                Log.info("Filtering out rows by >= from dataset Test_Arabic_Digit_short and column \"9\" using value 0.000541394602238")
                     filterHex <- hex[hex[,c(9)] >= 0.000541394602238,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"9" >= 0.000541394602238,]
                    Log.info("Filtering out rows by >= from dataset Test_Arabic_Digit_short and column \"4\" using value -0.87580606157, and also subsetting columns.")
                     filterHex <- hex[hex[,c(4)] >= -0.87580606157, c(4)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(4)] >= -0.87580606157, c(11,10,12,1,3,2,5,4,7,6,9,8)]
                    Log.info("Filtering out rows by >= from dataset Test_Arabic_Digit_short and column \"5\" using value 0.00501720235613, and also subsetting columns.")
                     filterHex <- hex[hex[,c(5)] >= 0.00501720235613, c(5)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(5)] >= 0.00501720235613, c(11,10,12,1,3,2,5,4,7,6,9,8)]
                    Log.info("Filtering out rows by >= from dataset Test_Arabic_Digit_short and column \"4\" using value -0.161078701305, and also subsetting columns.")
                     filterHex <- hex[hex[,c(4)] >= -0.161078701305, c(4)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(4)] >= -0.161078701305, c(11,10,12,1,3,2,5,4,7,6,9,8)]
                    Log.info("Filtering out rows by >= from dataset Test_Arabic_Digit_short and column \"5\" using value -2.01722910588, and also subsetting columns.")
                     filterHex <- hex[hex[,c(5)] >= -2.01722910588, c(5)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(5)] >= -2.01722910588, c(11,10,12,1,3,2,5,4,7,6,9,8)]
                    Log.info("Filtering out rows by >= from dataset Test_Arabic_Digit_short and column \"11\" using value -0.415505809579, and also subsetting columns.")
                     filterHex <- hex[hex[,c(11)] >= -0.415505809579, c(11)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(11)] >= -0.415505809579, c(11,10,12,1,3,2,5,4,7,6,9,8)]
                    Log.info("Filtering out rows by >= from dataset Test_Arabic_Digit_short and column \"6\" using value -0.00871826969567, and also subsetting columns.")
                     filterHex <- hex[hex[,c(6)] >= -0.00871826969567, c(6)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(6)] >= -0.00871826969567, c(11,10,12,1,3,2,5,4,7,6,9,8)]
                    Log.info("Filtering out rows by >= from dataset Test_Arabic_Digit_short and column \"11\" using value -0.489062325871, and also subsetting columns.")
                     filterHex <- hex[hex[,c(11)] >= -0.489062325871, c(11)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(11)] >= -0.489062325871, c(11,10,12,1,3,2,5,4,7,6,9,8)]
                    Log.info("Filtering out rows by >= from dataset Test_Arabic_Digit_short and column \"3\" using value -3.06499327939, and also subsetting columns.")
                     filterHex <- hex[hex[,c(3)] >= -3.06499327939, c(3)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(3)] >= -3.06499327939, c(11,10,12,1,3,2,5,4,7,6,9,8)]
                    Log.info("Filtering out rows by >= from dataset Test_Arabic_Digit_short and column \"12\" using value -0.711431591085, and also subsetting columns.")
                     filterHex <- hex[hex[,c(12)] >= -0.711431591085, c(12)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(12)] >= -0.711431591085, c(11,10,12,1,3,2,5,4,7,6,9,8)]
                    Log.info("Filtering out rows by >= from dataset Test_Arabic_Digit_short and column \"12\" using value -0.929704759313, and also subsetting columns.")
                     filterHex <- hex[hex[,c(12)] >= -0.929704759313, c(12)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(12)] >= -0.929704759313, c(11,10,12,1,3,2,5,4,7,6,9,8)]
                    Log.info("Filtering out rows by >= from dataset Test_Arabic_Digit_short and column \"2\" using value 0.352035234022, and also subsetting columns.")
                     filterHex <- hex[hex[,c(2)] >= 0.352035234022, c(2)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(2)] >= 0.352035234022, c(11,10,12,1,3,2,5,4,7,6,9,8)]
                    Log.info("Filtering out rows by >= from dataset Test_Arabic_Digit_short and column \"4\" using value 0.771113752573, and also subsetting columns.")
                     filterHex <- hex[hex[,c(4)] >= 0.771113752573, c(4)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(4)] >= 0.771113752573, c(11,10,12,1,3,2,5,4,7,6,9,8)]
                    Log.info("Filtering out rows by >= from dataset Test_Arabic_Digit_short and column \"10\" using value -0.921677941431, and also subsetting columns.")
                     filterHex <- hex[hex[,c(10)] >= -0.921677941431, c(10)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(10)] >= -0.921677941431, c(11,10,12,1,3,2,5,4,7,6,9,8)]
                    Log.info("Filtering out rows by >= from dataset Test_Arabic_Digit_short and column \"8\" using value -0.699339950807, and also subsetting columns.")
                     filterHex <- hex[hex[,c(8)] >= -0.699339950807, c(8)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(8)] >= -0.699339950807, c(11,10,12,1,3,2,5,4,7,6,9,8)]
                    Log.info("Filtering out rows by >= from dataset Test_Arabic_Digit_short and column \"12\" using value 0.802188364586, and also subsetting columns.")
                     filterHex <- hex[hex[,c(12)] >= 0.802188364586, c(12)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(12)] >= 0.802188364586, c(11,10,12,1,3,2,5,4,7,6,9,8)]
                    Log.info("Filtering out rows by >= from dataset Test_Arabic_Digit_short and column \"10\" using value 0.372709563426, and also subsetting columns.")
                     filterHex <- hex[hex[,c(10)] >= 0.372709563426, c(10)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(10)] >= 0.372709563426, c(11,10,12,1,3,2,5,4,7,6,9,8)]
                    Log.info("Filtering out rows by >= from dataset Test_Arabic_Digit_short and column \"9\" using value -0.175527936176, and also subsetting columns.")
                     filterHex <- hex[hex[,c(9)] >= -0.175527936176, c(9)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(9)] >= -0.175527936176, c(11,10,12,1,3,2,5,4,7,6,9,8)]
                    Log.info("Filtering out rows by >= from dataset Test_Arabic_Digit_short and column \"9\" using value 0.253082831297, and also subsetting columns.")
                     filterHex <- hex[hex[,c(9)] >= 0.253082831297, c(9)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(9)] >= 0.253082831297, c(11,10,12,1,3,2,5,4,7,6,9,8)]
                    Log.info("Filtering out rows by >= from dataset Test_Arabic_Digit_short and column \"8\" using value 0.173940457583, and also subsetting columns.")
                     filterHex <- hex[hex[,c(8)] >= 0.173940457583, c(8)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(8)] >= 0.173940457583, c(11,10,12,1,3,2,5,4,7,6,9,8)]
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("simpleFilterTest_ on data Test_Arabic_Digit_short", simpleFilterTest_Test_Arabic_Digit_short_98(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
