            ##
            # Author: Autogenerated on 2013-11-27 03:20:00
            # gitHash: 25eb0cfd1269362ae85d0f073d9abde2a68ac0e4
            # SEED: 4617575514352894151
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            complexFilterTest_make_me_converge_10000x5_185 <- function(conn) {
                Log.info("A munge-task R unit test on data <make_me_converge_10000x5> testing the functional unit <['!', '!=', '|', '<', '|', '>=']> ")
                Log.info("Uploading make_me_converge_10000x5")
                hex <- h2o.uploadFile(conn, "../../smalldata/logreg/make_me_converge_10000x5.csv", "rmake_me_converge_10000x5.hex")
            Log.info("Performing compound task !( ( hex[,c(1)] != 0.973704551314 ) | ( hex[,c(1)] < 0.414261658949 ) | ( ( hex[,c(2)] >= 0.99394490761 )) ) on dataset <make_me_converge_10000x5>")
                     filterHex <- hex[!( ( hex[,c(1)] != 0.973704551314 ) | ( hex[,c(1)] < 0.414261658949 ) | ( ( hex[,c(2)] >= 0.99394490761 )) ),]
            Log.info("Performing compound task !( ( hex[,c(3)] != 0.365233910775 ) | ( hex[,c(5)] < 0.95880289338 ) | ( ( hex[,c(2)] >= 0.468257256221 )) ) on dataset make_me_converge_10000x5, and also subsetting columns.")
                     filterHex <- hex[!( ( hex[,c(3)] != 0.365233910775 ) | ( hex[,c(5)] < 0.95880289338 ) | ( ( hex[,c(2)] >= 0.468257256221 )) ), c(1,3,2,5,4)]
                Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[!( ( hex[,c(3)] != 0.365233910775 ) | ( hex[,c(5)] < 0.95880289338 ) | ( ( hex[,c(2)] >= 0.468257256221 )) ), c(1)]
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("compoundFilterTest_ on data make_me_converge_10000x5", complexFilterTest_make_me_converge_10000x5_185(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
