            ##
            # Author: Autogenerated on 2013-11-27 18:13:58
            # gitHash: c4ad841105ba82f4a3979e4cf1ae7e20a5905e59
            # SEED: 4663640625336856642
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            simpleFilterTest_hhp_107_01_93 <- function(conn) {
                Log.info("A munge-task R unit test on data <hhp_107_01> testing the functional unit <>=> ")
                Log.info("Uploading hhp_107_01")
                hex <- h2o.uploadFile(conn, locate("../../smalldata/hhp_107_01.data.gz"), "rhhp_107_01.hex")
                Log.info("Filtering out rows by >= from dataset hhp_107_01 and column \"69\" using value 1.21953951488")
                     filterHex <- hex[hex[,c(69)] >= 1.21953951488,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"69" >= 1.21953951488,]
                Log.info("Filtering out rows by >= from dataset hhp_107_01 and column \"74\" using value 26.805578213")
                     filterHex <- hex[hex[,c(74)] >= 26.805578213,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"74" >= 26.805578213,]
                Log.info("Filtering out rows by >= from dataset hhp_107_01 and column \"76\" using value 0.0")
                     filterHex <- hex[hex[,c(76)] >= 0.0,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"76" >= 0.0,]
                Log.info("Filtering out rows by >= from dataset hhp_107_01 and column \"16\" using value 8.02919428069")
                     filterHex <- hex[hex[,c(16)] >= 8.02919428069,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"16" >= 8.02919428069,]
                Log.info("Filtering out rows by >= from dataset hhp_107_01 and column \"75\" using value 35.6288497302")
                     filterHex <- hex[hex[,c(75)] >= 35.6288497302,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"75" >= 35.6288497302,]
                    Log.info("Filtering out rows by >= from dataset hhp_107_01 and column \"53\" using value 22.851774558, and also subsetting columns.")
                     filterHex <- hex[hex[,c(53)] >= 22.851774558, c(53)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(53)] >= 22.851774558, c(24,25,26,27,20,21,22,23,28,29,4,8,59,58,55,54,57,56,51,50,53,52,88,89,82,83,80,81,86,87,84,85,3,7,102,103,100,101,106,104,105,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,48,49,46,47,44,45,42,43,40,41,1,5,9,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by >= from dataset hhp_107_01 and column \"76\" using value 0.0, and also subsetting columns.")
                     filterHex <- hex[hex[,c(76)] >= 0.0, c(76)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(76)] >= 0.0, c(24,25,26,27,20,21,22,23,28,29,4,8,59,58,55,54,57,56,51,50,53,52,88,89,82,83,80,81,86,87,84,85,3,7,102,103,100,101,106,104,105,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,48,49,46,47,44,45,42,43,40,41,1,5,9,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by >= from dataset hhp_107_01 and column \"81\" using value 27.9831282622, and also subsetting columns.")
                     filterHex <- hex[hex[,c(81)] >= 27.9831282622, c(81)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(81)] >= 27.9831282622, c(24,25,26,27,20,21,22,23,28,29,4,8,59,58,55,54,57,56,51,50,53,52,88,89,82,83,80,81,86,87,84,85,3,7,102,103,100,101,106,104,105,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,48,49,46,47,44,45,42,43,40,41,1,5,9,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by >= from dataset hhp_107_01 and column \"31\" using value 32.6479196927, and also subsetting columns.")
                     filterHex <- hex[hex[,c(31)] >= 32.6479196927, c(31)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(31)] >= 32.6479196927, c(24,25,26,27,20,21,22,23,28,29,4,8,59,58,55,54,57,56,51,50,53,52,88,89,82,83,80,81,86,87,84,85,3,7,102,103,100,101,106,104,105,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,48,49,46,47,44,45,42,43,40,41,1,5,9,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by >= from dataset hhp_107_01 and column \"76\" using value 0.0, and also subsetting columns.")
                     filterHex <- hex[hex[,c(76)] >= 0.0, c(76)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(76)] >= 0.0, c(24,25,26,27,20,21,22,23,28,29,4,8,59,58,55,54,57,56,51,50,53,52,88,89,82,83,80,81,86,87,84,85,3,7,102,103,100,101,106,104,105,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,48,49,46,47,44,45,42,43,40,41,1,5,9,77,76,75,74,73,72,71,70,79,78)]
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("simpleFilterTest_ on data hhp_107_01", simpleFilterTest_hhp_107_01_93(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
