            ##
            # Author: Autogenerated on 2013-11-29 01:20:08
            # gitHash: 10810480518d43dd720690e729d2f3b9a0f8eba7
            # SEED: 7977475956795433203
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            simpleFilterTest_clslowbwt_63 <- function(conn) {
                Log.info("A munge-task R unit test on data <clslowbwt> testing the functional unit <!=> ")
                Log.info("Uploading clslowbwt")
                hex <- h2o.uploadFile(conn, locate("../../smalldata/logreg/umass_statdata/clslowbwt.dat"), "rclslowbwt.hex")
                Log.info("Filtering out rows by != from dataset clslowbwt and column \"7\" using value 0.660066488566")
                     filterHex <- hex[hex[,c(7)] != 0.660066488566,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"7" != 0.660066488566,]
                Log.info("Filtering out rows by != from dataset clslowbwt and column \"7\" using value 0.142208570365")
                     filterHex <- hex[hex[,c(7)] != 0.142208570365,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"7" != 0.142208570365,]
                    Log.info("Filtering out rows by != from dataset clslowbwt and column \"7\" using value 0.94249708019, and also subsetting columns.")
                     filterHex <- hex[hex[,c(7)] != 0.94249708019, c(7)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(7)] != 0.94249708019, c(1,3,2,5,4,7,6)]
                    Log.info("Filtering out rows by != from dataset clslowbwt and column \"7\" using value 0.778421455724, and also subsetting columns.")
                     filterHex <- hex[hex[,c(7)] != 0.778421455724, c(7)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(7)] != 0.778421455724, c(1,3,2,5,4,7,6)]
            Log.info("End of test")
            PASSS <<- TRUE
            }
            PASSS <- FALSE
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("simpleFilterTest_ on data clslowbwt", simpleFilterTest_clslowbwt_63(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            if (!PASSS) FAIL("Did not reach the end of test. Check Rsandbox/errors.log for warnings and errors.")
            PASS()
