            ##
            # Author: Autogenerated on 2013-11-27 03:20:00
            # gitHash: 25eb0cfd1269362ae85d0f073d9abde2a68ac0e4
            # SEED: 4617575514352894151
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            complexFilterTest_prostate_cat_replaced_202 <- function(conn) {
                Log.info("A munge-task R unit test on data <prostate_cat_replaced> testing the functional unit <['!', '<=', '&', '==', '|', '>', '&', '>=', '|', '!=']> ")
                Log.info("Uploading prostate_cat_replaced")
                hex <- h2o.uploadFile(conn, "../../smalldata/glm_test/prostate_cat_replaced.csv", "rprostate_cat_replaced.hex")
            Log.info("Performing compound task !( ( hex[,c(\"DCAPS\")] <= 1.23545359691 ) & ( hex[,c(\"AGE\")] == 56.2132223931 ) | ( hex[,c(\"PSA\")] > 55.3828750102 ) & ( hex[,c(\"DPROS\")] >= 1.53495830797 ) | ( ( hex[,c(\"DPROS\")] != 1.33507168777 )) ) on dataset <prostate_cat_replaced>")
                     filterHex <- hex[!( ( hex[,c("DCAPS")] <= 1.23545359691 ) & ( hex[,c("AGE")] == 56.2132223931 ) | ( hex[,c("PSA")] > 55.3828750102 ) & ( hex[,c("DPROS")] >= 1.53495830797 ) | ( ( hex[,c("DPROS")] != 1.33507168777 )) ),]
            Log.info("Performing compound task !( ( hex[,c(\"GLEASON\")] <= 4.03506314397 ) & ( hex[,c(\"ID\")] == 249.894991571 ) | ( hex[,c(\"PSA\")] > 28.2330439153 ) & ( hex[,c(\"PSA\")] >= 59.8545302538 ) | ( ( hex[,c(\"AGE\")] != 73.1420828311 )) ) on dataset prostate_cat_replaced, and also subsetting columns.")
                     filterHex <- hex[!( ( hex[,c("GLEASON")] <= 4.03506314397 ) & ( hex[,c("ID")] == 249.894991571 ) | ( hex[,c("PSA")] > 28.2330439153 ) & ( hex[,c("PSA")] >= 59.8545302538 ) | ( ( hex[,c("AGE")] != 73.1420828311 )) ), c("ID","PSA","DCAPS","VOL","GLEASON","DPROS","CAPSULE","AGE")]
                Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[!( ( hex[,c("GLEASON")] <= 4.03506314397 ) & ( hex[,c("ID")] == 249.894991571 ) | ( hex[,c("PSA")] > 28.2330439153 ) & ( hex[,c("PSA")] >= 59.8545302538 ) | ( ( hex[,c("AGE")] != 73.1420828311 )) ), c("RACE")]
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("compoundFilterTest_ on data prostate_cat_replaced", complexFilterTest_prostate_cat_replaced_202(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
