            ##
            # Author: Autogenerated on 2013-11-27 03:20:00
            # gitHash: 25eb0cfd1269362ae85d0f073d9abde2a68ac0e4
            # SEED: 4617575514352894151
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            complexFilterTest_prostate_4_147 <- function(conn) {
                Log.info("A munge-task R unit test on data <prostate_4> testing the functional unit <['!', '>=']> ")
                Log.info("Uploading prostate_4")
                hex <- h2o.uploadFile(conn, "../../smalldata/parse_folder_test/prostate_4.csv", "rprostate_4.hex")
            Log.info("Performing compound task !( ( ( hex[,c(2)] >= 60.3707684951 )) ) on dataset <prostate_4>")
                     filterHex <- hex[!( ( ( hex[,c(2)] >= 60.3707684951 )) ),]
            Log.info("Performing compound task !( ( ( hex[,c(5)] >= 1.83021046223 )) ) on dataset prostate_4, and also subsetting columns.")
                     filterHex <- hex[!( ( ( hex[,c(5)] >= 1.83021046223 )) ), c(1,2,5,4,7,6,8)]
                Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[!( ( ( hex[,c(5)] >= 1.83021046223 )) ), c(3)]
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("compoundFilterTest_ on data prostate_4", complexFilterTest_prostate_4_147(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
