            ##
            # Author: Autogenerated on 2013-11-27 18:13:59
            # gitHash: c4ad841105ba82f4a3979e4cf1ae7e20a5905e59
            # SEED: 4663640625336856642
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            simpleFilterTest_iris_test_138 <- function(conn) {
                Log.info("A munge-task R unit test on data <iris_test> testing the functional unit <!=> ")
                Log.info("Uploading iris_test")
                hex <- h2o.uploadFile(conn, locate("../../smalldata/iris/iris_test.csv"), "riris_test.hex")
                Log.info("Filtering out rows by != from dataset iris_test and column \"petal_len\" using value 2.50054354325")
                     filterHex <- hex[hex[,c("petal_len")] != 2.50054354325,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"petal_len" != 2.50054354325,]
                Log.info("Filtering out rows by != from dataset iris_test and column \"sepal_wid\" using value 4.1141007004")
                     filterHex <- hex[hex[,c("sepal_wid")] != 4.1141007004,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"sepal_wid" != 4.1141007004,]
                Log.info("Filtering out rows by != from dataset iris_test and column \"petal_len\" using value 1.98442112875")
                     filterHex <- hex[hex[,c("petal_len")] != 1.98442112875,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"petal_len" != 1.98442112875,]
                Log.info("Filtering out rows by != from dataset iris_test and column \"sepal_len\" using value 7.40586870727")
                     filterHex <- hex[hex[,c("sepal_len")] != 7.40586870727,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"sepal_len" != 7.40586870727,]
                Log.info("Filtering out rows by != from dataset iris_test and column \"petal_wid\" using value 1.32265779203")
                     filterHex <- hex[hex[,c("petal_wid")] != 1.32265779203,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"petal_wid" != 1.32265779203,]
                Log.info("Filtering out rows by != from dataset iris_test and column \"petal_len\" using value 4.64161092079")
                     filterHex <- hex[hex[,c("petal_len")] != 4.64161092079,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"petal_len" != 4.64161092079,]
                    Log.info("Filtering out rows by != from dataset iris_test and column \"petal_wid\" using value 0.558319743315, and also subsetting columns.")
                     filterHex <- hex[hex[,c("petal_wid")] != 0.558319743315, c("petal_wid")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("petal_wid")] != 0.558319743315, c("petal_wid","sepal_wid","petal_len","sepal_len","species")]
                    Log.info("Filtering out rows by != from dataset iris_test and column \"petal_len\" using value 1.16919186839, and also subsetting columns.")
                     filterHex <- hex[hex[,c("petal_len")] != 1.16919186839, c("petal_len")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("petal_len")] != 1.16919186839, c("petal_wid","sepal_wid","petal_len","sepal_len","species")]
                    Log.info("Filtering out rows by != from dataset iris_test and column \"sepal_wid\" using value 3.19263164085, and also subsetting columns.")
                     filterHex <- hex[hex[,c("sepal_wid")] != 3.19263164085, c("sepal_wid")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("sepal_wid")] != 3.19263164085, c("petal_wid","sepal_wid","petal_len","sepal_len","species")]
                    Log.info("Filtering out rows by != from dataset iris_test and column \"petal_wid\" using value 1.42888212363, and also subsetting columns.")
                     filterHex <- hex[hex[,c("petal_wid")] != 1.42888212363, c("petal_wid")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("petal_wid")] != 1.42888212363, c("petal_wid","sepal_wid","petal_len","sepal_len","species")]
                    Log.info("Filtering out rows by != from dataset iris_test and column \"sepal_len\" using value 7.35939151574, and also subsetting columns.")
                     filterHex <- hex[hex[,c("sepal_len")] != 7.35939151574, c("sepal_len")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("sepal_len")] != 7.35939151574, c("petal_wid","sepal_wid","petal_len","sepal_len","species")]
                    Log.info("Filtering out rows by != from dataset iris_test and column \"sepal_wid\" using value 3.64367506474, and also subsetting columns.")
                     filterHex <- hex[hex[,c("sepal_wid")] != 3.64367506474, c("sepal_wid")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("sepal_wid")] != 3.64367506474, c("petal_wid","sepal_wid","petal_len","sepal_len","species")]
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("simpleFilterTest_ on data iris_test", simpleFilterTest_iris_test_138(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
