            ##
            # Author: Autogenerated on 2013-11-27 03:20:00
            # gitHash: 25eb0cfd1269362ae85d0f073d9abde2a68ac0e4
            # SEED: 4617575514352894151
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            complexFilterTest_stego_training_modified_156 <- function(conn) {
                Log.info("A munge-task R unit test on data <stego_training_modified> testing the functional unit <['!', '>', '&', '<=', '&', '!|', '!', '==']> ")
                Log.info("Uploading stego_training_modified")
                hex <- h2o.uploadFile(conn, "../../smalldata/stego/stego_training_modified.data", "rstego_training_modified.hex")
            Log.info("Performing compound task !( ( hex[,c(115)] > 0.078153416156 ) & ( hex[,c(111)] <= 0.0188167241034 ) & ( hex[,c(86)] !| 0.105267885144 ) ! ( hex[,c(59)] == 0.0417030428546 )) on dataset <stego_training_modified>")
                     filterHex <- hex[!( ( hex[,c(115)] > 0.078153416156 ) & ( hex[,c(111)] <= 0.0188167241034 ) & ( hex[,c(86)] !| 0.105267885144 ) ! ( hex[,c(59)] == 0.0417030428546 )),]
            Log.info("Performing compound task !( ( hex[,c(79)] > 0.125032692076 ) & ( hex[,c(48)] <= 0.032423956125 ) & ( hex[,c(67)] !| 0.0484999970301 ) ! ( hex[,c(144)] == 0.0765643573221 )) on dataset stego_training_modified, and also subsetting columns.")
                     filterHex <- hex[!( ( hex[,c(79)] > 0.125032692076 ) & ( hex[,c(48)] <= 0.032423956125 ) & ( hex[,c(67)] !| 0.0484999970301 ) ! ( hex[,c(144)] == 0.0765643573221 )), c(144,48,157,26,67,79)]
                Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[!( ( hex[,c(79)] > 0.125032692076 ) & ( hex[,c(48)] <= 0.032423956125 ) & ( hex[,c(67)] !| 0.0484999970301 ) ! ( hex[,c(144)] == 0.0765643573221 )), c(133,132,131,130,137,136,135,134,139,138,24,25,27,20,21,22,23,160,28,29,161,4,8,163,119,120,121,122,123,124,125,126,127,128,129,118,59,58,55,54,57,56,51,50,53,52,115,114,88,89,111,110,113,112,82,83,80,81,86,87,84,85,3,7,108,109,102,103,100,101,106,107,104,105,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,68,69,2,162,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,117,116,151,150,153,152,155,154,156,159,158,49,46,47,44,45,42,43,40,41,1,5,9,146,147,145,142,143,140,141,148,149,77,76,75,74,73,72,71,70,78)]
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("compoundFilterTest_ on data stego_training_modified", complexFilterTest_stego_training_modified_156(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
