            ##
            # Author: Autogenerated on 2013-11-27 03:20:00
            # gitHash: 25eb0cfd1269362ae85d0f073d9abde2a68ac0e4
            # SEED: 4617575514352894151
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            complexFilterTest_iris2_139 <- function(conn) {
                Log.info("A munge-task R unit test on data <iris2> testing the functional unit <['!', '>=']> ")
                Log.info("Uploading iris2")
                hex <- h2o.uploadFile(conn, "../../smalldata/iris/iris2.csv", "riris2.hex")
            Log.info("Performing compound task !( ( ( hex[,c(\"Sepal.Length\")] >= 6.50307468941 )) ) on dataset <iris2>")
                     filterHex <- hex[!( ( ( hex[,c("Sepal.Length")] >= 6.50307468941 )) ),]
            Log.info("Performing compound task !( ( ( hex[,c(\"Sepal.Length\")] >= 4.6261079096 )) ) on dataset iris2, and also subsetting columns.")
                     filterHex <- hex[!( ( ( hex[,c("Sepal.Length")] >= 4.6261079096 )) ), c("Petal.Length","Sepal.Width","Petal.Width","Sepal.Length")]
                Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[!( ( ( hex[,c("Sepal.Length")] >= 4.6261079096 )) ), c("response")]
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("compoundFilterTest_ on data iris2", complexFilterTest_iris2_139(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
