            ##
            # Author: Autogenerated on 2013-11-27 18:13:59
            # gitHash: c4ad841105ba82f4a3979e4cf1ae7e20a5905e59
            # SEED: 4663640625336856642
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            simpleFilterTest_chdage_cleaned_124 <- function(conn) {
                Log.info("A munge-task R unit test on data <chdage_cleaned> testing the functional unit <!=> ")
                Log.info("Uploading chdage_cleaned")
                hex <- h2o.uploadFile(conn, locate("../../smalldata/logreg/umass_statdata/chdage_cleaned.dat"), "rchdage_cleaned.hex")
                Log.info("Filtering out rows by != from dataset chdage_cleaned and column \"1\" using value 54.4036043119")
                     filterHex <- hex[hex[,c(1)] != 54.4036043119,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"1" != 54.4036043119,]
                    Log.info("Filtering out rows by != from dataset chdage_cleaned and column \"2\" using value 0.0863205271266, and also subsetting columns.")
                     filterHex <- hex[hex[,c(2)] != 0.0863205271266, c(2)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(2)] != 0.0863205271266, c(1,2)]
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("simpleFilterTest_ on data chdage_cleaned", simpleFilterTest_chdage_cleaned_124(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
