            ##
            # Author: Autogenerated on 2013-11-29 01:20:08
            # gitHash: 10810480518d43dd720690e729d2f3b9a0f8eba7
            # SEED: 7977475956795433203
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            simpleFilterTest_iris_wheader_48 <- function(conn) {
                Log.info("A munge-task R unit test on data <iris_wheader> testing the functional unit <>=> ")
                Log.info("Uploading iris_wheader")
                hex <- h2o.uploadFile(conn, locate("../../smalldata/iris/iris_wheader.csv.zip"), "riris_wheader.hex")
                Log.info("Filtering out rows by >= from dataset iris_wheader and column \"sepal_wid\" using value 3.06818563996")
                     filterHex <- hex[hex[,c("sepal_wid")] >= 3.06818563996,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"sepal_wid" >= 3.06818563996,]
                Log.info("Filtering out rows by >= from dataset iris_wheader and column \"sepal_len\" using value 7.50984140978")
                     filterHex <- hex[hex[,c("sepal_len")] >= 7.50984140978,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"sepal_len" >= 7.50984140978,]
                Log.info("Filtering out rows by >= from dataset iris_wheader and column \"sepal_wid\" using value 4.16736530779")
                     filterHex <- hex[hex[,c("sepal_wid")] >= 4.16736530779,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"sepal_wid" >= 4.16736530779,]
                    Log.info("Filtering out rows by >= from dataset iris_wheader and column \"petal_len\" using value 4.24683505383, and also subsetting columns.")
                     filterHex <- hex[hex[,c("petal_len")] >= 4.24683505383, c("petal_len")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("petal_len")] >= 4.24683505383, c("petal_wid","sepal_wid","class","petal_len","sepal_len")]
                    Log.info("Filtering out rows by >= from dataset iris_wheader and column \"petal_len\" using value 2.75993412137, and also subsetting columns.")
                     filterHex <- hex[hex[,c("petal_len")] >= 2.75993412137, c("petal_len")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("petal_len")] >= 2.75993412137, c("petal_wid","sepal_wid","class","petal_len","sepal_len")]
                    Log.info("Filtering out rows by >= from dataset iris_wheader and column \"petal_len\" using value 6.23779845431, and also subsetting columns.")
                     filterHex <- hex[hex[,c("petal_len")] >= 6.23779845431, c("petal_len")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("petal_len")] >= 6.23779845431, c("petal_wid","sepal_wid","class","petal_len","sepal_len")]
            Log.info("End of test")
            PASSS <<- TRUE
            }
            PASSS <- FALSE
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("simpleFilterTest_ on data iris_wheader", simpleFilterTest_iris_wheader_48(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            if (!PASSS) FAIL("Did not reach the end of test. Check Rsandbox/errors.log for warnings and errors.")
            PASS()
