            ##
            # Author: Autogenerated on 2013-11-27 17:26:17
            # gitHash: a4fe16d99eb5f003dd7c7d0da17f29e1712eda0f
            # SEED: 8586424275721420395
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            complexFilterTest_Test_Arabic_Digit_short_178 <- function(conn) {
                Log.info("A munge-task R unit test on data <Test_Arabic_Digit_short> testing the functional unit <['', '==', '|', '==', '&', '<']> ")
                Log.info("Uploading Test_Arabic_Digit_short")
                hex <- h2o.uploadFile(conn, locate("../../smalldata/Test_Arabic_Digit_short.data"), "rTest_Arabic_Digit_short.hex")
            Log.info("Performing compound task ( hex[,c(1)] == 6.57960533922 ) | ( hex[,c(6)] == 0.188948407383 ) & ( ( hex[,c(7)] < -1.08695941136 ))  on dataset <Test_Arabic_Digit_short>")
                     filterHex <- hex[( hex[,c(1)] == 6.57960533922 ) | ( hex[,c(6)] == 0.188948407383 ) & ( ( hex[,c(7)] < -1.08695941136 )) ,]
            Log.info("Performing compound task ( hex[,c(7)] == -0.459314468017 ) | ( hex[,c(5)] == -1.75498108546 ) & ( ( hex[,c(10)] < -1.08334265628 ))  on dataset Test_Arabic_Digit_short, and also subsetting columns.")
                     filterHex <- hex[( hex[,c(7)] == -0.459314468017 ) | ( hex[,c(5)] == -1.75498108546 ) & ( ( hex[,c(10)] < -1.08334265628 )) , c(11,10,12,1,3,2,5,7,6,9,8)]
                Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[( hex[,c(7)] == -0.459314468017 ) | ( hex[,c(5)] == -1.75498108546 ) & ( ( hex[,c(10)] < -1.08334265628 )) , c(4)]
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("compoundFilterTest_ on data Test_Arabic_Digit_short", complexFilterTest_Test_Arabic_Digit_short_178(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
