            ##
            # Author: Autogenerated on 2013-11-27 03:20:00
            # gitHash: 25eb0cfd1269362ae85d0f073d9abde2a68ac0e4
            # SEED: 4617575514352894151
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            simpleFilterTest_winesPCA_93 <- function(conn) {
                Log.info("A munge-task R unit test on data <winesPCA> testing the functional unit <>=> ")
                Log.info("Uploading winesPCA")
                hex <- h2o.uploadFile(conn, "../../smalldata/winesPCA.csv", "rwinesPCA.hex")
                Log.info("Filtering out rows by >= from dataset winesPCA and column \"1\" using value 3.61739707568")
                     filterHex <- hex[hex[,c(1)] >= 3.61739707568,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"1" >= 3.61739707568,]
                    Log.info("Filtering out rows by >= from dataset winesPCA and column \"1\" using value 1.08485714494, and also subsetting columns.")
                     filterHex <- hex[hex[,c(1)] >= 1.08485714494, c(1)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(1)] >= 1.08485714494, c(1)]
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("simpleFilterTest_ on data winesPCA", simpleFilterTest_winesPCA_93(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
