            ##
            # Author: Autogenerated on 2013-11-27 17:26:17
            # gitHash: a4fe16d99eb5f003dd7c7d0da17f29e1712eda0f
            # SEED: 8586424275721420395
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            simpleFilterTest_wonkysummary_87 <- function(conn) {
                Log.info("A munge-task R unit test on data <wonkysummary> testing the functional unit <>=> ")
                Log.info("Uploading wonkysummary")
                hex <- h2o.uploadFile(conn, locate("../../smalldata/wonkysummary.csv"), "rwonkysummary.hex")
                Log.info("Filtering out rows by >= from dataset wonkysummary and column \"X1\" using value 185050.490562")
                     filterHex <- hex[hex[,c("X1")] >= 185050.490562,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"X1" >= 185050.490562,]
                Log.info("Filtering out rows by >= from dataset wonkysummary and column \"DV\" using value 22981046.0384")
                     filterHex <- hex[hex[,c("DV")] >= 22981046.0384,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"DV" >= 22981046.0384,]
                    Log.info("Filtering out rows by >= from dataset wonkysummary and column \"Error\" using value -45.9245580415, and also subsetting columns.")
                     filterHex <- hex[hex[,c("Error")] >= -45.9245580415, c("Error")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("Error")] >= -45.9245580415, c("Error","DV","X1")]
                    Log.info("Filtering out rows by >= from dataset wonkysummary and column \"Error\" using value -60.9619362747, and also subsetting columns.")
                     filterHex <- hex[hex[,c("Error")] >= -60.9619362747, c("Error")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("Error")] >= -60.9619362747, c("Error","DV","X1")]
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("simpleFilterTest_ on data wonkysummary", simpleFilterTest_wonkysummary_87(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
