            ##
            # Author: Autogenerated on 2013-11-27 18:13:59
            # gitHash: c4ad841105ba82f4a3979e4cf1ae7e20a5905e59
            # SEED: 4663640625336856642
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            complexFilterTest_iris_test_numeric_extra_161 <- function(conn) {
                Log.info("A munge-task R unit test on data <iris_test_numeric_extra> testing the functional unit <['!', '>', '&', '==', '&', '<=']> ")
                Log.info("Uploading iris_test_numeric_extra")
                hex <- h2o.uploadFile(conn, locate("../../smalldata/test/classifier/iris_test_numeric_extra.csv"), "riris_test_numeric_extra.hex")
            Log.info("Performing compound task !( ( hex[,c(\"sepal_wid\")] > 3.37939441706 ) & ( hex[,c(\"petal_len\")] == 5.69374936247 ) & ( ( hex[,c(\"petal_wid\")] <= 1.02155218623 )) ) on dataset <iris_test_numeric_extra>")
                     filterHex <- hex[!( ( hex[,c("sepal_wid")] > 3.37939441706 ) & ( hex[,c("petal_len")] == 5.69374936247 ) & ( ( hex[,c("petal_wid")] <= 1.02155218623 )) ),]
            Log.info("Performing compound task !( ( hex[,c(\"sepal_wid\")] > 3.45610656592 ) & ( hex[,c(\"petal_len\")] == 5.61894664925 ) & ( ( hex[,c(\"species\")] <= 3.85625197671 )) ) on dataset iris_test_numeric_extra, and also subsetting columns.")
                     filterHex <- hex[!( ( hex[,c("sepal_wid")] > 3.45610656592 ) & ( hex[,c("petal_len")] == 5.61894664925 ) & ( ( hex[,c("species")] <= 3.85625197671 )) ), c("petal_wid","sepal_wid","petal_len","species")]
                Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[!( ( hex[,c("sepal_wid")] > 3.45610656592 ) & ( hex[,c("petal_len")] == 5.61894664925 ) & ( ( hex[,c("species")] <= 3.85625197671 )) ), c("sepal_len")]
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("compoundFilterTest_ on data iris_test_numeric_extra", complexFilterTest_iris_test_numeric_extra_161(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
