            ##
            # Author: Autogenerated on 2013-11-27 03:20:00
            # gitHash: 25eb0cfd1269362ae85d0f073d9abde2a68ac0e4
            # SEED: 4617575514352894151
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            complexFilterTest_copen_179 <- function(conn) {
                Log.info("A munge-task R unit test on data <copen> testing the functional unit <['!', '!=', '|', '<', '|', '>=']> ")
                Log.info("Uploading copen")
                hex <- h2o.uploadFile(conn, "../../smalldata/logreg/princeton/copen.dat", "rcopen.hex")
            Log.info("Performing compound task !( ( hex[,c(\"n\")] != 4.12902971205 ) | ( hex[,c(\"n\")] < 30.8154279998 ) | ( ( hex[,c(\"n\")] >= 39.7748700381 )) ) on dataset <copen>")
                     filterHex <- hex[!( ( hex[,c("n")] != 4.12902971205 ) | ( hex[,c("n")] < 30.8154279998 ) | ( ( hex[,c("n")] >= 39.7748700381 )) ),]
            Log.info("Performing compound task !( ( hex[,c(\"n\")] != 64.3060306222 ) | ( hex[,c(\"n\")] < 41.9878462137 ) | ( ( hex[,c(\"n\")] >= 22.8071163653 )) ) on dataset copen, and also subsetting columns.")
                     filterHex <- hex[!( ( hex[,c("n")] != 64.3060306222 ) | ( hex[,c("n")] < 41.9878462137 ) | ( ( hex[,c("n")] >= 22.8071163653 )) ), c("n")]
                Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[!( ( hex[,c("n")] != 64.3060306222 ) | ( hex[,c("n")] < 41.9878462137 ) | ( ( hex[,c("n")] >= 22.8071163653 )) ), c("influence","housing","contact","satisfaction")]
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("compoundFilterTest_ on data copen", complexFilterTest_copen_179(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
