            ##
            # Author: Autogenerated on 2013-11-27 18:13:59
            # gitHash: c4ad841105ba82f4a3979e4cf1ae7e20a5905e59
            # SEED: 4663640625336856642
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            simpleFilterTest_AirlinesTest_134 <- function(conn) {
                Log.info("A munge-task R unit test on data <AirlinesTest> testing the functional unit <!=> ")
                Log.info("Uploading AirlinesTest")
                hex <- h2o.uploadFile(conn, locate("../../smalldata/airlines/AirlinesTest.csv.zip"), "rAirlinesTest.hex")
                Log.info("Filtering out rows by != from dataset AirlinesTest and column \"Distance\" using value 1600.02981879")
                     filterHex <- hex[hex[,c("Distance")] != 1600.02981879,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"Distance" != 1600.02981879,]
                Log.info("Filtering out rows by != from dataset AirlinesTest and column \"IsDepDelayed_REC\" using value -0.343552456061")
                     filterHex <- hex[hex[,c("IsDepDelayed_REC")] != -0.343552456061,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"IsDepDelayed_REC" != -0.343552456061,]
                Log.info("Filtering out rows by != from dataset AirlinesTest and column \"ArrTime\" using value 391.434844718")
                     filterHex <- hex[hex[,c("ArrTime")] != 391.434844718,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"ArrTime" != 391.434844718,]
                Log.info("Filtering out rows by != from dataset AirlinesTest and column \"ArrTime\" using value 124.031792974")
                     filterHex <- hex[hex[,c("ArrTime")] != 124.031792974,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"ArrTime" != 124.031792974,]
                Log.info("Filtering out rows by != from dataset AirlinesTest and column \"IsDepDelayed_REC\" using value 0.588129357593")
                     filterHex <- hex[hex[,c("IsDepDelayed_REC")] != 0.588129357593,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"IsDepDelayed_REC" != 0.588129357593,]
                Log.info("Filtering out rows by != from dataset AirlinesTest and column \"ArrTime\" using value 397.367534333")
                     filterHex <- hex[hex[,c("ArrTime")] != 397.367534333,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"ArrTime" != 397.367534333,]
                Log.info("Filtering out rows by != from dataset AirlinesTest and column \"DepTime\" using value 777.681367846")
                     filterHex <- hex[hex[,c("DepTime")] != 777.681367846,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"DepTime" != 777.681367846,]
                Log.info("Filtering out rows by != from dataset AirlinesTest and column \"DepTime\" using value 70.2770583547")
                     filterHex <- hex[hex[,c("DepTime")] != 70.2770583547,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"DepTime" != 70.2770583547,]
                Log.info("Filtering out rows by != from dataset AirlinesTest and column \"ArrTime\" using value 219.369897636")
                     filterHex <- hex[hex[,c("ArrTime")] != 219.369897636,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"ArrTime" != 219.369897636,]
                Log.info("Filtering out rows by != from dataset AirlinesTest and column \"IsDepDelayed_REC\" using value 0.809402113059")
                     filterHex <- hex[hex[,c("IsDepDelayed_REC")] != 0.809402113059,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"IsDepDelayed_REC" != 0.809402113059,]
                    Log.info("Filtering out rows by != from dataset AirlinesTest and column \"DepTime\" using value 1370.85562891, and also subsetting columns.")
                     filterHex <- hex[hex[,c("DepTime")] != 1370.85562891, c("DepTime")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("DepTime")] != 1370.85562891, c("Distance","IsDepDelayed_REC","DepTime","Origin","fDayofMonth","fMonth","fDayOfWeek","IsDepDelayed","fYear","Dest","UniqueCarrier","ArrTime")]
                    Log.info("Filtering out rows by != from dataset AirlinesTest and column \"DepTime\" using value 1667.55998859, and also subsetting columns.")
                     filterHex <- hex[hex[,c("DepTime")] != 1667.55998859, c("DepTime")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("DepTime")] != 1667.55998859, c("Distance","IsDepDelayed_REC","DepTime","Origin","fDayofMonth","fMonth","fDayOfWeek","IsDepDelayed","fYear","Dest","UniqueCarrier","ArrTime")]
                    Log.info("Filtering out rows by != from dataset AirlinesTest and column \"Distance\" using value 2608.34037229, and also subsetting columns.")
                     filterHex <- hex[hex[,c("Distance")] != 2608.34037229, c("Distance")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("Distance")] != 2608.34037229, c("Distance","IsDepDelayed_REC","DepTime","Origin","fDayofMonth","fMonth","fDayOfWeek","IsDepDelayed","fYear","Dest","UniqueCarrier","ArrTime")]
                    Log.info("Filtering out rows by != from dataset AirlinesTest and column \"ArrTime\" using value 1937.04909712, and also subsetting columns.")
                     filterHex <- hex[hex[,c("ArrTime")] != 1937.04909712, c("ArrTime")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("ArrTime")] != 1937.04909712, c("Distance","IsDepDelayed_REC","DepTime","Origin","fDayofMonth","fMonth","fDayOfWeek","IsDepDelayed","fYear","Dest","UniqueCarrier","ArrTime")]
                    Log.info("Filtering out rows by != from dataset AirlinesTest and column \"DepTime\" using value 1021.03684304, and also subsetting columns.")
                     filterHex <- hex[hex[,c("DepTime")] != 1021.03684304, c("DepTime")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("DepTime")] != 1021.03684304, c("Distance","IsDepDelayed_REC","DepTime","Origin","fDayofMonth","fMonth","fDayOfWeek","IsDepDelayed","fYear","Dest","UniqueCarrier","ArrTime")]
                    Log.info("Filtering out rows by != from dataset AirlinesTest and column \"DepTime\" using value 1505.36193801, and also subsetting columns.")
                     filterHex <- hex[hex[,c("DepTime")] != 1505.36193801, c("DepTime")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("DepTime")] != 1505.36193801, c("Distance","IsDepDelayed_REC","DepTime","Origin","fDayofMonth","fMonth","fDayOfWeek","IsDepDelayed","fYear","Dest","UniqueCarrier","ArrTime")]
                    Log.info("Filtering out rows by != from dataset AirlinesTest and column \"IsDepDelayed_REC\" using value -0.788344522163, and also subsetting columns.")
                     filterHex <- hex[hex[,c("IsDepDelayed_REC")] != -0.788344522163, c("IsDepDelayed_REC")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("IsDepDelayed_REC")] != -0.788344522163, c("Distance","IsDepDelayed_REC","DepTime","Origin","fDayofMonth","fMonth","fDayOfWeek","IsDepDelayed","fYear","Dest","UniqueCarrier","ArrTime")]
                    Log.info("Filtering out rows by != from dataset AirlinesTest and column \"DepTime\" using value 1316.39786392, and also subsetting columns.")
                     filterHex <- hex[hex[,c("DepTime")] != 1316.39786392, c("DepTime")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("DepTime")] != 1316.39786392, c("Distance","IsDepDelayed_REC","DepTime","Origin","fDayofMonth","fMonth","fDayOfWeek","IsDepDelayed","fYear","Dest","UniqueCarrier","ArrTime")]
                    Log.info("Filtering out rows by != from dataset AirlinesTest and column \"ArrTime\" using value 322.897254019, and also subsetting columns.")
                     filterHex <- hex[hex[,c("ArrTime")] != 322.897254019, c("ArrTime")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("ArrTime")] != 322.897254019, c("Distance","IsDepDelayed_REC","DepTime","Origin","fDayofMonth","fMonth","fDayOfWeek","IsDepDelayed","fYear","Dest","UniqueCarrier","ArrTime")]
                    Log.info("Filtering out rows by != from dataset AirlinesTest and column \"ArrTime\" using value 490.786910494, and also subsetting columns.")
                     filterHex <- hex[hex[,c("ArrTime")] != 490.786910494, c("ArrTime")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("ArrTime")] != 490.786910494, c("Distance","IsDepDelayed_REC","DepTime","Origin","fDayofMonth","fMonth","fDayOfWeek","IsDepDelayed","fYear","Dest","UniqueCarrier","ArrTime")]
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("simpleFilterTest_ on data AirlinesTest", simpleFilterTest_AirlinesTest_134(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
