            ##
            # Author: Autogenerated on 2013-11-27 18:13:59
            # gitHash: c4ad841105ba82f4a3979e4cf1ae7e20a5905e59
            # SEED: 4663640625336856642
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            simpleFilterTest_tnc3_10_119 <- function(conn) {
                Log.info("A munge-task R unit test on data <tnc3_10> testing the functional unit <!=> ")
                Log.info("Uploading tnc3_10")
                hex <- h2o.uploadFile(conn, locate("../../smalldata/tnc3_10.csv"), "rtnc3_10.hex")
                Log.info("Filtering out rows by != from dataset tnc3_10 and column \"fare\" using value 45.2160112444")
                     filterHex <- hex[hex[,c("fare")] != 45.2160112444,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"fare" != 45.2160112444,]
                    Log.info("Filtering out rows by != from dataset tnc3_10 and column \"parch\" using value 1.48909193428, and also subsetting columns.")
                     filterHex <- hex[hex[,c("parch")] != 1.48909193428, c("parch")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("parch")] != 1.48909193428, c("boat","name","sex","fare","pclass","survived","ticket","cabin","age","body","embarked","home.dest","sibsp","parch")]
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("simpleFilterTest_ on data tnc3_10", simpleFilterTest_tnc3_10_119(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
