            ##
            # Author: Autogenerated on 2013-11-27 17:26:17
            # gitHash: a4fe16d99eb5f003dd7c7d0da17f29e1712eda0f
            # SEED: 8586424275721420395
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            complexFilterTest_allyears2k_187 <- function(conn) {
                Log.info("A munge-task R unit test on data <allyears2k> testing the functional unit <['', '==', '|', '==', '&', '<']> ")
                Log.info("Uploading allyears2k")
                hex <- h2o.uploadFile(conn, locate("../../smalldata/airlines/allyears2k.zip"), "rallyears2k.hex")
            Log.info("Performing compound task ( hex[,c(21)] == 0.279617857602 ) | ( hex[,c(12)] == 287.03164546 ) & ( ( hex[,c(20)] < 135.226070598 ))  on dataset <allyears2k>")
                     filterHex <- hex[( hex[,c(21)] == 0.279617857602 ) | ( hex[,c(12)] == 287.03164546 ) & ( ( hex[,c(20)] < 135.226070598 )) ,]
            Log.info("Performing compound task ( hex[,c(3)] == 3.81227673281 ) | ( hex[,c(2)] == 9.68618147554 ) & ( ( hex[,c(7)] < 852.078831745 ))  on dataset allyears2k, and also subsetting columns.")
                     filterHex <- hex[( hex[,c(3)] == 3.81227673281 ) | ( hex[,c(2)] == 9.68618147554 ) & ( ( hex[,c(7)] < 852.078831745 )) , c(24,25,26,20,21,23,28,1,3,2,5,4,7,6,9,11,10,13,12,15,14,19,18)]
                Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[( hex[,c(3)] == 3.81227673281 ) | ( hex[,c(2)] == 9.68618147554 ) & ( ( hex[,c(7)] < 852.078831745 )) , c(27,17,22,16,30,29,8)]
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("compoundFilterTest_ on data allyears2k", complexFilterTest_allyears2k_187(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
