            ##
            # Author: Autogenerated on 2013-11-27 18:13:59
            # gitHash: c4ad841105ba82f4a3979e4cf1ae7e20a5905e59
            # SEED: 4663640625336856642
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            complexFilterTest_na_test_139 <- function(conn) {
                Log.info("A munge-task R unit test on data <na_test> testing the functional unit <['', '==']> ")
                Log.info("Uploading na_test")
                hex <- h2o.uploadFile(conn, locate("../../smalldata/test/na_test.zip"), "rna_test.hex")
            Log.info("Performing compound task ( ( hex[,c(\"C2Chunk\")] == 1895.28313329 ))  on dataset <na_test>")
                     filterHex <- hex[( ( hex[,c("C2Chunk")] == 1895.28313329 )) ,]
            Log.info("Performing compound task ( ( hex[,c(\"C8DChunk\")] == 4.54223162712e+29 ))  on dataset na_test, and also subsetting columns.")
                     filterHex <- hex[( ( hex[,c("C8DChunk")] == 4.54223162712e+29 )) , c("C8DChunk","C1SChunk")]
                Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[( ( hex[,c("C8DChunk")] == 4.54223162712e+29 )) , c("C1Chunk","C2SChunk","C4FChunk","C2Chunk","C4Chunk","C8Chunk")]
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("compoundFilterTest_ on data na_test", complexFilterTest_na_test_139(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
