            ##
            # Author: Autogenerated on 2013-11-27 18:13:59
            # gitHash: c4ad841105ba82f4a3979e4cf1ae7e20a5905e59
            # SEED: 4663640625336856642
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            complexFilterTest_iris_test_151 <- function(conn) {
                Log.info("A munge-task R unit test on data <iris_test> testing the functional unit <['', '==']> ")
                Log.info("Uploading iris_test")
                hex <- h2o.uploadFile(conn, locate("../../smalldata/test/classifier/iris_test.csv"), "riris_test.hex")
            Log.info("Performing compound task ( ( hex[,c(\"petal_len\")] == 3.09071686114 ))  on dataset <iris_test>")
                     filterHex <- hex[( ( hex[,c("petal_len")] == 3.09071686114 )) ,]
            Log.info("Performing compound task ( ( hex[,c(\"petal_len\")] == 1.57964332347 ))  on dataset iris_test, and also subsetting columns.")
                     filterHex <- hex[( ( hex[,c("petal_len")] == 1.57964332347 )) , c("petal_wid","sepal_wid","petal_len","sepal_len")]
                Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[( ( hex[,c("petal_len")] == 1.57964332347 )) , c("species")]
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("compoundFilterTest_ on data iris_test", complexFilterTest_iris_test_151(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
