            ##
            # Author: Autogenerated on 2013-12-05 22:49:50
            # gitHash: dbc23230f6666890a6cb7c4234e68e540e096e0c
            # SEED: 779905237530228736
            ##
            source('./findNSourceUtils.R')
            simpleFilterTest_prostate_4_6 <- function(conn) {
                Log.info("A munge-task R unit test on data <prostate_4> testing the functional unit <<> ")
                Log.info("Uploading prostate_4")
                hex <- h2o.uploadFile(conn, locate("../../smalldata/parse_folder_test/prostate_4.csv"), "rprostate_4.hex")
                Log.info("Filtering out rows by < from dataset prostate_4 and column \"5\" using value 1.68726502541")
                     filterHex <- hex[hex[,c(5)] < 1.68726502541,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"5" < 1.68726502541,]
                Log.info("Filtering out rows by < from dataset prostate_4 and column \"6\" using value 44.5776865858")
                     filterHex <- hex[hex[,c(6)] < 44.5776865858,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"6" < 44.5776865858,]
                Log.info("Filtering out rows by < from dataset prostate_4 and column \"8\" using value 6.85324484218")
                     filterHex <- hex[hex[,c(8)] < 6.85324484218,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"8" < 6.85324484218,]
                Log.info("Filtering out rows by < from dataset prostate_4 and column \"4\" using value 1.96186748456")
                     filterHex <- hex[hex[,c(4)] < 1.96186748456,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"4" < 1.96186748456,]
                Log.info("Filtering out rows by < from dataset prostate_4 and column \"1\" using value 0.933859932591")
                     filterHex <- hex[hex[,c(1)] < 0.933859932591,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"1" < 0.933859932591,]
                Log.info("Filtering out rows by < from dataset prostate_4 and column \"1\" using value 0.0875966018421")
                     filterHex <- hex[hex[,c(1)] < 0.0875966018421,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"1" < 0.0875966018421,]
                Log.info("Filtering out rows by < from dataset prostate_4 and column \"7\" using value 77.424752819")
                     filterHex <- hex[hex[,c(7)] < 77.424752819,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"7" < 77.424752819,]
                Log.info("Filtering out rows by < from dataset prostate_4 and column \"5\" using value 1.32608865269")
                     filterHex <- hex[hex[,c(5)] < 1.32608865269,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"5" < 1.32608865269,]
                Log.info("Filtering out rows by < from dataset prostate_4 and column \"7\" using value 60.9017320286")
                     filterHex <- hex[hex[,c(7)] < 60.9017320286,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"7" < 60.9017320286,]
                Log.info("Filtering out rows by < from dataset prostate_4 and column \"5\" using value 1.5422053803")
                     filterHex <- hex[hex[,c(5)] < 1.5422053803,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"5" < 1.5422053803,]
                Log.info("Filtering out rows by < from dataset prostate_4 and column \"7\" using value 40.776681183")
                     filterHex <- hex[hex[,c(7)] < 40.776681183,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"7" < 40.776681183,]
                    Log.info("Filtering out rows by < from dataset prostate_4 and column \"1\" using value 0.00172967343572, and also subsetting columns.")
                     filterHex <- hex[hex[,c(1)] < 0.00172967343572, c(1)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(1)] < 0.00172967343572, c(1,3,2,5,4,7,6,8)]
                    Log.info("Filtering out rows by < from dataset prostate_4 and column \"7\" using value 19.17846522, and also subsetting columns.")
                     filterHex <- hex[hex[,c(7)] < 19.17846522, c(7)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(7)] < 19.17846522, c(1,3,2,5,4,7,6,8)]
                    Log.info("Filtering out rows by < from dataset prostate_4 and column \"6\" using value 9.54502105772, and also subsetting columns.")
                     filterHex <- hex[hex[,c(6)] < 9.54502105772, c(6)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(6)] < 9.54502105772, c(1,3,2,5,4,7,6,8)]
                    Log.info("Filtering out rows by < from dataset prostate_4 and column \"7\" using value 66.0607467068, and also subsetting columns.")
                     filterHex <- hex[hex[,c(7)] < 66.0607467068, c(7)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(7)] < 66.0607467068, c(1,3,2,5,4,7,6,8)]
                    Log.info("Filtering out rows by < from dataset prostate_4 and column \"2\" using value 75.5708003502, and also subsetting columns.")
                     filterHex <- hex[hex[,c(2)] < 75.5708003502, c(2)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(2)] < 75.5708003502, c(1,3,2,5,4,7,6,8)]
                    Log.info("Filtering out rows by < from dataset prostate_4 and column \"5\" using value 1.82185845734, and also subsetting columns.")
                     filterHex <- hex[hex[,c(5)] < 1.82185845734, c(5)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(5)] < 1.82185845734, c(1,3,2,5,4,7,6,8)]
                    Log.info("Filtering out rows by < from dataset prostate_4 and column \"6\" using value 17.38027161, and also subsetting columns.")
                     filterHex <- hex[hex[,c(6)] < 17.38027161, c(6)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(6)] < 17.38027161, c(1,3,2,5,4,7,6,8)]
                    Log.info("Filtering out rows by < from dataset prostate_4 and column \"6\" using value 2.60075189237, and also subsetting columns.")
                     filterHex <- hex[hex[,c(6)] < 2.60075189237, c(6)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(6)] < 2.60075189237, c(1,3,2,5,4,7,6,8)]
                    Log.info("Filtering out rows by < from dataset prostate_4 and column \"7\" using value 82.6392533504, and also subsetting columns.")
                     filterHex <- hex[hex[,c(7)] < 82.6392533504, c(7)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(7)] < 82.6392533504, c(1,3,2,5,4,7,6,8)]
                    Log.info("Filtering out rows by < from dataset prostate_4 and column \"1\" using value 0.591172778662, and also subsetting columns.")
                     filterHex <- hex[hex[,c(1)] < 0.591172778662, c(1)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(1)] < 0.591172778662, c(1,3,2,5,4,7,6,8)]
                    Log.info("Filtering out rows by < from dataset prostate_4 and column \"1\" using value 0.7142898393, and also subsetting columns.")
                     filterHex <- hex[hex[,c(1)] < 0.7142898393, c(1)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(1)] < 0.7142898393, c(1,3,2,5,4,7,6,8)]
            testEnd()
            }
            doTest("simpleFilterTest_ on data prostate_4 unit= <", simpleFilterTest_prostate_4_6)
