            ##
            # Author: Autogenerated on 2013-11-27 17:26:17
            # gitHash: a4fe16d99eb5f003dd7c7d0da17f29e1712eda0f
            # SEED: 8586424275721420395
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            simpleFilterTest_iris_test_84 <- function(conn) {
                Log.info("A munge-task R unit test on data <iris_test> testing the functional unit <>=> ")
                Log.info("Uploading iris_test")
                hex <- h2o.uploadFile(conn, locate("../../smalldata/test/classifier/iris_test.csv"), "riris_test.hex")
                Log.info("Filtering out rows by >= from dataset iris_test and column \"petal_len\" using value 3.00959297732")
                     filterHex <- hex[hex[,c("petal_len")] >= 3.00959297732,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"petal_len" >= 3.00959297732,]
                Log.info("Filtering out rows by >= from dataset iris_test and column \"sepal_len\" using value 7.57374495069")
                     filterHex <- hex[hex[,c("sepal_len")] >= 7.57374495069,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"sepal_len" >= 7.57374495069,]
                Log.info("Filtering out rows by >= from dataset iris_test and column \"sepal_len\" using value 5.0344818223")
                     filterHex <- hex[hex[,c("sepal_len")] >= 5.0344818223,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"sepal_len" >= 5.0344818223,]
                    Log.info("Filtering out rows by >= from dataset iris_test and column \"petal_wid\" using value 0.29097327433, and also subsetting columns.")
                     filterHex <- hex[hex[,c("petal_wid")] >= 0.29097327433, c("petal_wid")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("petal_wid")] >= 0.29097327433, c("petal_wid","sepal_wid","petal_len","sepal_len","species")]
                    Log.info("Filtering out rows by >= from dataset iris_test and column \"sepal_len\" using value 5.99939880254, and also subsetting columns.")
                     filterHex <- hex[hex[,c("sepal_len")] >= 5.99939880254, c("sepal_len")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("sepal_len")] >= 5.99939880254, c("petal_wid","sepal_wid","petal_len","sepal_len","species")]
                    Log.info("Filtering out rows by >= from dataset iris_test and column \"sepal_wid\" using value 3.95414380426, and also subsetting columns.")
                     filterHex <- hex[hex[,c("sepal_wid")] >= 3.95414380426, c("sepal_wid")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("sepal_wid")] >= 3.95414380426, c("petal_wid","sepal_wid","petal_len","sepal_len","species")]
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("simpleFilterTest_ on data iris_test", simpleFilterTest_iris_test_84(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
