            ##
            # Author: Autogenerated on 2013-11-27 16:42:11
            # gitHash: 309fddf242f8fc44e7492e4851b0e0335ca5808b
            # SEED: 8361750421268902493
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            complexFilterTest_test_200 <- function(conn) {
                Log.info("A munge-task R unit test on data <test> testing the functional unit <['', '>', '|', '==', '|', '<=', '&', '<=', '&', '!|', '!', '!=']> ")
                Log.info("Uploading test")
                hex <- h2o.uploadFile(conn, locate("../../smalldata/chess/chess_2x2x1000/h2o/test.csv"), "rtest.hex")
            Log.info("Performing compound task ( hex[,c(\"y\")] > 1.29507461577 ) | ( hex[,c(\"y\")] == 0.567627963876 ) | ( hex[,c(\"x\")] <= 1.69615171185 ) & ( hex[,c(\"x\")] <= 0.0077046494947 ) & ( hex[,c(\"x\")] !| 0.0924968773071 ) ! ( hex[,c(\"x\")] != 1.72719773878 ) on dataset <test>")
                     filterHex <- hex[( hex[,c("y")] > 1.29507461577 ) | ( hex[,c("y")] == 0.567627963876 ) | ( hex[,c("x")] <= 1.69615171185 ) & ( hex[,c("x")] <= 0.0077046494947 ) & ( hex[,c("x")] !| 0.0924968773071 ) ! ( hex[,c("x")] != 1.72719773878 ),]
            Log.info("Performing compound task ( hex[,c(\"x\")] > 0.228202655883 ) | ( hex[,c(\"x\")] == 1.30879903042 ) | ( hex[,c(\"x\")] <= 0.0190021962831 ) & ( hex[,c(\"y\")] <= 1.97105733515 ) & ( hex[,c(\"x\")] !| 0.304449174205 ) ! ( hex[,c(\"y\")] != 0.584105363615 ) on dataset test, and also subsetting columns.")
                     filterHex <- hex[( hex[,c("x")] > 0.228202655883 ) | ( hex[,c("x")] == 1.30879903042 ) | ( hex[,c("x")] <= 0.0190021962831 ) & ( hex[,c("y")] <= 1.97105733515 ) & ( hex[,c("x")] !| 0.304449174205 ) ! ( hex[,c("y")] != 0.584105363615 ), c("x","y")]
                Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[( hex[,c("x")] > 0.228202655883 ) | ( hex[,c("x")] == 1.30879903042 ) | ( hex[,c("x")] <= 0.0190021962831 ) & ( hex[,c("y")] <= 1.97105733515 ) & ( hex[,c("x")] !| 0.304449174205 ) ! ( hex[,c("y")] != 0.584105363615 ), c("color")]
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("compoundFilterTest_ on data test", complexFilterTest_test_200(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
