            ##
            # Author: Autogenerated on 2013-11-27 18:13:58
            # gitHash: c4ad841105ba82f4a3979e4cf1ae7e20a5905e59
            # SEED: 4663640625336856642
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            simpleFilterTest_make_me_converge_10000x5_67 <- function(conn) {
                Log.info("A munge-task R unit test on data <make_me_converge_10000x5> testing the functional unit <>> ")
                Log.info("Uploading make_me_converge_10000x5")
                hex <- h2o.uploadFile(conn, locate("../../smalldata/logreg/make_me_converge_10000x5.csv"), "rmake_me_converge_10000x5.hex")
                Log.info("Filtering out rows by > from dataset make_me_converge_10000x5 and column \"4\" using value 0.029677371225")
                     filterHex <- hex[hex[,c(4)] > 0.029677371225,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"4" > 0.029677371225,]
                Log.info("Filtering out rows by > from dataset make_me_converge_10000x5 and column \"4\" using value 0.172611553133")
                     filterHex <- hex[hex[,c(4)] > 0.172611553133,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"4" > 0.172611553133,]
                Log.info("Filtering out rows by > from dataset make_me_converge_10000x5 and column \"1\" using value 0.233290948306")
                     filterHex <- hex[hex[,c(1)] > 0.233290948306,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"1" > 0.233290948306,]
                Log.info("Filtering out rows by > from dataset make_me_converge_10000x5 and column \"4\" using value 0.460888299457")
                     filterHex <- hex[hex[,c(4)] > 0.460888299457,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"4" > 0.460888299457,]
                Log.info("Filtering out rows by > from dataset make_me_converge_10000x5 and column \"4\" using value 0.646446176182")
                     filterHex <- hex[hex[,c(4)] > 0.646446176182,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"4" > 0.646446176182,]
                Log.info("Filtering out rows by > from dataset make_me_converge_10000x5 and column \"4\" using value 0.992451838605")
                     filterHex <- hex[hex[,c(4)] > 0.992451838605,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"4" > 0.992451838605,]
                Log.info("Filtering out rows by > from dataset make_me_converge_10000x5 and column \"4\" using value 0.397697978394")
                     filterHex <- hex[hex[,c(4)] > 0.397697978394,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"4" > 0.397697978394,]
                Log.info("Filtering out rows by > from dataset make_me_converge_10000x5 and column \"4\" using value 0.0253280694147")
                     filterHex <- hex[hex[,c(4)] > 0.0253280694147,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"4" > 0.0253280694147,]
                Log.info("Filtering out rows by > from dataset make_me_converge_10000x5 and column \"5\" using value 0.494556921631")
                     filterHex <- hex[hex[,c(5)] > 0.494556921631,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"5" > 0.494556921631,]
                Log.info("Filtering out rows by > from dataset make_me_converge_10000x5 and column \"3\" using value 0.807733371995")
                     filterHex <- hex[hex[,c(3)] > 0.807733371995,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"3" > 0.807733371995,]
                    Log.info("Filtering out rows by > from dataset make_me_converge_10000x5 and column \"2\" using value 0.960066133969, and also subsetting columns.")
                     filterHex <- hex[hex[,c(2)] > 0.960066133969, c(2)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(2)] > 0.960066133969, c(1,3,2,5,4)]
                    Log.info("Filtering out rows by > from dataset make_me_converge_10000x5 and column \"4\" using value 0.747727911038, and also subsetting columns.")
                     filterHex <- hex[hex[,c(4)] > 0.747727911038, c(4)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(4)] > 0.747727911038, c(1,3,2,5,4)]
                    Log.info("Filtering out rows by > from dataset make_me_converge_10000x5 and column \"0\" using value 0.194927804387, and also subsetting columns.")
                     filterHex <- hex[hex[,c(1)] > 0.194927804387, c(1)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(1)] > 0.194927804387, c(1,3,2,5,4)]
                    Log.info("Filtering out rows by > from dataset make_me_converge_10000x5 and column \"1\" using value 0.0577763061742, and also subsetting columns.")
                     filterHex <- hex[hex[,c(1)] > 0.0577763061742, c(1)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(1)] > 0.0577763061742, c(1,3,2,5,4)]
                    Log.info("Filtering out rows by > from dataset make_me_converge_10000x5 and column \"0\" using value 0.310622331588, and also subsetting columns.")
                     filterHex <- hex[hex[,c(1)] > 0.310622331588, c(1)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(1)] > 0.310622331588, c(1,3,2,5,4)]
                    Log.info("Filtering out rows by > from dataset make_me_converge_10000x5 and column \"2\" using value 0.301808636882, and also subsetting columns.")
                     filterHex <- hex[hex[,c(2)] > 0.301808636882, c(2)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(2)] > 0.301808636882, c(1,3,2,5,4)]
                    Log.info("Filtering out rows by > from dataset make_me_converge_10000x5 and column \"1\" using value 0.0110286551652, and also subsetting columns.")
                     filterHex <- hex[hex[,c(1)] > 0.0110286551652, c(1)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(1)] > 0.0110286551652, c(1,3,2,5,4)]
                    Log.info("Filtering out rows by > from dataset make_me_converge_10000x5 and column \"0\" using value 0.274613200026, and also subsetting columns.")
                     filterHex <- hex[hex[,c(1)] > 0.274613200026, c(1)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(1)] > 0.274613200026, c(1,3,2,5,4)]
                    Log.info("Filtering out rows by > from dataset make_me_converge_10000x5 and column \"3\" using value 0.466080343343, and also subsetting columns.")
                     filterHex <- hex[hex[,c(3)] > 0.466080343343, c(3)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(3)] > 0.466080343343, c(1,3,2,5,4)]
                    Log.info("Filtering out rows by > from dataset make_me_converge_10000x5 and column \"5\" using value 0.739638815258, and also subsetting columns.")
                     filterHex <- hex[hex[,c(5)] > 0.739638815258, c(5)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(5)] > 0.739638815258, c(1,3,2,5,4)]
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("simpleFilterTest_ on data make_me_converge_10000x5", simpleFilterTest_make_me_converge_10000x5_67(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
