            ##
            # Author: Autogenerated on 2013-11-27 03:20:00
            # gitHash: 25eb0cfd1269362ae85d0f073d9abde2a68ac0e4
            # SEED: 4617575514352894151
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            complexFilterTest_test_200 <- function(conn) {
                Log.info("A munge-task R unit test on data <test> testing the functional unit <['!', '<=', '&', '==', '|', '>', '&', '>=', '|', '!=']> ")
                Log.info("Uploading test")
                hex <- h2o.uploadFile(conn, "../../smalldata/chess/chess_2x2x10/weka/test.csv.arff", "rtest.hex")
            Log.info("Performing compound task !( ( hex[,c(1)] <= 0.402218320285 ) & ( hex[,c(1)] == 1.91888152468 ) | ( hex[,c(1)] > 0.238881032985 ) & ( hex[,c(1)] >= 0.163925504901 ) | ( ( hex[,c(1)] != 0.746822774792 )) ) on dataset <test>")
                     filterHex <- hex[!( ( hex[,c(1)] <= 0.402218320285 ) & ( hex[,c(1)] == 1.91888152468 ) | ( hex[,c(1)] > 0.238881032985 ) & ( hex[,c(1)] >= 0.163925504901 ) | ( ( hex[,c(1)] != 0.746822774792 )) ),]
            Log.info("Performing compound task !( ( hex[,c(1)] <= 1.57361203603 ) & ( hex[,c(1)] == 0.253517650205 ) | ( hex[,c(1)] > 1.82703662976 ) & ( hex[,c(1)] >= 0.858825140798 ) | ( ( hex[,c(1)] != 0.509333807363 )) ) on dataset test, and also subsetting columns.")
                     filterHex <- hex[!( ( hex[,c(1)] <= 1.57361203603 ) & ( hex[,c(1)] == 0.253517650205 ) | ( hex[,c(1)] > 1.82703662976 ) & ( hex[,c(1)] >= 0.858825140798 ) | ( ( hex[,c(1)] != 0.509333807363 )) ), c(1)]
                Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[!( ( hex[,c(1)] <= 1.57361203603 ) & ( hex[,c(1)] == 0.253517650205 ) | ( hex[,c(1)] > 1.82703662976 ) & ( hex[,c(1)] >= 0.858825140798 ) | ( ( hex[,c(1)] != 0.509333807363 )) ), c(2)]
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("compoundFilterTest_ on data test", complexFilterTest_test_200(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
