            ##
            # Author: Autogenerated on 2013-11-27 17:26:17
            # gitHash: a4fe16d99eb5f003dd7c7d0da17f29e1712eda0f
            # SEED: 8586424275721420395
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            sliceTest_iris22_4 <- function(conn) {
                Log.info("A munge-task R unit test on data <iris22> testing the functional unit <[> ")
                Log.info("Uploading iris22")
                hex <- h2o.uploadFile(conn, locate("../../smalldata/iris/iris22.csv"), "riris22.hex")
                Log.info("Performing a column slice of iris22 using these columns: c(\"sepal_wid\",\"sepal_len\")")
                slicedHex <- hex[,c("sepal_wid","sepal_len")]
                    Log.info("Performing a 1-by-1 column slice of iris22 using these columns: ")
                    Log.info("Performing a 1-by-1 row slice of iris22 using these rows: ")
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("sliceTest_ on data iris22", sliceTest_iris22_4(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
