            ##
            # Author: Autogenerated on 2013-11-27 18:13:59
            # gitHash: c4ad841105ba82f4a3979e4cf1ae7e20a5905e59
            # SEED: 4663640625336856642
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            simpleFilterTest_test_enum_domain_size_133 <- function(conn) {
                Log.info("A munge-task R unit test on data <test_enum_domain_size> testing the functional unit <!=> ")
                Log.info("Uploading test_enum_domain_size")
                hex <- h2o.uploadFile(conn, locate("../../smalldata/test/test_enum_domain_size.csv"), "rtest_enum_domain_size.hex")
                Log.info("Filtering out rows by != from dataset test_enum_domain_size and column \"A1\" using value 3.93888428301")
                     filterHex <- hex[hex[,c("A1")] != 3.93888428301,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"A1" != 3.93888428301,]
                Log.info("Filtering out rows by != from dataset test_enum_domain_size and column \"A2\" using value 7.64675771373")
                     filterHex <- hex[hex[,c("A2")] != 7.64675771373,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"A2" != 7.64675771373,]
                Log.info("Filtering out rows by != from dataset test_enum_domain_size and column \"A1\" using value 3.43511990726")
                     filterHex <- hex[hex[,c("A1")] != 3.43511990726,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"A1" != 3.43511990726,]
                Log.info("Filtering out rows by != from dataset test_enum_domain_size and column \"A1\" using value 2.62956368343")
                     filterHex <- hex[hex[,c("A1")] != 2.62956368343,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"A1" != 2.62956368343,]
                    Log.info("Filtering out rows by != from dataset test_enum_domain_size and column \"A2\" using value 6.29483873367, and also subsetting columns.")
                     filterHex <- hex[hex[,c("A2")] != 6.29483873367, c("A2")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("A2")] != 6.29483873367, c("A1","A2","A3")]
                    Log.info("Filtering out rows by != from dataset test_enum_domain_size and column \"A1\" using value 3.76160815915, and also subsetting columns.")
                     filterHex <- hex[hex[,c("A1")] != 3.76160815915, c("A1")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("A1")] != 3.76160815915, c("A1","A2","A3")]
                    Log.info("Filtering out rows by != from dataset test_enum_domain_size and column \"A2\" using value 6.21167544626, and also subsetting columns.")
                     filterHex <- hex[hex[,c("A2")] != 6.21167544626, c("A2")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("A2")] != 6.21167544626, c("A1","A2","A3")]
                    Log.info("Filtering out rows by != from dataset test_enum_domain_size and column \"A2\" using value 5.91848444937, and also subsetting columns.")
                     filterHex <- hex[hex[,c("A2")] != 5.91848444937, c("A2")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("A2")] != 5.91848444937, c("A1","A2","A3")]
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("simpleFilterTest_ on data test_enum_domain_size", simpleFilterTest_test_enum_domain_size_133(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
