            ##
            # Author: Autogenerated on 2013-11-27 18:13:59
            # gitHash: c4ad841105ba82f4a3979e4cf1ae7e20a5905e59
            # SEED: 4663640625336856642
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            complexFilterTest_test_157 <- function(conn) {
                Log.info("A munge-task R unit test on data <test> testing the functional unit <['', '==']> ")
                Log.info("Uploading test")
                hex <- h2o.uploadFile(conn, locate("../../smalldata/chess/chess_2x2x1000/weka/test.csv.arff"), "rtest.hex")
            Log.info("Performing compound task ( ( hex[,c(1)] == 0.52838441389 ))  on dataset <test>")
                     filterHex <- hex[( ( hex[,c(1)] == 0.52838441389 )) ,]
            Log.info("Performing compound task ( ( hex[,c(1)] == 1.70351752988 ))  on dataset test, and also subsetting columns.")
                     filterHex <- hex[( ( hex[,c(1)] == 1.70351752988 )) , c(1)]
                Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[( ( hex[,c(1)] == 1.70351752988 )) , c(2)]
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("compoundFilterTest_ on data test", complexFilterTest_test_157(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
