            ##
            # Author: Autogenerated on 2013-11-27 17:26:17
            # gitHash: a4fe16d99eb5f003dd7c7d0da17f29e1712eda0f
            # SEED: 8586424275721420395
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            complexFilterTest_train_145 <- function(conn) {
                Log.info("A munge-task R unit test on data <train> testing the functional unit <['!', '!=']> ")
                Log.info("Uploading train")
                hex <- h2o.uploadFile(conn, locate("../../smalldata/chess/chess_1x2x1000/h2o/train.csv"), "rtrain.hex")
            Log.info("Performing compound task !( ( ( hex[,c(\"x\")] != 0.978715433484 )) ) on dataset <train>")
                     filterHex <- hex[!( ( ( hex[,c("x")] != 0.978715433484 )) ),]
            Log.info("Performing compound task !( ( ( hex[,c(\"x\")] != 0.413598715423 )) ) on dataset train, and also subsetting columns.")
                     filterHex <- hex[!( ( ( hex[,c("x")] != 0.413598715423 )) ), c("x","y")]
                Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[!( ( ( hex[,c("x")] != 0.413598715423 )) ), c("color")]
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("compoundFilterTest_ on data train", complexFilterTest_train_145(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
