            ##
            # Author: Autogenerated on 2013-11-27 03:20:00
            # gitHash: 25eb0cfd1269362ae85d0f073d9abde2a68ac0e4
            # SEED: 4617575514352894151
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            complexFilterTest_iris_test_numeric_missing_extra_182 <- function(conn) {
                Log.info("A munge-task R unit test on data <iris_test_numeric_missing_extra> testing the functional unit <['!', '!=', '|', '<', '|', '>=']> ")
                Log.info("Uploading iris_test_numeric_missing_extra")
                hex <- h2o.uploadFile(conn, "../../smalldata/test/classifier/iris_test_numeric_missing_extra.csv", "riris_test_numeric_missing_extra.hex")
            Log.info("Performing compound task !( ( hex[,c(\"sepal_len\")] != 5.62680052817 ) | ( hex[,c(\"petal_wid\")] < 1.30396620892 ) | ( ( hex[,c(\"sepal_wid\")] >= 2.53344427886 )) ) on dataset <iris_test_numeric_missing_extra>")
                     filterHex <- hex[!( ( hex[,c("sepal_len")] != 5.62680052817 ) | ( hex[,c("petal_wid")] < 1.30396620892 ) | ( ( hex[,c("sepal_wid")] >= 2.53344427886 )) ),]
            Log.info("Performing compound task !( ( hex[,c(\"species\")] != 1.22382127284 ) | ( hex[,c(\"sepal_wid\")] < 2.20836669878 ) | ( ( hex[,c(\"petal_len\")] >= 3.61107457347 )) ) on dataset iris_test_numeric_missing_extra, and also subsetting columns.")
                     filterHex <- hex[!( ( hex[,c("species")] != 1.22382127284 ) | ( hex[,c("sepal_wid")] < 2.20836669878 ) | ( ( hex[,c("petal_len")] >= 3.61107457347 )) ), c("petal_wid","sepal_wid","petal_len","sepal_len","species")]
                Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[!( ( hex[,c("species")] != 1.22382127284 ) | ( hex[,c("sepal_wid")] < 2.20836669878 ) | ( ( hex[,c("petal_len")] >= 3.61107457347 )) ), c(1)]
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("compoundFilterTest_ on data iris_test_numeric_missing_extra", complexFilterTest_iris_test_numeric_missing_extra_182(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
