            ##
            # Author: Autogenerated on 2013-11-27 17:26:17
            # gitHash: a4fe16d99eb5f003dd7c7d0da17f29e1712eda0f
            # SEED: 8586424275721420395
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            complexFilterTest_dd_mon_yy_with_other_cols_161 <- function(conn) {
                Log.info("A munge-task R unit test on data <dd_mon_yy_with_other_cols> testing the functional unit <['!', '==', '&', '>', '|', '>=']> ")
                Log.info("Uploading dd_mon_yy_with_other_cols")
                hex <- h2o.uploadFile(conn, locate("../../smalldata/datetime/dd-mon-yy-with-other-cols.csv"), "rdd_mon_yy_with_other_cols.hex")
            Log.info("Performing compound task !( ( hex[,c(2)] == 1.35160520113e+12 ) & ( hex[,c(2)] > 1.3516334586e+12 ) | ( ( hex[,c(1)] >= 1464.37666785 )) ) on dataset <dd-mon-yy-with-other-cols>")
                     filterHex <- hex[!( ( hex[,c(2)] == 1.35160520113e+12 ) & ( hex[,c(2)] > 1.3516334586e+12 ) | ( ( hex[,c(1)] >= 1464.37666785 )) ),]
            Log.info("Performing compound task !( ( hex[,c(2)] == 1.35132959392e+12 ) & ( hex[,c(2)] > 1.3513931466e+12 ) | ( ( hex[,c(1)] >= 4768.29957244 )) ) on dataset dd-mon-yy-with-other-cols, and also subsetting columns.")
                     filterHex <- hex[!( ( hex[,c(2)] == 1.35132959392e+12 ) & ( hex[,c(2)] > 1.3513931466e+12 ) | ( ( hex[,c(1)] >= 4768.29957244 )) ), c(2)]
                Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[!( ( hex[,c(2)] == 1.35132959392e+12 ) & ( hex[,c(2)] > 1.3513931466e+12 ) | ( ( hex[,c(1)] >= 4768.29957244 )) ), c(1)]
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("compoundFilterTest_ on data dd-mon-yy-with-other-cols", complexFilterTest_dd_mon_yy_with_other_cols_161(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
