            ##
            # Author: Autogenerated on 2013-11-27 17:26:17
            # gitHash: a4fe16d99eb5f003dd7c7d0da17f29e1712eda0f
            # SEED: 8586424275721420395
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            simpleFilterTest_hhp_107_01_94 <- function(conn) {
                Log.info("A munge-task R unit test on data <hhp_107_01> testing the functional unit <>=> ")
                Log.info("Uploading hhp_107_01")
                hex <- h2o.uploadFile(conn, locate("../../smalldata/hhp_107_01.data.gz"), "rhhp_107_01.hex")
                Log.info("Filtering out rows by >= from dataset hhp_107_01 and column \"10\" using value 0.0141777796444")
                     filterHex <- hex[hex[,c(10)] >= 0.0141777796444,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"10" >= 0.0141777796444,]
                Log.info("Filtering out rows by >= from dataset hhp_107_01 and column \"15\" using value 32.4805026252")
                     filterHex <- hex[hex[,c(15)] >= 32.4805026252,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"15" >= 32.4805026252,]
                Log.info("Filtering out rows by >= from dataset hhp_107_01 and column \"98\" using value 9.07843242169")
                     filterHex <- hex[hex[,c(98)] >= 9.07843242169,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"98" >= 9.07843242169,]
                Log.info("Filtering out rows by >= from dataset hhp_107_01 and column \"28\" using value 13.0028553581")
                     filterHex <- hex[hex[,c(28)] >= 13.0028553581,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"28" >= 13.0028553581,]
                Log.info("Filtering out rows by >= from dataset hhp_107_01 and column \"82\" using value 6.94131844337")
                     filterHex <- hex[hex[,c(82)] >= 6.94131844337,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"82" >= 6.94131844337,]
                Log.info("Filtering out rows by >= from dataset hhp_107_01 and column \"55\" using value 19.4772914675")
                     filterHex <- hex[hex[,c(55)] >= 19.4772914675,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"55" >= 19.4772914675,]
                Log.info("Filtering out rows by >= from dataset hhp_107_01 and column \"0\" using value 0.375865659601")
                     filterHex <- hex[hex[,c(1)] >= 0.375865659601,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"0" >= 0.375865659601,]
                Log.info("Filtering out rows by >= from dataset hhp_107_01 and column \"95\" using value 22.9847094855")
                     filterHex <- hex[hex[,c(95)] >= 22.9847094855,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"95" >= 22.9847094855,]
                Log.info("Filtering out rows by >= from dataset hhp_107_01 and column \"12\" using value 0.0")
                     filterHex <- hex[hex[,c(12)] >= 0.0,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"12" >= 0.0,]
                Log.info("Filtering out rows by >= from dataset hhp_107_01 and column \"47\" using value 35.212635411")
                     filterHex <- hex[hex[,c(47)] >= 35.212635411,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"47" >= 35.212635411,]
                Log.info("Filtering out rows by >= from dataset hhp_107_01 and column \"25\" using value 0.0")
                     filterHex <- hex[hex[,c(25)] >= 0.0,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"25" >= 0.0,]
                Log.info("Filtering out rows by >= from dataset hhp_107_01 and column \"64\" using value 17.6490748763")
                     filterHex <- hex[hex[,c(64)] >= 17.6490748763,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"64" >= 17.6490748763,]
                Log.info("Filtering out rows by >= from dataset hhp_107_01 and column \"52\" using value 3.95141129778")
                     filterHex <- hex[hex[,c(52)] >= 3.95141129778,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"52" >= 3.95141129778,]
                Log.info("Filtering out rows by >= from dataset hhp_107_01 and column \"93\" using value 2.96707613537")
                     filterHex <- hex[hex[,c(93)] >= 2.96707613537,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"93" >= 2.96707613537,]
                Log.info("Filtering out rows by >= from dataset hhp_107_01 and column \"106\" using value 0.17537207736")
                     filterHex <- hex[hex[,c(106)] >= 0.17537207736,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"106" >= 0.17537207736,]
                Log.info("Filtering out rows by >= from dataset hhp_107_01 and column \"2\" using value 0.0172460170147")
                     filterHex <- hex[hex[,c(2)] >= 0.0172460170147,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"2" >= 0.0172460170147,]
                Log.info("Filtering out rows by >= from dataset hhp_107_01 and column \"81\" using value 18.8686622677")
                     filterHex <- hex[hex[,c(81)] >= 18.8686622677,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"81" >= 18.8686622677,]
                    Log.info("Filtering out rows by >= from dataset hhp_107_01 and column \"96\" using value 14.3956617805, and also subsetting columns.")
                     filterHex <- hex[hex[,c(96)] >= 14.3956617805, c(96)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(96)] >= 14.3956617805, c(24,25,26,27,20,21,22,23,28,29,4,8,59,58,55,54,57,56,51,50,53,52,88,89,82,83,80,81,86,87,84,85,3,7,102,103,100,101,106,104,105,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,48,49,46,47,44,45,42,43,40,41,1,5,9,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by >= from dataset hhp_107_01 and column \"39\" using value 7.80744141472, and also subsetting columns.")
                     filterHex <- hex[hex[,c(39)] >= 7.80744141472, c(39)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(39)] >= 7.80744141472, c(24,25,26,27,20,21,22,23,28,29,4,8,59,58,55,54,57,56,51,50,53,52,88,89,82,83,80,81,86,87,84,85,3,7,102,103,100,101,106,104,105,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,48,49,46,47,44,45,42,43,40,41,1,5,9,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by >= from dataset hhp_107_01 and column \"42\" using value 25.253004837, and also subsetting columns.")
                     filterHex <- hex[hex[,c(42)] >= 25.253004837, c(42)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(42)] >= 25.253004837, c(24,25,26,27,20,21,22,23,28,29,4,8,59,58,55,54,57,56,51,50,53,52,88,89,82,83,80,81,86,87,84,85,3,7,102,103,100,101,106,104,105,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,48,49,46,47,44,45,42,43,40,41,1,5,9,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by >= from dataset hhp_107_01 and column \"83\" using value 2.39220140748, and also subsetting columns.")
                     filterHex <- hex[hex[,c(83)] >= 2.39220140748, c(83)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(83)] >= 2.39220140748, c(24,25,26,27,20,21,22,23,28,29,4,8,59,58,55,54,57,56,51,50,53,52,88,89,82,83,80,81,86,87,84,85,3,7,102,103,100,101,106,104,105,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,48,49,46,47,44,45,42,43,40,41,1,5,9,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by >= from dataset hhp_107_01 and column \"51\" using value 18.7044042556, and also subsetting columns.")
                     filterHex <- hex[hex[,c(51)] >= 18.7044042556, c(51)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(51)] >= 18.7044042556, c(24,25,26,27,20,21,22,23,28,29,4,8,59,58,55,54,57,56,51,50,53,52,88,89,82,83,80,81,86,87,84,85,3,7,102,103,100,101,106,104,105,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,48,49,46,47,44,45,42,43,40,41,1,5,9,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by >= from dataset hhp_107_01 and column \"82\" using value 14.672343635, and also subsetting columns.")
                     filterHex <- hex[hex[,c(82)] >= 14.672343635, c(82)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(82)] >= 14.672343635, c(24,25,26,27,20,21,22,23,28,29,4,8,59,58,55,54,57,56,51,50,53,52,88,89,82,83,80,81,86,87,84,85,3,7,102,103,100,101,106,104,105,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,48,49,46,47,44,45,42,43,40,41,1,5,9,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by >= from dataset hhp_107_01 and column \"59\" using value 14.0745950831, and also subsetting columns.")
                     filterHex <- hex[hex[,c(59)] >= 14.0745950831, c(59)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(59)] >= 14.0745950831, c(24,25,26,27,20,21,22,23,28,29,4,8,59,58,55,54,57,56,51,50,53,52,88,89,82,83,80,81,86,87,84,85,3,7,102,103,100,101,106,104,105,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,48,49,46,47,44,45,42,43,40,41,1,5,9,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by >= from dataset hhp_107_01 and column \"81\" using value 18.0673119084, and also subsetting columns.")
                     filterHex <- hex[hex[,c(81)] >= 18.0673119084, c(81)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(81)] >= 18.0673119084, c(24,25,26,27,20,21,22,23,28,29,4,8,59,58,55,54,57,56,51,50,53,52,88,89,82,83,80,81,86,87,84,85,3,7,102,103,100,101,106,104,105,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,48,49,46,47,44,45,42,43,40,41,1,5,9,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by >= from dataset hhp_107_01 and column \"37\" using value 19.2431967089, and also subsetting columns.")
                     filterHex <- hex[hex[,c(37)] >= 19.2431967089, c(37)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(37)] >= 19.2431967089, c(24,25,26,27,20,21,22,23,28,29,4,8,59,58,55,54,57,56,51,50,53,52,88,89,82,83,80,81,86,87,84,85,3,7,102,103,100,101,106,104,105,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,48,49,46,47,44,45,42,43,40,41,1,5,9,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by >= from dataset hhp_107_01 and column \"106\" using value 0.42629322766, and also subsetting columns.")
                     filterHex <- hex[hex[,c(106)] >= 0.42629322766, c(106)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(106)] >= 0.42629322766, c(24,25,26,27,20,21,22,23,28,29,4,8,59,58,55,54,57,56,51,50,53,52,88,89,82,83,80,81,86,87,84,85,3,7,102,103,100,101,106,104,105,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,48,49,46,47,44,45,42,43,40,41,1,5,9,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by >= from dataset hhp_107_01 and column \"57\" using value 0.181787450992, and also subsetting columns.")
                     filterHex <- hex[hex[,c(57)] >= 0.181787450992, c(57)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(57)] >= 0.181787450992, c(24,25,26,27,20,21,22,23,28,29,4,8,59,58,55,54,57,56,51,50,53,52,88,89,82,83,80,81,86,87,84,85,3,7,102,103,100,101,106,104,105,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,48,49,46,47,44,45,42,43,40,41,1,5,9,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by >= from dataset hhp_107_01 and column \"9\" using value 0.0, and also subsetting columns.")
                     filterHex <- hex[hex[,c(9)] >= 0.0, c(9)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(9)] >= 0.0, c(24,25,26,27,20,21,22,23,28,29,4,8,59,58,55,54,57,56,51,50,53,52,88,89,82,83,80,81,86,87,84,85,3,7,102,103,100,101,106,104,105,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,48,49,46,47,44,45,42,43,40,41,1,5,9,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by >= from dataset hhp_107_01 and column \"61\" using value 18.8105631575, and also subsetting columns.")
                     filterHex <- hex[hex[,c(61)] >= 18.8105631575, c(61)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(61)] >= 18.8105631575, c(24,25,26,27,20,21,22,23,28,29,4,8,59,58,55,54,57,56,51,50,53,52,88,89,82,83,80,81,86,87,84,85,3,7,102,103,100,101,106,104,105,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,48,49,46,47,44,45,42,43,40,41,1,5,9,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by >= from dataset hhp_107_01 and column \"104\" using value 77.3803340003, and also subsetting columns.")
                     filterHex <- hex[hex[,c(104)] >= 77.3803340003, c(104)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(104)] >= 77.3803340003, c(24,25,26,27,20,21,22,23,28,29,4,8,59,58,55,54,57,56,51,50,53,52,88,89,82,83,80,81,86,87,84,85,3,7,102,103,100,101,106,104,105,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,48,49,46,47,44,45,42,43,40,41,1,5,9,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by >= from dataset hhp_107_01 and column \"85\" using value 9.77295103169, and also subsetting columns.")
                     filterHex <- hex[hex[,c(85)] >= 9.77295103169, c(85)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(85)] >= 9.77295103169, c(24,25,26,27,20,21,22,23,28,29,4,8,59,58,55,54,57,56,51,50,53,52,88,89,82,83,80,81,86,87,84,85,3,7,102,103,100,101,106,104,105,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,48,49,46,47,44,45,42,43,40,41,1,5,9,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by >= from dataset hhp_107_01 and column \"44\" using value 32.7959229975, and also subsetting columns.")
                     filterHex <- hex[hex[,c(44)] >= 32.7959229975, c(44)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(44)] >= 32.7959229975, c(24,25,26,27,20,21,22,23,28,29,4,8,59,58,55,54,57,56,51,50,53,52,88,89,82,83,80,81,86,87,84,85,3,7,102,103,100,101,106,104,105,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,48,49,46,47,44,45,42,43,40,41,1,5,9,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by >= from dataset hhp_107_01 and column \"51\" using value 9.04127526652, and also subsetting columns.")
                     filterHex <- hex[hex[,c(51)] >= 9.04127526652, c(51)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(51)] >= 9.04127526652, c(24,25,26,27,20,21,22,23,28,29,4,8,59,58,55,54,57,56,51,50,53,52,88,89,82,83,80,81,86,87,84,85,3,7,102,103,100,101,106,104,105,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,48,49,46,47,44,45,42,43,40,41,1,5,9,77,76,75,74,73,72,71,70,79,78)]
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("simpleFilterTest_ on data hhp_107_01", simpleFilterTest_hhp_107_01_94(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
