            ##
            # Author: Autogenerated on 2013-11-27 17:26:17
            # gitHash: a4fe16d99eb5f003dd7c7d0da17f29e1712eda0f
            # SEED: 8586424275721420395
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            complexFilterTest_badchars_151 <- function(conn) {
                Log.info("A munge-task R unit test on data <badchars> testing the functional unit <['!', '!=']> ")
                Log.info("Uploading badchars")
                hex <- h2o.uploadFile(conn, locate("../../smalldata/badchars.csv"), "rbadchars.hex")
            Log.info("Performing compound task !( ( ( hex[,c(20)] != 0.0 )) ) on dataset <badchars>")
                     filterHex <- hex[!( ( ( hex[,c(20)] != 0.0 )) ),]
            Log.info("Performing compound task !( ( ( hex[,c(23)] != 0.647598472364 )) ) on dataset badchars, and also subsetting columns.")
                     filterHex <- hex[!( ( ( hex[,c(23)] != 0.647598472364 )) ), c(42,43,53,24,25,26,27,20,21,48,23,46,47,44,45,28,29,40,41,1,2,5,4,7,6,8,49,38,11,10,13,12,15,17,16,33,18,31,30,51,50,35,19,32)]
                Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[!( ( ( hex[,c(23)] != 0.647598472364 )) ), c(39,14,22,54,37,36,34,3,9,52)]
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("compoundFilterTest_ on data badchars", complexFilterTest_badchars_151(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
