            ##
            # Author: Autogenerated on 2013-11-27 03:20:00
            # gitHash: 25eb0cfd1269362ae85d0f073d9abde2a68ac0e4
            # SEED: 4617575514352894151
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            sliceTest_chess_test_7 <- function(conn) {
                Log.info("A munge-task R unit test on data <chess_test> testing the functional unit <[> ")
                Log.info("Uploading chess_test")
                hex <- h2o.uploadFile(conn, "../../smalldata/test/classifier/chess_test.csv", "rchess_test.hex")
                Log.info("Performing a column slice of chess_test using these columns: c(1)")
                slicedHex <- hex[,c(1)]
                    Log.info("Performing a row & column slice of chess_test using these rows & columns: c(1) & c(1)")
                slicedHex <- hex[c(1),c(1)]
                    Log.info("Performing a 1-by-1 column slice of chess_test using these columns: ")
                    Log.info("Performing a 1-by-1 row slice of chess_test using these rows: ")
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("sliceTest_ on data chess_test", sliceTest_chess_test_7(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
