            ##
            # Author: Autogenerated on 2013-11-27 03:20:00
            # gitHash: 25eb0cfd1269362ae85d0f073d9abde2a68ac0e4
            # SEED: 4617575514352894151
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            simpleFilterTest_nhanes3_80 <- function(conn) {
                Log.info("A munge-task R unit test on data <nhanes3> testing the functional unit <>=> ")
                Log.info("Uploading nhanes3")
                hex <- h2o.uploadFile(conn, "../../smalldata/logreg/umass_statdata/nhanes3.dat", "rnhanes3.hex")
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("simpleFilterTest_ on data nhanes3", simpleFilterTest_nhanes3_80(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
