            ##
            # Author: Autogenerated on 2013-11-27 03:20:00
            # gitHash: 25eb0cfd1269362ae85d0f073d9abde2a68ac0e4
            # SEED: 4617575514352894151
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            simpleFilterTest_chdage_84 <- function(conn) {
                Log.info("A munge-task R unit test on data <chdage> testing the functional unit <>=> ")
                Log.info("Uploading chdage")
                hex <- h2o.uploadFile(conn, "../../smalldata/logreg/umass_statdata/chdage.dat", "rchdage.hex")
                Log.info("Filtering out rows by >= from dataset chdage and column \"ID\" using value 28.5508857915")
                     filterHex <- hex[hex[,c("ID")] >= 28.5508857915,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"ID" >= 28.5508857915,]
                    Log.info("Filtering out rows by >= from dataset chdage and column \"AGE\" using value 57.7517418123, and also subsetting columns.")
                     filterHex <- hex[hex[,c("AGE")] >= 57.7517418123, c("AGE")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("AGE")] >= 57.7517418123, c("CHD","ID","AGE")]
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("simpleFilterTest_ on data chdage", simpleFilterTest_chdage_84(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
