            ##
            # Author: Autogenerated on 2013-11-27 17:26:17
            # gitHash: a4fe16d99eb5f003dd7c7d0da17f29e1712eda0f
            # SEED: 8586424275721420395
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            sliceTest_baddata_1 <- function(conn) {
                Log.info("A munge-task R unit test on data <baddata> testing the functional unit <[> ")
                Log.info("Uploading baddata")
                hex <- h2o.uploadFile(conn, locate("../../smalldata/baddata.data"), "rbaddata.hex")
                Log.info("Performing a column slice of baddata using these columns: c(1)")
                slicedHex <- hex[,c(1)]
                    Log.info("Performing a row slice of baddata using these rows: c(1,2)")
                slicedHex <- hex[c(1,2),]
                    Log.info("Performing a row & column slice of baddata using these rows & columns: c(1) & c(3)")
                slicedHex <- hex[c(3),c(1)]
                    Log.info("Performing a 1-by-1 column slice of baddata using these columns: ")
                    Log.info("Performing a 1-by-1 row slice of baddata using these rows: ")
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("sliceTest_ on data baddata", sliceTest_baddata_1(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
