            ##
            # Author: Autogenerated on 2013-11-27 18:13:58
            # gitHash: c4ad841105ba82f4a3979e4cf1ae7e20a5905e59
            # SEED: 4663640625336856642
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            simpleFilterTest_test_59 <- function(conn) {
                Log.info("A munge-task R unit test on data <test> testing the functional unit <<=> ")
                Log.info("Uploading test")
                hex <- h2o.uploadFile(conn, locate("../../smalldata/chess/chess_2x2x1000/h2o/test.csv"), "rtest.hex")
                Log.info("Filtering out rows by <= from dataset test and column \"y\" using value 0.298121018694")
                     filterHex <- hex[hex[,c("y")] <= 0.298121018694,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"y" <= 0.298121018694,]
                Log.info("Filtering out rows by <= from dataset test and column \"x\" using value 0.533360696472")
                     filterHex <- hex[hex[,c("x")] <= 0.533360696472,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"x" <= 0.533360696472,]
                Log.info("Filtering out rows by <= from dataset test and column \"y\" using value 1.9666103677")
                     filterHex <- hex[hex[,c("y")] <= 1.9666103677,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"y" <= 1.9666103677,]
                Log.info("Filtering out rows by <= from dataset test and column \"x\" using value 0.561663062452")
                     filterHex <- hex[hex[,c("x")] <= 0.561663062452,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"x" <= 0.561663062452,]
                Log.info("Filtering out rows by <= from dataset test and column \"x\" using value 0.208296322185")
                     filterHex <- hex[hex[,c("x")] <= 0.208296322185,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"x" <= 0.208296322185,]
                    Log.info("Filtering out rows by <= from dataset test and column \"x\" using value 1.3679986205, and also subsetting columns.")
                     filterHex <- hex[hex[,c("x")] <= 1.3679986205, c("x")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("x")] <= 1.3679986205, c("color","x","y")]
                    Log.info("Filtering out rows by <= from dataset test and column \"x\" using value 1.22920702984, and also subsetting columns.")
                     filterHex <- hex[hex[,c("x")] <= 1.22920702984, c("x")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("x")] <= 1.22920702984, c("color","x","y")]
                    Log.info("Filtering out rows by <= from dataset test and column \"y\" using value 0.604747597295, and also subsetting columns.")
                     filterHex <- hex[hex[,c("y")] <= 0.604747597295, c("y")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("y")] <= 0.604747597295, c("color","x","y")]
                    Log.info("Filtering out rows by <= from dataset test and column \"x\" using value 1.41227093755, and also subsetting columns.")
                     filterHex <- hex[hex[,c("x")] <= 1.41227093755, c("x")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("x")] <= 1.41227093755, c("color","x","y")]
                    Log.info("Filtering out rows by <= from dataset test and column \"x\" using value 0.616537731023, and also subsetting columns.")
                     filterHex <- hex[hex[,c("x")] <= 0.616537731023, c("x")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("x")] <= 0.616537731023, c("color","x","y")]
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("simpleFilterTest_ on data test", simpleFilterTest_test_59(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
