            ##
            # Author: Autogenerated on 2013-11-27 18:13:58
            # gitHash: c4ad841105ba82f4a3979e4cf1ae7e20a5905e59
            # SEED: 4663640625336856642
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            simpleFilterTest_iris_test_29 <- function(conn) {
                Log.info("A munge-task R unit test on data <iris_test> testing the functional unit <<> ")
                Log.info("Uploading iris_test")
                hex <- h2o.uploadFile(conn, locate("../../smalldata/test/classifier/iris_test.csv"), "riris_test.hex")
                Log.info("Filtering out rows by < from dataset iris_test and column \"petal_len\" using value 2.60418553829")
                     filterHex <- hex[hex[,c("petal_len")] < 2.60418553829,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"petal_len" < 2.60418553829,]
                Log.info("Filtering out rows by < from dataset iris_test and column \"petal_wid\" using value 1.45260503223")
                     filterHex <- hex[hex[,c("petal_wid")] < 1.45260503223,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"petal_wid" < 1.45260503223,]
                Log.info("Filtering out rows by < from dataset iris_test and column \"sepal_wid\" using value 4.10998176592")
                     filterHex <- hex[hex[,c("sepal_wid")] < 4.10998176592,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"sepal_wid" < 4.10998176592,]
                Log.info("Filtering out rows by < from dataset iris_test and column \"sepal_len\" using value 5.8461945891")
                     filterHex <- hex[hex[,c("sepal_len")] < 5.8461945891,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"sepal_len" < 5.8461945891,]
                Log.info("Filtering out rows by < from dataset iris_test and column \"petal_len\" using value 3.22552456236")
                     filterHex <- hex[hex[,c("petal_len")] < 3.22552456236,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"petal_len" < 3.22552456236,]
                Log.info("Filtering out rows by < from dataset iris_test and column \"petal_len\" using value 2.70931722186")
                     filterHex <- hex[hex[,c("petal_len")] < 2.70931722186,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"petal_len" < 2.70931722186,]
                Log.info("Filtering out rows by < from dataset iris_test and column \"sepal_len\" using value 6.65850667201")
                     filterHex <- hex[hex[,c("sepal_len")] < 6.65850667201,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"sepal_len" < 6.65850667201,]
                Log.info("Filtering out rows by < from dataset iris_test and column \"petal_wid\" using value 1.86028943813")
                     filterHex <- hex[hex[,c("petal_wid")] < 1.86028943813,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"petal_wid" < 1.86028943813,]
                    Log.info("Filtering out rows by < from dataset iris_test and column \"petal_wid\" using value 0.143660948677, and also subsetting columns.")
                     filterHex <- hex[hex[,c("petal_wid")] < 0.143660948677, c("petal_wid")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("petal_wid")] < 0.143660948677, c("petal_wid","sepal_wid","petal_len","sepal_len","species")]
                    Log.info("Filtering out rows by < from dataset iris_test and column \"sepal_wid\" using value 3.26032888035, and also subsetting columns.")
                     filterHex <- hex[hex[,c("sepal_wid")] < 3.26032888035, c("sepal_wid")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("sepal_wid")] < 3.26032888035, c("petal_wid","sepal_wid","petal_len","sepal_len","species")]
                    Log.info("Filtering out rows by < from dataset iris_test and column \"sepal_wid\" using value 2.77446753993, and also subsetting columns.")
                     filterHex <- hex[hex[,c("sepal_wid")] < 2.77446753993, c("sepal_wid")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("sepal_wid")] < 2.77446753993, c("petal_wid","sepal_wid","petal_len","sepal_len","species")]
                    Log.info("Filtering out rows by < from dataset iris_test and column \"sepal_len\" using value 7.64140565843, and also subsetting columns.")
                     filterHex <- hex[hex[,c("sepal_len")] < 7.64140565843, c("sepal_len")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("sepal_len")] < 7.64140565843, c("petal_wid","sepal_wid","petal_len","sepal_len","species")]
                    Log.info("Filtering out rows by < from dataset iris_test and column \"sepal_wid\" using value 3.03160584795, and also subsetting columns.")
                     filterHex <- hex[hex[,c("sepal_wid")] < 3.03160584795, c("sepal_wid")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("sepal_wid")] < 3.03160584795, c("petal_wid","sepal_wid","petal_len","sepal_len","species")]
                    Log.info("Filtering out rows by < from dataset iris_test and column \"sepal_wid\" using value 4.38789450275, and also subsetting columns.")
                     filterHex <- hex[hex[,c("sepal_wid")] < 4.38789450275, c("sepal_wid")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("sepal_wid")] < 4.38789450275, c("petal_wid","sepal_wid","petal_len","sepal_len","species")]
                    Log.info("Filtering out rows by < from dataset iris_test and column \"sepal_len\" using value 4.78324379877, and also subsetting columns.")
                     filterHex <- hex[hex[,c("sepal_len")] < 4.78324379877, c("sepal_len")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("sepal_len")] < 4.78324379877, c("petal_wid","sepal_wid","petal_len","sepal_len","species")]
                    Log.info("Filtering out rows by < from dataset iris_test and column \"sepal_wid\" using value 2.63941249459, and also subsetting columns.")
                     filterHex <- hex[hex[,c("sepal_wid")] < 2.63941249459, c("sepal_wid")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("sepal_wid")] < 2.63941249459, c("petal_wid","sepal_wid","petal_len","sepal_len","species")]
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("simpleFilterTest_ on data iris_test", simpleFilterTest_iris_test_29(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
