            ##
            # Author: Autogenerated on 2013-11-27 17:26:17
            # gitHash: a4fe16d99eb5f003dd7c7d0da17f29e1712eda0f
            # SEED: 8586424275721420395
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            sliceTest_poker_hand_testing_8 <- function(conn) {
                Log.info("A munge-task R unit test on data <poker_hand_testing> testing the functional unit <[> ")
                Log.info("Uploading poker_hand_testing")
                hex <- h2o.uploadFile(conn, locate("../../smalldata/poker/poker-hand-testing.data"), "rpoker_hand_testing.hex")
                Log.info("Performing a column slice of poker-hand-testing using these columns: c(1,2)")
                slicedHex <- hex[,c(1,2)]
                    Log.info("Performing a 1-by-1 column slice of poker-hand-testing using these columns: ")
                    Log.info("Performing a 1-by-1 row slice of poker-hand-testing using these rows: ")
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("sliceTest_ on data poker-hand-testing", sliceTest_poker_hand_testing_8(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
