            ##
            # Author: Autogenerated on 2013-11-27 18:13:58
            # gitHash: c4ad841105ba82f4a3979e4cf1ae7e20a5905e59
            # SEED: 4663640625336856642
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            simpleFilterTest_syn_binary10Kx100_47 <- function(conn) {
                Log.info("A munge-task R unit test on data <syn_binary10Kx100> testing the functional unit <<=> ")
                Log.info("Uploading syn_binary10Kx100")
                hex <- h2o.uploadFile(conn, locate("../../smalldata/syn_binary10Kx100.csv.gz"), "rsyn_binary10Kx100.hex")
                Log.info("Filtering out rows by <= from dataset syn_binary10Kx100 and column \"100\" using value 0.826471736312")
                     filterHex <- hex[hex[,c(100)] <= 0.826471736312,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"100" <= 0.826471736312,]
                Log.info("Filtering out rows by <= from dataset syn_binary10Kx100 and column \"100\" using value 0.610860899995")
                     filterHex <- hex[hex[,c(100)] <= 0.610860899995,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"100" <= 0.610860899995,]
                Log.info("Filtering out rows by <= from dataset syn_binary10Kx100 and column \"100\" using value 0.191027299367")
                     filterHex <- hex[hex[,c(100)] <= 0.191027299367,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"100" <= 0.191027299367,]
                Log.info("Filtering out rows by <= from dataset syn_binary10Kx100 and column \"100\" using value 0.868058030109")
                     filterHex <- hex[hex[,c(100)] <= 0.868058030109,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"100" <= 0.868058030109,]
                Log.info("Filtering out rows by <= from dataset syn_binary10Kx100 and column \"100\" using value 0.104038374402")
                     filterHex <- hex[hex[,c(100)] <= 0.104038374402,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"100" <= 0.104038374402,]
                Log.info("Filtering out rows by <= from dataset syn_binary10Kx100 and column \"100\" using value 0.850333879622")
                     filterHex <- hex[hex[,c(100)] <= 0.850333879622,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"100" <= 0.850333879622,]
                Log.info("Filtering out rows by <= from dataset syn_binary10Kx100 and column \"100\" using value 0.635071462909")
                     filterHex <- hex[hex[,c(100)] <= 0.635071462909,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"100" <= 0.635071462909,]
                Log.info("Filtering out rows by <= from dataset syn_binary10Kx100 and column \"100\" using value 0.361861730229")
                     filterHex <- hex[hex[,c(100)] <= 0.361861730229,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"100" <= 0.361861730229,]
                Log.info("Filtering out rows by <= from dataset syn_binary10Kx100 and column \"100\" using value 0.595925922465")
                     filterHex <- hex[hex[,c(100)] <= 0.595925922465,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"100" <= 0.595925922465,]
                Log.info("Filtering out rows by <= from dataset syn_binary10Kx100 and column \"100\" using value 0.159208197942")
                     filterHex <- hex[hex[,c(100)] <= 0.159208197942,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"100" <= 0.159208197942,]
                Log.info("Filtering out rows by <= from dataset syn_binary10Kx100 and column \"100\" using value 0.717626550229")
                     filterHex <- hex[hex[,c(100)] <= 0.717626550229,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"100" <= 0.717626550229,]
                Log.info("Filtering out rows by <= from dataset syn_binary10Kx100 and column \"100\" using value 0.741045318515")
                     filterHex <- hex[hex[,c(100)] <= 0.741045318515,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"100" <= 0.741045318515,]
                Log.info("Filtering out rows by <= from dataset syn_binary10Kx100 and column \"100\" using value 0.986277363842")
                     filterHex <- hex[hex[,c(100)] <= 0.986277363842,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"100" <= 0.986277363842,]
                Log.info("Filtering out rows by <= from dataset syn_binary10Kx100 and column \"100\" using value 0.866652402391")
                     filterHex <- hex[hex[,c(100)] <= 0.866652402391,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"100" <= 0.866652402391,]
                Log.info("Filtering out rows by <= from dataset syn_binary10Kx100 and column \"100\" using value 0.875767044959")
                     filterHex <- hex[hex[,c(100)] <= 0.875767044959,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"100" <= 0.875767044959,]
                Log.info("Filtering out rows by <= from dataset syn_binary10Kx100 and column \"100\" using value 0.574150044168")
                     filterHex <- hex[hex[,c(100)] <= 0.574150044168,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"100" <= 0.574150044168,]
                Log.info("Filtering out rows by <= from dataset syn_binary10Kx100 and column \"100\" using value 0.784037680674")
                     filterHex <- hex[hex[,c(100)] <= 0.784037680674,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"100" <= 0.784037680674,]
                Log.info("Filtering out rows by <= from dataset syn_binary10Kx100 and column \"100\" using value 0.792520899497")
                     filterHex <- hex[hex[,c(100)] <= 0.792520899497,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"100" <= 0.792520899497,]
                Log.info("Filtering out rows by <= from dataset syn_binary10Kx100 and column \"100\" using value 0.646607138171")
                     filterHex <- hex[hex[,c(100)] <= 0.646607138171,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"100" <= 0.646607138171,]
                Log.info("Filtering out rows by <= from dataset syn_binary10Kx100 and column \"100\" using value 0.325546552706")
                     filterHex <- hex[hex[,c(100)] <= 0.325546552706,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"100" <= 0.325546552706,]
                Log.info("Filtering out rows by <= from dataset syn_binary10Kx100 and column \"100\" using value 0.622444005235")
                     filterHex <- hex[hex[,c(100)] <= 0.622444005235,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"100" <= 0.622444005235,]
                Log.info("Filtering out rows by <= from dataset syn_binary10Kx100 and column \"100\" using value 0.501657107919")
                     filterHex <- hex[hex[,c(100)] <= 0.501657107919,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"100" <= 0.501657107919,]
                Log.info("Filtering out rows by <= from dataset syn_binary10Kx100 and column \"100\" using value 0.636269952455")
                     filterHex <- hex[hex[,c(100)] <= 0.636269952455,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"100" <= 0.636269952455,]
                Log.info("Filtering out rows by <= from dataset syn_binary10Kx100 and column \"100\" using value 0.564121599419")
                     filterHex <- hex[hex[,c(100)] <= 0.564121599419,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"100" <= 0.564121599419,]
                Log.info("Filtering out rows by <= from dataset syn_binary10Kx100 and column \"100\" using value 0.315883032027")
                     filterHex <- hex[hex[,c(100)] <= 0.315883032027,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"100" <= 0.315883032027,]
                Log.info("Filtering out rows by <= from dataset syn_binary10Kx100 and column \"100\" using value 0.0795827704051")
                     filterHex <- hex[hex[,c(100)] <= 0.0795827704051,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"100" <= 0.0795827704051,]
                    Log.info("Filtering out rows by <= from dataset syn_binary10Kx100 and column \"100\" using value 0.897184969235, and also subsetting columns.")
                     filterHex <- hex[hex[,c(100)] <= 0.897184969235, c(100)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(100)] <= 0.897184969235, c(24,25,26,27,20,21,22,23,28,29,4,8,59,58,55,54,57,56,51,50,53,52,88,89,82,83,80,81,86,87,84,85,3,7,100,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,48,49,46,47,44,45,42,43,40,41,1,5,9,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by <= from dataset syn_binary10Kx100 and column \"100\" using value 0.288917752598, and also subsetting columns.")
                     filterHex <- hex[hex[,c(100)] <= 0.288917752598, c(100)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(100)] <= 0.288917752598, c(24,25,26,27,20,21,22,23,28,29,4,8,59,58,55,54,57,56,51,50,53,52,88,89,82,83,80,81,86,87,84,85,3,7,100,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,48,49,46,47,44,45,42,43,40,41,1,5,9,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by <= from dataset syn_binary10Kx100 and column \"100\" using value 0.764123283284, and also subsetting columns.")
                     filterHex <- hex[hex[,c(100)] <= 0.764123283284, c(100)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(100)] <= 0.764123283284, c(24,25,26,27,20,21,22,23,28,29,4,8,59,58,55,54,57,56,51,50,53,52,88,89,82,83,80,81,86,87,84,85,3,7,100,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,48,49,46,47,44,45,42,43,40,41,1,5,9,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by <= from dataset syn_binary10Kx100 and column \"100\" using value 0.202468819456, and also subsetting columns.")
                     filterHex <- hex[hex[,c(100)] <= 0.202468819456, c(100)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(100)] <= 0.202468819456, c(24,25,26,27,20,21,22,23,28,29,4,8,59,58,55,54,57,56,51,50,53,52,88,89,82,83,80,81,86,87,84,85,3,7,100,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,48,49,46,47,44,45,42,43,40,41,1,5,9,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by <= from dataset syn_binary10Kx100 and column \"100\" using value 0.158120991868, and also subsetting columns.")
                     filterHex <- hex[hex[,c(100)] <= 0.158120991868, c(100)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(100)] <= 0.158120991868, c(24,25,26,27,20,21,22,23,28,29,4,8,59,58,55,54,57,56,51,50,53,52,88,89,82,83,80,81,86,87,84,85,3,7,100,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,48,49,46,47,44,45,42,43,40,41,1,5,9,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by <= from dataset syn_binary10Kx100 and column \"100\" using value 0.711043069716, and also subsetting columns.")
                     filterHex <- hex[hex[,c(100)] <= 0.711043069716, c(100)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(100)] <= 0.711043069716, c(24,25,26,27,20,21,22,23,28,29,4,8,59,58,55,54,57,56,51,50,53,52,88,89,82,83,80,81,86,87,84,85,3,7,100,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,48,49,46,47,44,45,42,43,40,41,1,5,9,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by <= from dataset syn_binary10Kx100 and column \"100\" using value 0.837850794166, and also subsetting columns.")
                     filterHex <- hex[hex[,c(100)] <= 0.837850794166, c(100)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(100)] <= 0.837850794166, c(24,25,26,27,20,21,22,23,28,29,4,8,59,58,55,54,57,56,51,50,53,52,88,89,82,83,80,81,86,87,84,85,3,7,100,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,48,49,46,47,44,45,42,43,40,41,1,5,9,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by <= from dataset syn_binary10Kx100 and column \"100\" using value 0.321576586651, and also subsetting columns.")
                     filterHex <- hex[hex[,c(100)] <= 0.321576586651, c(100)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(100)] <= 0.321576586651, c(24,25,26,27,20,21,22,23,28,29,4,8,59,58,55,54,57,56,51,50,53,52,88,89,82,83,80,81,86,87,84,85,3,7,100,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,48,49,46,47,44,45,42,43,40,41,1,5,9,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by <= from dataset syn_binary10Kx100 and column \"100\" using value 0.43077860298, and also subsetting columns.")
                     filterHex <- hex[hex[,c(100)] <= 0.43077860298, c(100)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(100)] <= 0.43077860298, c(24,25,26,27,20,21,22,23,28,29,4,8,59,58,55,54,57,56,51,50,53,52,88,89,82,83,80,81,86,87,84,85,3,7,100,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,48,49,46,47,44,45,42,43,40,41,1,5,9,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by <= from dataset syn_binary10Kx100 and column \"100\" using value 0.450808985376, and also subsetting columns.")
                     filterHex <- hex[hex[,c(100)] <= 0.450808985376, c(100)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(100)] <= 0.450808985376, c(24,25,26,27,20,21,22,23,28,29,4,8,59,58,55,54,57,56,51,50,53,52,88,89,82,83,80,81,86,87,84,85,3,7,100,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,48,49,46,47,44,45,42,43,40,41,1,5,9,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by <= from dataset syn_binary10Kx100 and column \"100\" using value 0.583840337852, and also subsetting columns.")
                     filterHex <- hex[hex[,c(100)] <= 0.583840337852, c(100)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(100)] <= 0.583840337852, c(24,25,26,27,20,21,22,23,28,29,4,8,59,58,55,54,57,56,51,50,53,52,88,89,82,83,80,81,86,87,84,85,3,7,100,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,48,49,46,47,44,45,42,43,40,41,1,5,9,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by <= from dataset syn_binary10Kx100 and column \"100\" using value 0.0394854639929, and also subsetting columns.")
                     filterHex <- hex[hex[,c(100)] <= 0.0394854639929, c(100)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(100)] <= 0.0394854639929, c(24,25,26,27,20,21,22,23,28,29,4,8,59,58,55,54,57,56,51,50,53,52,88,89,82,83,80,81,86,87,84,85,3,7,100,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,48,49,46,47,44,45,42,43,40,41,1,5,9,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by <= from dataset syn_binary10Kx100 and column \"100\" using value 0.548701097988, and also subsetting columns.")
                     filterHex <- hex[hex[,c(100)] <= 0.548701097988, c(100)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(100)] <= 0.548701097988, c(24,25,26,27,20,21,22,23,28,29,4,8,59,58,55,54,57,56,51,50,53,52,88,89,82,83,80,81,86,87,84,85,3,7,100,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,48,49,46,47,44,45,42,43,40,41,1,5,9,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by <= from dataset syn_binary10Kx100 and column \"100\" using value 0.713271470021, and also subsetting columns.")
                     filterHex <- hex[hex[,c(100)] <= 0.713271470021, c(100)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(100)] <= 0.713271470021, c(24,25,26,27,20,21,22,23,28,29,4,8,59,58,55,54,57,56,51,50,53,52,88,89,82,83,80,81,86,87,84,85,3,7,100,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,48,49,46,47,44,45,42,43,40,41,1,5,9,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by <= from dataset syn_binary10Kx100 and column \"100\" using value 0.937989154465, and also subsetting columns.")
                     filterHex <- hex[hex[,c(100)] <= 0.937989154465, c(100)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(100)] <= 0.937989154465, c(24,25,26,27,20,21,22,23,28,29,4,8,59,58,55,54,57,56,51,50,53,52,88,89,82,83,80,81,86,87,84,85,3,7,100,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,48,49,46,47,44,45,42,43,40,41,1,5,9,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by <= from dataset syn_binary10Kx100 and column \"100\" using value 0.969460956145, and also subsetting columns.")
                     filterHex <- hex[hex[,c(100)] <= 0.969460956145, c(100)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(100)] <= 0.969460956145, c(24,25,26,27,20,21,22,23,28,29,4,8,59,58,55,54,57,56,51,50,53,52,88,89,82,83,80,81,86,87,84,85,3,7,100,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,48,49,46,47,44,45,42,43,40,41,1,5,9,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by <= from dataset syn_binary10Kx100 and column \"100\" using value 0.114967171334, and also subsetting columns.")
                     filterHex <- hex[hex[,c(100)] <= 0.114967171334, c(100)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(100)] <= 0.114967171334, c(24,25,26,27,20,21,22,23,28,29,4,8,59,58,55,54,57,56,51,50,53,52,88,89,82,83,80,81,86,87,84,85,3,7,100,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,48,49,46,47,44,45,42,43,40,41,1,5,9,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by <= from dataset syn_binary10Kx100 and column \"100\" using value 0.271559118619, and also subsetting columns.")
                     filterHex <- hex[hex[,c(100)] <= 0.271559118619, c(100)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(100)] <= 0.271559118619, c(24,25,26,27,20,21,22,23,28,29,4,8,59,58,55,54,57,56,51,50,53,52,88,89,82,83,80,81,86,87,84,85,3,7,100,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,48,49,46,47,44,45,42,43,40,41,1,5,9,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by <= from dataset syn_binary10Kx100 and column \"100\" using value 0.770626084113, and also subsetting columns.")
                     filterHex <- hex[hex[,c(100)] <= 0.770626084113, c(100)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(100)] <= 0.770626084113, c(24,25,26,27,20,21,22,23,28,29,4,8,59,58,55,54,57,56,51,50,53,52,88,89,82,83,80,81,86,87,84,85,3,7,100,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,48,49,46,47,44,45,42,43,40,41,1,5,9,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by <= from dataset syn_binary10Kx100 and column \"100\" using value 0.357551200998, and also subsetting columns.")
                     filterHex <- hex[hex[,c(100)] <= 0.357551200998, c(100)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(100)] <= 0.357551200998, c(24,25,26,27,20,21,22,23,28,29,4,8,59,58,55,54,57,56,51,50,53,52,88,89,82,83,80,81,86,87,84,85,3,7,100,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,48,49,46,47,44,45,42,43,40,41,1,5,9,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by <= from dataset syn_binary10Kx100 and column \"100\" using value 0.489177850131, and also subsetting columns.")
                     filterHex <- hex[hex[,c(100)] <= 0.489177850131, c(100)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(100)] <= 0.489177850131, c(24,25,26,27,20,21,22,23,28,29,4,8,59,58,55,54,57,56,51,50,53,52,88,89,82,83,80,81,86,87,84,85,3,7,100,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,48,49,46,47,44,45,42,43,40,41,1,5,9,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by <= from dataset syn_binary10Kx100 and column \"100\" using value 0.216675323899, and also subsetting columns.")
                     filterHex <- hex[hex[,c(100)] <= 0.216675323899, c(100)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(100)] <= 0.216675323899, c(24,25,26,27,20,21,22,23,28,29,4,8,59,58,55,54,57,56,51,50,53,52,88,89,82,83,80,81,86,87,84,85,3,7,100,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,48,49,46,47,44,45,42,43,40,41,1,5,9,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by <= from dataset syn_binary10Kx100 and column \"100\" using value 0.841146678702, and also subsetting columns.")
                     filterHex <- hex[hex[,c(100)] <= 0.841146678702, c(100)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(100)] <= 0.841146678702, c(24,25,26,27,20,21,22,23,28,29,4,8,59,58,55,54,57,56,51,50,53,52,88,89,82,83,80,81,86,87,84,85,3,7,100,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,48,49,46,47,44,45,42,43,40,41,1,5,9,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by <= from dataset syn_binary10Kx100 and column \"100\" using value 0.648189962489, and also subsetting columns.")
                     filterHex <- hex[hex[,c(100)] <= 0.648189962489, c(100)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(100)] <= 0.648189962489, c(24,25,26,27,20,21,22,23,28,29,4,8,59,58,55,54,57,56,51,50,53,52,88,89,82,83,80,81,86,87,84,85,3,7,100,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,48,49,46,47,44,45,42,43,40,41,1,5,9,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by <= from dataset syn_binary10Kx100 and column \"100\" using value 0.0214687948626, and also subsetting columns.")
                     filterHex <- hex[hex[,c(100)] <= 0.0214687948626, c(100)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(100)] <= 0.0214687948626, c(24,25,26,27,20,21,22,23,28,29,4,8,59,58,55,54,57,56,51,50,53,52,88,89,82,83,80,81,86,87,84,85,3,7,100,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,48,49,46,47,44,45,42,43,40,41,1,5,9,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by <= from dataset syn_binary10Kx100 and column \"100\" using value 0.316010351265, and also subsetting columns.")
                     filterHex <- hex[hex[,c(100)] <= 0.316010351265, c(100)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(100)] <= 0.316010351265, c(24,25,26,27,20,21,22,23,28,29,4,8,59,58,55,54,57,56,51,50,53,52,88,89,82,83,80,81,86,87,84,85,3,7,100,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,48,49,46,47,44,45,42,43,40,41,1,5,9,77,76,75,74,73,72,71,70,79,78)]
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("simpleFilterTest_ on data syn_binary10Kx100", simpleFilterTest_syn_binary10Kx100_47(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
