            ##
            # Author: Autogenerated on 2013-11-29 01:20:07
            # gitHash: 10810480518d43dd720690e729d2f3b9a0f8eba7
            # SEED: 7977475956795433203
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            sliceTest_sumsigmoids_6 <- function(conn) {
                Log.info("A munge-task R unit test on data <sumsigmoids> testing the functional unit <[> ")
                Log.info("Uploading sumsigmoids")
                hex <- h2o.uploadFile(conn, locate("../../smalldata/neural/sumsigmoids.csv"), "rsumsigmoids.hex")
                    Log.info("Performing a row slice of sumsigmoids using these rows: c(24,25,26,27,20,21,22,23,28,29,4,8,59,58,55,54,57,56,51,50,53,52,88,89,82,83,80,81,86,87,84,85,3,7,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,6,91,90,93,92,11,10,13,12,15,14,17,16,19,18,48,49,46,47,44,45,42,43,40,41,1,5,9,77,76,75,74,73,72,71,70,79,78)")
                slicedHex <- hex[c(24,25,26,27,20,21,22,23,28,29,4,8,59,58,55,54,57,56,51,50,53,52,88,89,82,83,80,81,86,87,84,85,3,7,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,6,91,90,93,92,11,10,13,12,15,14,17,16,19,18,48,49,46,47,44,45,42,43,40,41,1,5,9,77,76,75,74,73,72,71,70,79,78),]
                    Log.info("Performing a row & column slice of sumsigmoids using these rows & columns: c(\"X.2\") & c(30,37,36,60,82,62,63,64,68,83,80,84,85,24,26,20,22,23,43,2,14,9,77,74,71,91,15,79,78,11,59,58,17,33,32,57,49,51,50,53,52,18,31)")
                slicedHex <- hex[c(30,37,36,60,82,62,63,64,68,83,80,84,85,24,26,20,22,23,43,2,14,9,77,74,71,91,15,79,78,11,59,58,17,33,32,57,49,51,50,53,52,18,31),c("X.2")]
                    Log.info("Performing a 1-by-1 column slice of sumsigmoids using these columns: ")
                    Log.info("Performing a 1-by-1 row slice of sumsigmoids using these rows: ")
            Log.inf("End of test")
            PASSS <<- TRUE
            }
            PASSS <- FALSE
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("sliceTest_ on data sumsigmoids", sliceTest_sumsigmoids_6(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            if (!PASSS) FAIL("Did not reach the end of test. Check Rsandbox/errors.log for warnings and errors.")
            PASS()
