            ##
            # Author: Autogenerated on 2013-11-27 18:13:58
            # gitHash: c4ad841105ba82f4a3979e4cf1ae7e20a5905e59
            # SEED: 4663640625336856642
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            simpleFilterTest_train_96 <- function(conn) {
                Log.info("A munge-task R unit test on data <train> testing the functional unit <>=> ")
                Log.info("Uploading train")
                hex <- h2o.uploadFile(conn, locate("../../smalldata/chess/chess_2x2x1000/weka/train.csv.arff"), "rtrain.hex")
                Log.info("Filtering out rows by >= from dataset train and column \"0\" using value 0.0320616734401")
                     filterHex <- hex[hex[,c(1)] >= 0.0320616734401,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"0" >= 0.0320616734401,]
                Log.info("Filtering out rows by >= from dataset train and column \"1\" using value 1.84588971974")
                     filterHex <- hex[hex[,c(1)] >= 1.84588971974,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"1" >= 1.84588971974,]
                Log.info("Filtering out rows by >= from dataset train and column \"0\" using value 1.8769217093")
                     filterHex <- hex[hex[,c(1)] >= 1.8769217093,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"0" >= 1.8769217093,]
                Log.info("Filtering out rows by >= from dataset train and column \"0\" using value 0.445092448832")
                     filterHex <- hex[hex[,c(1)] >= 0.445092448832,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"0" >= 0.445092448832,]
                Log.info("Filtering out rows by >= from dataset train and column \"0\" using value 1.82572175166")
                     filterHex <- hex[hex[,c(1)] >= 1.82572175166,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"0" >= 1.82572175166,]
                    Log.info("Filtering out rows by >= from dataset train and column \"0\" using value 1.14614765397, and also subsetting columns.")
                     filterHex <- hex[hex[,c(1)] >= 1.14614765397, c(1)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(1)] >= 1.14614765397, c(1,2)]
                    Log.info("Filtering out rows by >= from dataset train and column \"0\" using value 0.256621024195, and also subsetting columns.")
                     filterHex <- hex[hex[,c(1)] >= 0.256621024195, c(1)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(1)] >= 0.256621024195, c(1,2)]
                    Log.info("Filtering out rows by >= from dataset train and column \"1\" using value 1.5529428872, and also subsetting columns.")
                     filterHex <- hex[hex[,c(1)] >= 1.5529428872, c(1)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(1)] >= 1.5529428872, c(1,2)]
                    Log.info("Filtering out rows by >= from dataset train and column \"1\" using value 0.697508914065, and also subsetting columns.")
                     filterHex <- hex[hex[,c(1)] >= 0.697508914065, c(1)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(1)] >= 0.697508914065, c(1,2)]
                    Log.info("Filtering out rows by >= from dataset train and column \"1\" using value 0.0590898119148, and also subsetting columns.")
                     filterHex <- hex[hex[,c(1)] >= 0.0590898119148, c(1)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(1)] >= 0.0590898119148, c(1,2)]
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("simpleFilterTest_ on data train", simpleFilterTest_train_96(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
