            ##
            # Author: Autogenerated on 2013-12-05 22:49:50
            # gitHash: dbc23230f6666890a6cb7c4234e68e540e096e0c
            # SEED: 779905237530228736
            ##
            source('./findNSourceUtils.R')
            simpleFilterTest_pharynx_33 <- function(conn) {
                Log.info("A munge-task R unit test on data <pharynx> testing the functional unit <!=> ")
                Log.info("Uploading pharynx")
                hex <- h2o.uploadFile(conn, locate("../../smalldata/logreg/umass_statdata/pharynx.dat"), "rpharynx.hex")
                Log.info("Filtering out rows by != from dataset pharynx and column \"9\" using value 1.47592978687")
                     filterHex <- hex[hex[,c(9)] != 1.47592978687,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"9" != 1.47592978687,]
                    Log.info("Filtering out rows by != from dataset pharynx and column \"2\" using value 1.45227349302, and also subsetting columns.")
                     filterHex <- hex[hex[,c(2)] != 1.45227349302, c(2)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(2)] != 1.45227349302, c(11,10,12,1,3,2,5,4,7,6,9,8)]
            testEnd()
            }
            doTest("simpleFilterTest_ on data pharynx unit= !=", simpleFilterTest_pharynx_33)
