            ##
            # Author: Autogenerated on 2013-11-27 03:20:00
            # gitHash: 25eb0cfd1269362ae85d0f073d9abde2a68ac0e4
            # SEED: 4617575514352894151
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            simpleFilterTest_covtype_89 <- function(conn) {
                Log.info("A munge-task R unit test on data <covtype> testing the functional unit <>=> ")
                Log.info("Uploading covtype")
                hex <- h2o.uploadFile(conn, "../../smalldata/covtype/covtype.20k.data", "rcovtype.hex")
                Log.info("Filtering out rows by >= from dataset covtype and column \"24\" using value 0.315046488628")
                     filterHex <- hex[hex[,c(24)] >= 0.315046488628,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"24" >= 0.315046488628,]
                Log.info("Filtering out rows by >= from dataset covtype and column \"20\" using value 0.0")
                     filterHex <- hex[hex[,c(20)] >= 0.0,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"20" >= 0.0,]
                Log.info("Filtering out rows by >= from dataset covtype and column \"22\" using value 0.252602838602")
                     filterHex <- hex[hex[,c(22)] >= 0.252602838602,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"22" >= 0.252602838602,]
                Log.info("Filtering out rows by >= from dataset covtype and column \"40\" using value 0.18082560028")
                     filterHex <- hex[hex[,c(40)] >= 0.18082560028,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"40" >= 0.18082560028,]
                Log.info("Filtering out rows by >= from dataset covtype and column \"43\" using value 0.277785578787")
                     filterHex <- hex[hex[,c(43)] >= 0.277785578787,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"43" >= 0.277785578787,]
                Log.info("Filtering out rows by >= from dataset covtype and column \"0\" using value 2307.33407003")
                     filterHex <- hex[hex[,c(1)] >= 2307.33407003,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"0" >= 2307.33407003,]
                Log.info("Filtering out rows by >= from dataset covtype and column \"47\" using value 0.286138642961")
                     filterHex <- hex[hex[,c(47)] >= 0.286138642961,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"47" >= 0.286138642961,]
                Log.info("Filtering out rows by >= from dataset covtype and column \"4\" using value 439.855692917")
                     filterHex <- hex[hex[,c(4)] >= 439.855692917,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"4" >= 439.855692917,]
                Log.info("Filtering out rows by >= from dataset covtype and column \"15\" using value 0.311444092834")
                     filterHex <- hex[hex[,c(15)] >= 0.311444092834,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"15" >= 0.311444092834,]
                Log.info("Filtering out rows by >= from dataset covtype and column \"38\" using value 0.548317094253")
                     filterHex <- hex[hex[,c(38)] >= 0.548317094253,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"38" >= 0.548317094253,]
                Log.info("Filtering out rows by >= from dataset covtype and column \"45\" using value 0.416143702051")
                     filterHex <- hex[hex[,c(45)] >= 0.416143702051,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"45" >= 0.416143702051,]
                Log.info("Filtering out rows by >= from dataset covtype and column \"19\" using value 0.633510563066")
                     filterHex <- hex[hex[,c(19)] >= 0.633510563066,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"19" >= 0.633510563066,]
                Log.info("Filtering out rows by >= from dataset covtype and column \"5\" using value 6051.30330236")
                     filterHex <- hex[hex[,c(5)] >= 6051.30330236,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"5" >= 6051.30330236,]
                Log.info("Filtering out rows by >= from dataset covtype and column \"17\" using value 0.202172954193")
                     filterHex <- hex[hex[,c(17)] >= 0.202172954193,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"17" >= 0.202172954193,]
                Log.info("Filtering out rows by >= from dataset covtype and column \"14\" using value 0.82729851885")
                     filterHex <- hex[hex[,c(14)] >= 0.82729851885,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"14" >= 0.82729851885,]
                    Log.info("Filtering out rows by >= from dataset covtype and column \"7\" using value 226.362870681, and also subsetting columns.")
                     filterHex <- hex[hex[,c(7)] >= 226.362870681, c(7)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(7)] >= 226.362870681, c(54,42,48,43,49,52,53,24,25,26,27,20,21,22,23,46,47,44,45,28,29,40,41,1,3,2,5,4,7,6,9,8,51,39,38,11,10,13,12,15,14,17,16,19,18,31,30,37,36,35,34,33,32,50)]
                    Log.info("Filtering out rows by >= from dataset covtype and column \"15\" using value 0.21763318075, and also subsetting columns.")
                     filterHex <- hex[hex[,c(15)] >= 0.21763318075, c(15)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(15)] >= 0.21763318075, c(54,42,48,43,49,52,53,24,25,26,27,20,21,22,23,46,47,44,45,28,29,40,41,1,3,2,5,4,7,6,9,8,51,39,38,11,10,13,12,15,14,17,16,19,18,31,30,37,36,35,34,33,32,50)]
                    Log.info("Filtering out rows by >= from dataset covtype and column \"45\" using value 0.713687514714, and also subsetting columns.")
                     filterHex <- hex[hex[,c(45)] >= 0.713687514714, c(45)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(45)] >= 0.713687514714, c(54,42,48,43,49,52,53,24,25,26,27,20,21,22,23,46,47,44,45,28,29,40,41,1,3,2,5,4,7,6,9,8,51,39,38,11,10,13,12,15,14,17,16,19,18,31,30,37,36,35,34,33,32,50)]
                    Log.info("Filtering out rows by >= from dataset covtype and column \"0\" using value 2573.59390004, and also subsetting columns.")
                     filterHex <- hex[hex[,c(1)] >= 2573.59390004, c(1)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(1)] >= 2573.59390004, c(54,42,48,43,49,52,53,24,25,26,27,20,21,22,23,46,47,44,45,28,29,40,41,1,3,2,5,4,7,6,9,8,51,39,38,11,10,13,12,15,14,17,16,19,18,31,30,37,36,35,34,33,32,50)]
                    Log.info("Filtering out rows by >= from dataset covtype and column \"13\" using value 0.410749182065, and also subsetting columns.")
                     filterHex <- hex[hex[,c(13)] >= 0.410749182065, c(13)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(13)] >= 0.410749182065, c(54,42,48,43,49,52,53,24,25,26,27,20,21,22,23,46,47,44,45,28,29,40,41,1,3,2,5,4,7,6,9,8,51,39,38,11,10,13,12,15,14,17,16,19,18,31,30,37,36,35,34,33,32,50)]
                    Log.info("Filtering out rows by >= from dataset covtype and column \"51\" using value 0.427906219282, and also subsetting columns.")
                     filterHex <- hex[hex[,c(51)] >= 0.427906219282, c(51)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(51)] >= 0.427906219282, c(54,42,48,43,49,52,53,24,25,26,27,20,21,22,23,46,47,44,45,28,29,40,41,1,3,2,5,4,7,6,9,8,51,39,38,11,10,13,12,15,14,17,16,19,18,31,30,37,36,35,34,33,32,50)]
                    Log.info("Filtering out rows by >= from dataset covtype and column \"12\" using value 0.67585711964, and also subsetting columns.")
                     filterHex <- hex[hex[,c(12)] >= 0.67585711964, c(12)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(12)] >= 0.67585711964, c(54,42,48,43,49,52,53,24,25,26,27,20,21,22,23,46,47,44,45,28,29,40,41,1,3,2,5,4,7,6,9,8,51,39,38,11,10,13,12,15,14,17,16,19,18,31,30,37,36,35,34,33,32,50)]
                    Log.info("Filtering out rows by >= from dataset covtype and column \"44\" using value 0.926818461651, and also subsetting columns.")
                     filterHex <- hex[hex[,c(44)] >= 0.926818461651, c(44)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(44)] >= 0.926818461651, c(54,42,48,43,49,52,53,24,25,26,27,20,21,22,23,46,47,44,45,28,29,40,41,1,3,2,5,4,7,6,9,8,51,39,38,11,10,13,12,15,14,17,16,19,18,31,30,37,36,35,34,33,32,50)]
                    Log.info("Filtering out rows by >= from dataset covtype and column \"52\" using value 0.0978455546611, and also subsetting columns.")
                     filterHex <- hex[hex[,c(52)] >= 0.0978455546611, c(52)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(52)] >= 0.0978455546611, c(54,42,48,43,49,52,53,24,25,26,27,20,21,22,23,46,47,44,45,28,29,40,41,1,3,2,5,4,7,6,9,8,51,39,38,11,10,13,12,15,14,17,16,19,18,31,30,37,36,35,34,33,32,50)]
                    Log.info("Filtering out rows by >= from dataset covtype and column \"13\" using value 0.146954482555, and also subsetting columns.")
                     filterHex <- hex[hex[,c(13)] >= 0.146954482555, c(13)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(13)] >= 0.146954482555, c(54,42,48,43,49,52,53,24,25,26,27,20,21,22,23,46,47,44,45,28,29,40,41,1,3,2,5,4,7,6,9,8,51,39,38,11,10,13,12,15,14,17,16,19,18,31,30,37,36,35,34,33,32,50)]
                    Log.info("Filtering out rows by >= from dataset covtype and column \"2\" using value 45.1919207322, and also subsetting columns.")
                     filterHex <- hex[hex[,c(2)] >= 45.1919207322, c(2)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(2)] >= 45.1919207322, c(54,42,48,43,49,52,53,24,25,26,27,20,21,22,23,46,47,44,45,28,29,40,41,1,3,2,5,4,7,6,9,8,51,39,38,11,10,13,12,15,14,17,16,19,18,31,30,37,36,35,34,33,32,50)]
                    Log.info("Filtering out rows by >= from dataset covtype and column \"48\" using value 0.372007579476, and also subsetting columns.")
                     filterHex <- hex[hex[,c(48)] >= 0.372007579476, c(48)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(48)] >= 0.372007579476, c(54,42,48,43,49,52,53,24,25,26,27,20,21,22,23,46,47,44,45,28,29,40,41,1,3,2,5,4,7,6,9,8,51,39,38,11,10,13,12,15,14,17,16,19,18,31,30,37,36,35,34,33,32,50)]
                    Log.info("Filtering out rows by >= from dataset covtype and column \"24\" using value 0.057010578439, and also subsetting columns.")
                     filterHex <- hex[hex[,c(24)] >= 0.057010578439, c(24)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(24)] >= 0.057010578439, c(54,42,48,43,49,52,53,24,25,26,27,20,21,22,23,46,47,44,45,28,29,40,41,1,3,2,5,4,7,6,9,8,51,39,38,11,10,13,12,15,14,17,16,19,18,31,30,37,36,35,34,33,32,50)]
                    Log.info("Filtering out rows by >= from dataset covtype and column \"3\" using value 907.053760511, and also subsetting columns.")
                     filterHex <- hex[hex[,c(3)] >= 907.053760511, c(3)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(3)] >= 907.053760511, c(54,42,48,43,49,52,53,24,25,26,27,20,21,22,23,46,47,44,45,28,29,40,41,1,3,2,5,4,7,6,9,8,51,39,38,11,10,13,12,15,14,17,16,19,18,31,30,37,36,35,34,33,32,50)]
                    Log.info("Filtering out rows by >= from dataset covtype and column \"40\" using value 0.127850179058, and also subsetting columns.")
                     filterHex <- hex[hex[,c(40)] >= 0.127850179058, c(40)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(40)] >= 0.127850179058, c(54,42,48,43,49,52,53,24,25,26,27,20,21,22,23,46,47,44,45,28,29,40,41,1,3,2,5,4,7,6,9,8,51,39,38,11,10,13,12,15,14,17,16,19,18,31,30,37,36,35,34,33,32,50)]
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("simpleFilterTest_ on data covtype", simpleFilterTest_covtype_89(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
