            ##
            # Author: Autogenerated on 2013-12-05 22:49:50
            # gitHash: dbc23230f6666890a6cb7c4234e68e540e096e0c
            # SEED: 779905237530228736
            ##
            source('./findNSourceUtils.R')
            simpleFilterTest_AustraliaCoast_16 <- function(conn) {
                Log.info("A munge-task R unit test on data <AustraliaCoast> testing the functional unit <>> ")
                Log.info("Uploading AustraliaCoast")
                hex <- h2o.uploadFile(conn, locate("../../smalldata/pca_test/AustraliaCoast.csv"), "rAustraliaCoast.hex")
                Log.info("Filtering out rows by > from dataset AustraliaCoast and column \"premax\" using value 292.615547971")
                     filterHex <- hex[hex[,c("premax")] > 292.615547971,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"premax" > 292.615547971,]
                Log.info("Filtering out rows by > from dataset AustraliaCoast and column \"minairtemp\" using value 282.619504267")
                     filterHex <- hex[hex[,c("minairtemp")] > 282.619504267,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"minairtemp" > 282.619504267,]
                Log.info("Filtering out rows by > from dataset AustraliaCoast and column \"minairtemp\" using value 282.202264151")
                     filterHex <- hex[hex[,c("minairtemp")] > 282.202264151,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"minairtemp" > 282.202264151,]
                Log.info("Filtering out rows by > from dataset AustraliaCoast and column \"runoffnew\" using value 1421.95896251")
                     filterHex <- hex[hex[,c("runoffnew")] > 1421.95896251,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"runoffnew" > 1421.95896251,]
                Log.info("Filtering out rows by > from dataset AustraliaCoast and column \"maxsoilmoist\" using value 12.3314431477")
                     filterHex <- hex[hex[,c("maxsoilmoist")] > 12.3314431477,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"maxsoilmoist" > 12.3314431477,]
                Log.info("Filtering out rows by > from dataset AustraliaCoast and column \"minairtemp\" using value 284.500003491")
                     filterHex <- hex[hex[,c("minairtemp")] > 284.500003491,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"minairtemp" > 284.500003491,]
                Log.info("Filtering out rows by > from dataset AustraliaCoast and column \"runoffnew\" using value 104.111248622")
                     filterHex <- hex[hex[,c("runoffnew")] > 104.111248622,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"runoffnew" > 104.111248622,]
                Log.info("Filtering out rows by > from dataset AustraliaCoast and column \"premax\" using value 126.379337455")
                     filterHex <- hex[hex[,c("premax")] > 126.379337455,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"premax" > 126.379337455,]
                Log.info("Filtering out rows by > from dataset AustraliaCoast and column \"premax\" using value 206.279944163")
                     filterHex <- hex[hex[,c("premax")] > 206.279944163,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"premax" > 206.279944163,]
                    Log.info("Filtering out rows by > from dataset AustraliaCoast and column \"premax\" using value 258.147733075, and also subsetting columns.")
                     filterHex <- hex[hex[,c("premax")] > 258.147733075, c("premax")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("premax")] > 258.147733075, c("maxairtemp","maxsoilmoist","Max_czcs","runoffnew","minairtemp","maxsst","premax","salmax")]
                    Log.info("Filtering out rows by > from dataset AustraliaCoast and column \"maxsoilmoist\" using value 5.2190343531, and also subsetting columns.")
                     filterHex <- hex[hex[,c("maxsoilmoist")] > 5.2190343531, c("maxsoilmoist")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("maxsoilmoist")] > 5.2190343531, c("maxairtemp","maxsoilmoist","Max_czcs","runoffnew","minairtemp","maxsst","premax","salmax")]
                    Log.info("Filtering out rows by > from dataset AustraliaCoast and column \"premax\" using value 51.6271424611, and also subsetting columns.")
                     filterHex <- hex[hex[,c("premax")] > 51.6271424611, c("premax")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("premax")] > 51.6271424611, c("maxairtemp","maxsoilmoist","Max_czcs","runoffnew","minairtemp","maxsst","premax","salmax")]
                    Log.info("Filtering out rows by > from dataset AustraliaCoast and column \"maxsoilmoist\" using value 7.62132757299, and also subsetting columns.")
                     filterHex <- hex[hex[,c("maxsoilmoist")] > 7.62132757299, c("maxsoilmoist")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("maxsoilmoist")] > 7.62132757299, c("maxairtemp","maxsoilmoist","Max_czcs","runoffnew","minairtemp","maxsst","premax","salmax")]
                    Log.info("Filtering out rows by > from dataset AustraliaCoast and column \"salmax\" using value 3588.46070963, and also subsetting columns.")
                     filterHex <- hex[hex[,c("salmax")] > 3588.46070963, c("salmax")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("salmax")] > 3588.46070963, c("maxairtemp","maxsoilmoist","Max_czcs","runoffnew","minairtemp","maxsst","premax","salmax")]
                    Log.info("Filtering out rows by > from dataset AustraliaCoast and column \"Max_czcs\" using value 11.0669943204, and also subsetting columns.")
                     filterHex <- hex[hex[,c("Max_czcs")] > 11.0669943204, c("Max_czcs")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("Max_czcs")] > 11.0669943204, c("maxairtemp","maxsoilmoist","Max_czcs","runoffnew","minairtemp","maxsst","premax","salmax")]
                    Log.info("Filtering out rows by > from dataset AustraliaCoast and column \"runoffnew\" using value 2.97107810916, and also subsetting columns.")
                     filterHex <- hex[hex[,c("runoffnew")] > 2.97107810916, c("runoffnew")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("runoffnew")] > 2.97107810916, c("maxairtemp","maxsoilmoist","Max_czcs","runoffnew","minairtemp","maxsst","premax","salmax")]
                    Log.info("Filtering out rows by > from dataset AustraliaCoast and column \"maxsoilmoist\" using value 12.8004054956, and also subsetting columns.")
                     filterHex <- hex[hex[,c("maxsoilmoist")] > 12.8004054956, c("maxsoilmoist")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("maxsoilmoist")] > 12.8004054956, c("maxairtemp","maxsoilmoist","Max_czcs","runoffnew","minairtemp","maxsst","premax","salmax")]
                    Log.info("Filtering out rows by > from dataset AustraliaCoast and column \"premax\" using value 334.220104006, and also subsetting columns.")
                     filterHex <- hex[hex[,c("premax")] > 334.220104006, c("premax")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("premax")] > 334.220104006, c("maxairtemp","maxsoilmoist","Max_czcs","runoffnew","minairtemp","maxsst","premax","salmax")]
            testEnd()
            }
            doTest("simpleFilterTest_ on data AustraliaCoast unit= >", simpleFilterTest_AustraliaCoast_16)
