            ##
            # Author: Autogenerated on 2013-11-27 18:13:59
            # gitHash: c4ad841105ba82f4a3979e4cf1ae7e20a5905e59
            # SEED: 4663640625336856642
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            simpleFilterTest_prostate_2_114 <- function(conn) {
                Log.info("A munge-task R unit test on data <prostate_2> testing the functional unit <==> ")
                Log.info("Uploading prostate_2")
                hex <- h2o.uploadFile(conn, locate("../../smalldata/parse_folder_test/prostate_2.csv"), "rprostate_2.hex")
                Log.info("Filtering out rows by == from dataset prostate_2 and column \"8\" using value 5.28323176015")
                     filterHex <- hex[hex[,c(8)] == 5.28323176015,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"8" == 5.28323176015,]
                Log.info("Filtering out rows by == from dataset prostate_2 and column \"6\" using value 17.3944543742")
                     filterHex <- hex[hex[,c(6)] == 17.3944543742,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"6" == 17.3944543742,]
                Log.info("Filtering out rows by == from dataset prostate_2 and column \"2\" using value 63.7939885266")
                     filterHex <- hex[hex[,c(2)] == 63.7939885266,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"2" == 63.7939885266,]
                Log.info("Filtering out rows by == from dataset prostate_2 and column \"6\" using value 43.5539561089")
                     filterHex <- hex[hex[,c(6)] == 43.5539561089,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"6" == 43.5539561089,]
                Log.info("Filtering out rows by == from dataset prostate_2 and column \"5\" using value 1.0")
                     filterHex <- hex[hex[,c(5)] == 1.0,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"5" == 1.0,]
                Log.info("Filtering out rows by == from dataset prostate_2 and column \"1\" using value 0.0596153920016")
                     filterHex <- hex[hex[,c(1)] == 0.0596153920016,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"1" == 0.0596153920016,]
                Log.info("Filtering out rows by == from dataset prostate_2 and column \"1\" using value 0.225572624595")
                     filterHex <- hex[hex[,c(1)] == 0.225572624595,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"1" == 0.225572624595,]
                Log.info("Filtering out rows by == from dataset prostate_2 and column \"1\" using value 0.495901509403")
                     filterHex <- hex[hex[,c(1)] == 0.495901509403,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"1" == 0.495901509403,]
                Log.info("Filtering out rows by == from dataset prostate_2 and column \"6\" using value 34.7396214068")
                     filterHex <- hex[hex[,c(6)] == 34.7396214068,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"6" == 34.7396214068,]
                Log.info("Filtering out rows by == from dataset prostate_2 and column \"8\" using value 5.89341070578")
                     filterHex <- hex[hex[,c(8)] == 5.89341070578,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"8" == 5.89341070578,]
                Log.info("Filtering out rows by == from dataset prostate_2 and column \"2\" using value 58.434739954")
                     filterHex <- hex[hex[,c(2)] == 58.434739954,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"2" == 58.434739954,]
                Log.info("Filtering out rows by == from dataset prostate_2 and column \"1\" using value 0.522403486448")
                     filterHex <- hex[hex[,c(1)] == 0.522403486448,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"1" == 0.522403486448,]
                    Log.info("Filtering out rows by == from dataset prostate_2 and column \"2\" using value 58.0846578393, and also subsetting columns.")
                     filterHex <- hex[hex[,c(2)] == 58.0846578393, c(2)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(2)] == 58.0846578393, c(1,3,2,5,4,7,6,8)]
                    Log.info("Filtering out rows by == from dataset prostate_2 and column \"1\" using value 0.427999269465, and also subsetting columns.")
                     filterHex <- hex[hex[,c(1)] == 0.427999269465, c(1)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(1)] == 0.427999269465, c(1,3,2,5,4,7,6,8)]
                    Log.info("Filtering out rows by == from dataset prostate_2 and column \"5\" using value 1.0, and also subsetting columns.")
                     filterHex <- hex[hex[,c(5)] == 1.0, c(5)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(5)] == 1.0, c(1,3,2,5,4,7,6,8)]
                    Log.info("Filtering out rows by == from dataset prostate_2 and column \"8\" using value 5.50877808726, and also subsetting columns.")
                     filterHex <- hex[hex[,c(8)] == 5.50877808726, c(8)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(8)] == 5.50877808726, c(1,3,2,5,4,7,6,8)]
                    Log.info("Filtering out rows by == from dataset prostate_2 and column \"8\" using value 6.48062726848, and also subsetting columns.")
                     filterHex <- hex[hex[,c(8)] == 6.48062726848, c(8)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(8)] == 6.48062726848, c(1,3,2,5,4,7,6,8)]
                    Log.info("Filtering out rows by == from dataset prostate_2 and column \"8\" using value 6.60106598753, and also subsetting columns.")
                     filterHex <- hex[hex[,c(8)] == 6.60106598753, c(8)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(8)] == 6.60106598753, c(1,3,2,5,4,7,6,8)]
                    Log.info("Filtering out rows by == from dataset prostate_2 and column \"5\" using value 1.0, and also subsetting columns.")
                     filterHex <- hex[hex[,c(5)] == 1.0, c(5)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(5)] == 1.0, c(1,3,2,5,4,7,6,8)]
                    Log.info("Filtering out rows by == from dataset prostate_2 and column \"8\" using value 6.10191678863, and also subsetting columns.")
                     filterHex <- hex[hex[,c(8)] == 6.10191678863, c(8)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(8)] == 6.10191678863, c(1,3,2,5,4,7,6,8)]
                    Log.info("Filtering out rows by == from dataset prostate_2 and column \"0\" using value 23.8490834675, and also subsetting columns.")
                     filterHex <- hex[hex[,c(1)] == 23.8490834675, c(1)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(1)] == 23.8490834675, c(1,3,2,5,4,7,6,8)]
                    Log.info("Filtering out rows by == from dataset prostate_2 and column \"0\" using value 26.9777605122, and also subsetting columns.")
                     filterHex <- hex[hex[,c(1)] == 26.9777605122, c(1)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(1)] == 26.9777605122, c(1,3,2,5,4,7,6,8)]
                    Log.info("Filtering out rows by == from dataset prostate_2 and column \"7\" using value 21.5060795578, and also subsetting columns.")
                     filterHex <- hex[hex[,c(7)] == 21.5060795578, c(7)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(7)] == 21.5060795578, c(1,3,2,5,4,7,6,8)]
                    Log.info("Filtering out rows by == from dataset prostate_2 and column \"7\" using value 52.2925623638, and also subsetting columns.")
                     filterHex <- hex[hex[,c(7)] == 52.2925623638, c(7)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(7)] == 52.2925623638, c(1,3,2,5,4,7,6,8)]
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("simpleFilterTest_ on data prostate_2", simpleFilterTest_prostate_2_114(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
