            ##
            # Author: Autogenerated on 2013-11-27 18:13:58
            # gitHash: c4ad841105ba82f4a3979e4cf1ae7e20a5905e59
            # SEED: 4663640625336856642
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            simpleFilterTest_train_45 <- function(conn) {
                Log.info("A munge-task R unit test on data <train> testing the functional unit <<=> ")
                Log.info("Uploading train")
                hex <- h2o.uploadFile(conn, locate("../../smalldata/chess/chess_1x2x1000/h2o/train.csv"), "rtrain.hex")
                Log.info("Filtering out rows by <= from dataset train and column \"x\" using value 0.0301960095769")
                     filterHex <- hex[hex[,c("x")] <= 0.0301960095769,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"x" <= 0.0301960095769,]
                Log.info("Filtering out rows by <= from dataset train and column \"y\" using value 1.01659268748")
                     filterHex <- hex[hex[,c("y")] <= 1.01659268748,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"y" <= 1.01659268748,]
                Log.info("Filtering out rows by <= from dataset train and column \"x\" using value 0.398513130522")
                     filterHex <- hex[hex[,c("x")] <= 0.398513130522,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"x" <= 0.398513130522,]
                    Log.info("Filtering out rows by <= from dataset train and column \"y\" using value 1.43503975034, and also subsetting columns.")
                     filterHex <- hex[hex[,c("y")] <= 1.43503975034, c("y")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("y")] <= 1.43503975034, c("color","x","y")]
                    Log.info("Filtering out rows by <= from dataset train and column \"y\" using value 1.66393005888, and also subsetting columns.")
                     filterHex <- hex[hex[,c("y")] <= 1.66393005888, c("y")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("y")] <= 1.66393005888, c("color","x","y")]
                    Log.info("Filtering out rows by <= from dataset train and column \"y\" using value 1.46966981739, and also subsetting columns.")
                     filterHex <- hex[hex[,c("y")] <= 1.46966981739, c("y")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("y")] <= 1.46966981739, c("color","x","y")]
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("simpleFilterTest_ on data train", simpleFilterTest_train_45(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
