            ##
            # Author: Autogenerated on 2013-11-27 03:20:00
            # gitHash: 25eb0cfd1269362ae85d0f073d9abde2a68ac0e4
            # SEED: 4617575514352894151
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            complexFilterTest_leads_169 <- function(conn) {
                Log.info("A munge-task R unit test on data <leads> testing the functional unit <['!', '>', '&', '<=', '&', '!|', '!', '==']> ")
                Log.info("Uploading leads")
                hex <- h2o.uploadFile(conn, "../../smalldata/iris/leads.csv", "rleads.hex")
            Log.info("Performing compound task !( ( hex[,c(\"class\")] > 1.42247366339 ) & ( hex[,c(\"item_price\")] <= 3.7343473649 ) & ( hex[,c(\"frequent_customer\")] !| 6.85400018941 ) ! ( hex[,c(\"risk_idx\")] == 1.91271340711 )) on dataset <leads>")
                     filterHex <- hex[!( ( hex[,c("class")] > 1.42247366339 ) & ( hex[,c("item_price")] <= 3.7343473649 ) & ( hex[,c("frequent_customer")] !| 6.85400018941 ) ! ( hex[,c("risk_idx")] == 1.91271340711 )),]
            Log.info("Performing compound task !( ( hex[,c(\"frequent_customer\")] > 6.06039118611 ) & ( hex[,c(\"risk_idx\")] <= 0.793644809248 ) & ( hex[,c(\"risk_idx\")] !| 1.89341375427 ) ! ( hex[,c(\"frequent_customer\")] == 6.46364683448 )) on dataset leads, and also subsetting columns.")
                     filterHex <- hex[!( ( hex[,c("frequent_customer")] > 6.06039118611 ) & ( hex[,c("risk_idx")] <= 0.793644809248 ) & ( hex[,c("risk_idx")] !| 1.89341375427 ) ! ( hex[,c("frequent_customer")] == 6.46364683448 )), c("risk_idx","class","frequent_customer","desire_idx","item_price")]
                Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[!( ( hex[,c("frequent_customer")] > 6.06039118611 ) & ( hex[,c("risk_idx")] <= 0.793644809248 ) & ( hex[,c("risk_idx")] !| 1.89341375427 ) ! ( hex[,c("frequent_customer")] == 6.46364683448 )), c("date")]
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("compoundFilterTest_ on data leads", complexFilterTest_leads_169(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
