            ##
            # Author: Autogenerated on 2013-11-27 17:26:17
            # gitHash: a4fe16d99eb5f003dd7c7d0da17f29e1712eda0f
            # SEED: 8586424275721420395
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            complexFilterTest_stego_testing_157 <- function(conn) {
                Log.info("A munge-task R unit test on data <stego_testing> testing the functional unit <['!', '==', '&', '>', '|', '>=']> ")
                Log.info("Uploading stego_testing")
                hex <- h2o.uploadFile(conn, locate("../../smalldata/stego/stego_testing.data"), "rstego_testing.hex")
            Log.info("Performing compound task !( ( hex[,c(52)] == 0.0485891758522 ) & ( hex[,c(116)] > 0.0270013813847 ) | ( ( hex[,c(134)] >= 0.131157078926 )) ) on dataset <stego_testing>")
                     filterHex <- hex[!( ( hex[,c(52)] == 0.0485891758522 ) & ( hex[,c(116)] > 0.0270013813847 ) | ( ( hex[,c(134)] >= 0.131157078926 )) ),]
            Log.info("Performing compound task !( ( hex[,c(33)] == 0.267529196454 ) & ( hex[,c(109)] > 0.00772775532372 ) | ( ( hex[,c(91)] >= 0.220439265683 )) ) on dataset stego_testing, and also subsetting columns.")
                     filterHex <- hex[!( ( hex[,c(33)] == 0.267529196454 ) & ( hex[,c(109)] > 0.00772775532372 ) | ( ( hex[,c(91)] >= 0.220439265683 )) ), c(13,48,33,6,37,40,61,3,109,137,129,91,83)]
                Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[!( ( hex[,c(33)] == 0.267529196454 ) & ( hex[,c(109)] > 0.00772775532372 ) | ( ( hex[,c(91)] >= 0.220439265683 )) ), c(133,132,131,130,136,135,134,139,138,24,25,26,27,20,21,22,23,160,28,29,161,4,8,163,119,120,121,122,123,124,125,126,127,128,118,59,58,55,54,57,56,51,50,53,52,115,114,88,89,111,110,113,112,82,80,81,86,87,84,85,7,108,102,103,100,101,106,107,104,105,39,38,32,31,30,36,35,34,60,62,63,64,65,66,67,68,69,2,162,99,98,90,93,92,95,94,97,96,11,10,12,15,14,17,16,19,18,117,116,151,150,153,152,155,154,157,156,159,158,49,46,47,44,45,42,43,41,1,5,9,146,147,144,145,142,143,140,141,148,149,77,76,75,74,73,72,71,70,79,78)]
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("compoundFilterTest_ on data stego_testing", complexFilterTest_stego_testing_157(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
