            ##
            # Author: Autogenerated on 2013-11-27 03:20:00
            # gitHash: 25eb0cfd1269362ae85d0f073d9abde2a68ac0e4
            # SEED: 4617575514352894151
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            complexFilterTest_test_191 <- function(conn) {
                Log.info("A munge-task R unit test on data <test> testing the functional unit <['!', '<=', '&', '==', '|', '>', '&', '>=', '|', '!=']> ")
                Log.info("Uploading test")
                hex <- h2o.uploadFile(conn, "../../smalldata/chess/chess_2x2x100/h2o/test.csv", "rtest.hex")
            Log.info("Performing compound task !( ( hex[,c(\"y\")] <= 1.37697344301 ) & ( hex[,c(\"y\")] == 1.37500119586 )) on dataset <test>")
                     filterHex <- hex[!( ( hex[,c("y")] <= 1.37697344301 ) & ( hex[,c("y")] == 1.37500119586 )),]
            Log.info("Performing compound task !( ( hex[,c(\"y\")] <= 0.349516778436 ) & ( hex[,c(\"y\")] == 0.499116736741 )) on dataset test, and also subsetting columns.")
                     filterHex <- hex[!( ( hex[,c("y")] <= 0.349516778436 ) & ( hex[,c("y")] == 0.499116736741 )), c("y")]
                Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[!( ( hex[,c("y")] <= 0.349516778436 ) & ( hex[,c("y")] == 0.499116736741 )), c("x","color")]
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("compoundFilterTest_ on data test", complexFilterTest_test_191(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
