            ##
            # Author: Autogenerated on 2013-11-27 18:13:59
            # gitHash: c4ad841105ba82f4a3979e4cf1ae7e20a5905e59
            # SEED: 4663640625336856642
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            simpleFilterTest_constantColumn_100 <- function(conn) {
                Log.info("A munge-task R unit test on data <constantColumn> testing the functional unit <==> ")
                Log.info("Uploading constantColumn")
                hex <- h2o.uploadFile(conn, locate("../../smalldata/constantColumn.csv"), "rconstantColumn.hex")
                Log.info("Filtering out rows by == from dataset constantColumn and column \"konstant\" using value 0.1")
                     filterHex <- hex[hex[,c("konstant")] == 0.1,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"konstant" == 0.1,]
                    Log.info("Filtering out rows by == from dataset constantColumn and column \"konstant\" using value 0.1, and also subsetting columns.")
                     filterHex <- hex[hex[,c("konstant")] == 0.1, c("konstant")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("konstant")] == 0.1, c("konstant")]
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("simpleFilterTest_ on data constantColumn", simpleFilterTest_constantColumn_100(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
