            ##
            # Author: Autogenerated on 2013-11-27 03:20:00
            # gitHash: 25eb0cfd1269362ae85d0f073d9abde2a68ac0e4
            # SEED: 4617575514352894151
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            complexFilterTest_iris_test_numeric_missing_171 <- function(conn) {
                Log.info("A munge-task R unit test on data <iris_test_numeric_missing> testing the functional unit <['!', '>', '&', '<=', '&', '!|', '!', '==']> ")
                Log.info("Uploading iris_test_numeric_missing")
                hex <- h2o.uploadFile(conn, "../../smalldata/test/classifier/iris_test_numeric_missing.csv", "riris_test_numeric_missing.hex")
            Log.info("Performing compound task !( ( hex[,c(\"sepal_len\")] > 6.43145279717 ) & ( hex[,c(\"petal_len\")] <= 3.31021527615 ) & ( hex[,c(\"species\")] !| 1.0 ) ! ( hex[,c(\"sepal_len\")] == 6.06301097019 )) on dataset <iris_test_numeric_missing>")
                     filterHex <- hex[!( ( hex[,c("sepal_len")] > 6.43145279717 ) & ( hex[,c("petal_len")] <= 3.31021527615 ) & ( hex[,c("species")] !| 1.0 ) ! ( hex[,c("sepal_len")] == 6.06301097019 )),]
            Log.info("Performing compound task !( ( hex[,c(\"petal_wid\")] > 1.51031508963 ) & ( hex[,c(\"petal_wid\")] <= 1.20335883475 ) & ( hex[,c(\"sepal_len\")] !| 5.73500387442 ) ! ( hex[,c(\"petal_wid\")] == 1.471312021 )) on dataset iris_test_numeric_missing, and also subsetting columns.")
                     filterHex <- hex[!( ( hex[,c("petal_wid")] > 1.51031508963 ) & ( hex[,c("petal_wid")] <= 1.20335883475 ) & ( hex[,c("sepal_len")] !| 5.73500387442 ) ! ( hex[,c("petal_wid")] == 1.471312021 )), c("petal_wid","sepal_wid","petal_len","sepal_len","species")]
                Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[!( ( hex[,c("petal_wid")] > 1.51031508963 ) & ( hex[,c("petal_wid")] <= 1.20335883475 ) & ( hex[,c("sepal_len")] !| 5.73500387442 ) ! ( hex[,c("petal_wid")] == 1.471312021 )), c(1)]
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("compoundFilterTest_ on data iris_test_numeric_missing", complexFilterTest_iris_test_numeric_missing_171(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
