            ##
            # Author: Autogenerated on 2013-11-27 03:20:00
            # gitHash: 25eb0cfd1269362ae85d0f073d9abde2a68ac0e4
            # SEED: 4617575514352894151
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            simpleFilterTest_AirlinesTrain_96 <- function(conn) {
                Log.info("A munge-task R unit test on data <AirlinesTrain> testing the functional unit <>=> ")
                Log.info("Uploading AirlinesTrain")
                hex <- h2o.uploadFile(conn, "../../smalldata/airlines/AirlinesTrain.csv.zip", "rAirlinesTrain.hex")
                Log.info("Filtering out rows by >= from dataset AirlinesTrain and column \"IsDepDelayed_REC\" using value 0.686201155263")
                     filterHex <- hex[hex[,c("IsDepDelayed_REC")] >= 0.686201155263,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"IsDepDelayed_REC" >= 0.686201155263,]
                Log.info("Filtering out rows by >= from dataset AirlinesTrain and column \"Distance\" using value 1835.89796705")
                     filterHex <- hex[hex[,c("Distance")] >= 1835.89796705,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"Distance" >= 1835.89796705,]
                Log.info("Filtering out rows by >= from dataset AirlinesTrain and column \"IsDepDelayed_REC\" using value 0.916501742373")
                     filterHex <- hex[hex[,c("IsDepDelayed_REC")] >= 0.916501742373,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"IsDepDelayed_REC" >= 0.916501742373,]
                Log.info("Filtering out rows by >= from dataset AirlinesTrain and column \"Distance\" using value 1549.70127415")
                     filterHex <- hex[hex[,c("Distance")] >= 1549.70127415,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"Distance" >= 1549.70127415,]
                Log.info("Filtering out rows by >= from dataset AirlinesTrain and column \"Distance\" using value 1607.87558758")
                     filterHex <- hex[hex[,c("Distance")] >= 1607.87558758,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"Distance" >= 1607.87558758,]
                Log.info("Filtering out rows by >= from dataset AirlinesTrain and column \"DepTime\" using value 1375.5843692")
                     filterHex <- hex[hex[,c("DepTime")] >= 1375.5843692,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"DepTime" >= 1375.5843692,]
                Log.info("Filtering out rows by >= from dataset AirlinesTrain and column \"IsDepDelayed_REC\" using value 0.866734069514")
                     filterHex <- hex[hex[,c("IsDepDelayed_REC")] >= 0.866734069514,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"IsDepDelayed_REC" >= 0.866734069514,]
                Log.info("Filtering out rows by >= from dataset AirlinesTrain and column \"Distance\" using value 2247.02187839")
                     filterHex <- hex[hex[,c("Distance")] >= 2247.02187839,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"Distance" >= 2247.02187839,]
                Log.info("Filtering out rows by >= from dataset AirlinesTrain and column \"Distance\" using value 2323.89860912")
                     filterHex <- hex[hex[,c("Distance")] >= 2323.89860912,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"Distance" >= 2323.89860912,]
                Log.info("Filtering out rows by >= from dataset AirlinesTrain and column \"DepTime\" using value 2154.66018951")
                     filterHex <- hex[hex[,c("DepTime")] >= 2154.66018951,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"DepTime" >= 2154.66018951,]
                Log.info("Filtering out rows by >= from dataset AirlinesTrain and column \"Distance\" using value 1155.27251494")
                     filterHex <- hex[hex[,c("Distance")] >= 1155.27251494,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"Distance" >= 1155.27251494,]
                Log.info("Filtering out rows by >= from dataset AirlinesTrain and column \"DepTime\" using value 1555.84224547")
                     filterHex <- hex[hex[,c("DepTime")] >= 1555.84224547,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"DepTime" >= 1555.84224547,]
                Log.info("Filtering out rows by >= from dataset AirlinesTrain and column \"IsDepDelayed_REC\" using value -0.0990217395377")
                     filterHex <- hex[hex[,c("IsDepDelayed_REC")] >= -0.0990217395377,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"IsDepDelayed_REC" >= -0.0990217395377,]
                Log.info("Filtering out rows by >= from dataset AirlinesTrain and column \"DepTime\" using value 1172.02777719")
                     filterHex <- hex[hex[,c("DepTime")] >= 1172.02777719,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"DepTime" >= 1172.02777719,]
                Log.info("Filtering out rows by >= from dataset AirlinesTrain and column \"Distance\" using value 3117.85026888")
                     filterHex <- hex[hex[,c("Distance")] >= 3117.85026888,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"Distance" >= 3117.85026888,]
                Log.info("Filtering out rows by >= from dataset AirlinesTrain and column \"DepTime\" using value 186.316158565")
                     filterHex <- hex[hex[,c("DepTime")] >= 186.316158565,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"DepTime" >= 186.316158565,]
                Log.info("Filtering out rows by >= from dataset AirlinesTrain and column \"ArrTime\" using value 912.786048282")
                     filterHex <- hex[hex[,c("ArrTime")] >= 912.786048282,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"ArrTime" >= 912.786048282,]
                Log.info("Filtering out rows by >= from dataset AirlinesTrain and column \"ArrTime\" using value 15.6797609927")
                     filterHex <- hex[hex[,c("ArrTime")] >= 15.6797609927,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"ArrTime" >= 15.6797609927,]
                Log.info("Filtering out rows by >= from dataset AirlinesTrain and column \"DepTime\" using value 1144.52024123")
                     filterHex <- hex[hex[,c("DepTime")] >= 1144.52024123,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"DepTime" >= 1144.52024123,]
                    Log.info("Filtering out rows by >= from dataset AirlinesTrain and column \"DepTime\" using value 1282.65486736, and also subsetting columns.")
                     filterHex <- hex[hex[,c("DepTime")] >= 1282.65486736, c("DepTime")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("DepTime")] >= 1282.65486736, c("Distance","IsDepDelayed_REC","DepTime","Origin","fDayofMonth","fMonth","fDayOfWeek","IsDepDelayed","fYear","Dest","UniqueCarrier","ArrTime")]
                    Log.info("Filtering out rows by >= from dataset AirlinesTrain and column \"IsDepDelayed_REC\" using value -0.532788454307, and also subsetting columns.")
                     filterHex <- hex[hex[,c("IsDepDelayed_REC")] >= -0.532788454307, c("IsDepDelayed_REC")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("IsDepDelayed_REC")] >= -0.532788454307, c("Distance","IsDepDelayed_REC","DepTime","Origin","fDayofMonth","fMonth","fDayOfWeek","IsDepDelayed","fYear","Dest","UniqueCarrier","ArrTime")]
                    Log.info("Filtering out rows by >= from dataset AirlinesTrain and column \"Distance\" using value 2336.55893497, and also subsetting columns.")
                     filterHex <- hex[hex[,c("Distance")] >= 2336.55893497, c("Distance")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("Distance")] >= 2336.55893497, c("Distance","IsDepDelayed_REC","DepTime","Origin","fDayofMonth","fMonth","fDayOfWeek","IsDepDelayed","fYear","Dest","UniqueCarrier","ArrTime")]
                    Log.info("Filtering out rows by >= from dataset AirlinesTrain and column \"ArrTime\" using value 491.924668734, and also subsetting columns.")
                     filterHex <- hex[hex[,c("ArrTime")] >= 491.924668734, c("ArrTime")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("ArrTime")] >= 491.924668734, c("Distance","IsDepDelayed_REC","DepTime","Origin","fDayofMonth","fMonth","fDayOfWeek","IsDepDelayed","fYear","Dest","UniqueCarrier","ArrTime")]
                    Log.info("Filtering out rows by >= from dataset AirlinesTrain and column \"Distance\" using value 1073.23822601, and also subsetting columns.")
                     filterHex <- hex[hex[,c("Distance")] >= 1073.23822601, c("Distance")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("Distance")] >= 1073.23822601, c("Distance","IsDepDelayed_REC","DepTime","Origin","fDayofMonth","fMonth","fDayOfWeek","IsDepDelayed","fYear","Dest","UniqueCarrier","ArrTime")]
                    Log.info("Filtering out rows by >= from dataset AirlinesTrain and column \"IsDepDelayed_REC\" using value 0.674047993605, and also subsetting columns.")
                     filterHex <- hex[hex[,c("IsDepDelayed_REC")] >= 0.674047993605, c("IsDepDelayed_REC")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("IsDepDelayed_REC")] >= 0.674047993605, c("Distance","IsDepDelayed_REC","DepTime","Origin","fDayofMonth","fMonth","fDayOfWeek","IsDepDelayed","fYear","Dest","UniqueCarrier","ArrTime")]
                    Log.info("Filtering out rows by >= from dataset AirlinesTrain and column \"Distance\" using value 890.088168088, and also subsetting columns.")
                     filterHex <- hex[hex[,c("Distance")] >= 890.088168088, c("Distance")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("Distance")] >= 890.088168088, c("Distance","IsDepDelayed_REC","DepTime","Origin","fDayofMonth","fMonth","fDayOfWeek","IsDepDelayed","fYear","Dest","UniqueCarrier","ArrTime")]
                    Log.info("Filtering out rows by >= from dataset AirlinesTrain and column \"ArrTime\" using value 2029.2623551, and also subsetting columns.")
                     filterHex <- hex[hex[,c("ArrTime")] >= 2029.2623551, c("ArrTime")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("ArrTime")] >= 2029.2623551, c("Distance","IsDepDelayed_REC","DepTime","Origin","fDayofMonth","fMonth","fDayOfWeek","IsDepDelayed","fYear","Dest","UniqueCarrier","ArrTime")]
                    Log.info("Filtering out rows by >= from dataset AirlinesTrain and column \"IsDepDelayed_REC\" using value 0.626376531096, and also subsetting columns.")
                     filterHex <- hex[hex[,c("IsDepDelayed_REC")] >= 0.626376531096, c("IsDepDelayed_REC")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("IsDepDelayed_REC")] >= 0.626376531096, c("Distance","IsDepDelayed_REC","DepTime","Origin","fDayofMonth","fMonth","fDayOfWeek","IsDepDelayed","fYear","Dest","UniqueCarrier","ArrTime")]
                    Log.info("Filtering out rows by >= from dataset AirlinesTrain and column \"IsDepDelayed_REC\" using value 0.896435602762, and also subsetting columns.")
                     filterHex <- hex[hex[,c("IsDepDelayed_REC")] >= 0.896435602762, c("IsDepDelayed_REC")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("IsDepDelayed_REC")] >= 0.896435602762, c("Distance","IsDepDelayed_REC","DepTime","Origin","fDayofMonth","fMonth","fDayOfWeek","IsDepDelayed","fYear","Dest","UniqueCarrier","ArrTime")]
                    Log.info("Filtering out rows by >= from dataset AirlinesTrain and column \"ArrTime\" using value 27.273762546, and also subsetting columns.")
                     filterHex <- hex[hex[,c("ArrTime")] >= 27.273762546, c("ArrTime")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("ArrTime")] >= 27.273762546, c("Distance","IsDepDelayed_REC","DepTime","Origin","fDayofMonth","fMonth","fDayOfWeek","IsDepDelayed","fYear","Dest","UniqueCarrier","ArrTime")]
                    Log.info("Filtering out rows by >= from dataset AirlinesTrain and column \"IsDepDelayed_REC\" using value -0.416084859673, and also subsetting columns.")
                     filterHex <- hex[hex[,c("IsDepDelayed_REC")] >= -0.416084859673, c("IsDepDelayed_REC")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("IsDepDelayed_REC")] >= -0.416084859673, c("Distance","IsDepDelayed_REC","DepTime","Origin","fDayofMonth","fMonth","fDayOfWeek","IsDepDelayed","fYear","Dest","UniqueCarrier","ArrTime")]
                    Log.info("Filtering out rows by >= from dataset AirlinesTrain and column \"ArrTime\" using value 19.6793962957, and also subsetting columns.")
                     filterHex <- hex[hex[,c("ArrTime")] >= 19.6793962957, c("ArrTime")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("ArrTime")] >= 19.6793962957, c("Distance","IsDepDelayed_REC","DepTime","Origin","fDayofMonth","fMonth","fDayOfWeek","IsDepDelayed","fYear","Dest","UniqueCarrier","ArrTime")]
                    Log.info("Filtering out rows by >= from dataset AirlinesTrain and column \"Distance\" using value 3319.03691538, and also subsetting columns.")
                     filterHex <- hex[hex[,c("Distance")] >= 3319.03691538, c("Distance")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("Distance")] >= 3319.03691538, c("Distance","IsDepDelayed_REC","DepTime","Origin","fDayofMonth","fMonth","fDayOfWeek","IsDepDelayed","fYear","Dest","UniqueCarrier","ArrTime")]
                    Log.info("Filtering out rows by >= from dataset AirlinesTrain and column \"IsDepDelayed_REC\" using value -0.738121522733, and also subsetting columns.")
                     filterHex <- hex[hex[,c("IsDepDelayed_REC")] >= -0.738121522733, c("IsDepDelayed_REC")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("IsDepDelayed_REC")] >= -0.738121522733, c("Distance","IsDepDelayed_REC","DepTime","Origin","fDayofMonth","fMonth","fDayOfWeek","IsDepDelayed","fYear","Dest","UniqueCarrier","ArrTime")]
                    Log.info("Filtering out rows by >= from dataset AirlinesTrain and column \"ArrTime\" using value 563.167192794, and also subsetting columns.")
                     filterHex <- hex[hex[,c("ArrTime")] >= 563.167192794, c("ArrTime")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("ArrTime")] >= 563.167192794, c("Distance","IsDepDelayed_REC","DepTime","Origin","fDayofMonth","fMonth","fDayOfWeek","IsDepDelayed","fYear","Dest","UniqueCarrier","ArrTime")]
                    Log.info("Filtering out rows by >= from dataset AirlinesTrain and column \"DepTime\" using value 2255.02268314, and also subsetting columns.")
                     filterHex <- hex[hex[,c("DepTime")] >= 2255.02268314, c("DepTime")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("DepTime")] >= 2255.02268314, c("Distance","IsDepDelayed_REC","DepTime","Origin","fDayofMonth","fMonth","fDayOfWeek","IsDepDelayed","fYear","Dest","UniqueCarrier","ArrTime")]
                    Log.info("Filtering out rows by >= from dataset AirlinesTrain and column \"ArrTime\" using value 1318.50795866, and also subsetting columns.")
                     filterHex <- hex[hex[,c("ArrTime")] >= 1318.50795866, c("ArrTime")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("ArrTime")] >= 1318.50795866, c("Distance","IsDepDelayed_REC","DepTime","Origin","fDayofMonth","fMonth","fDayOfWeek","IsDepDelayed","fYear","Dest","UniqueCarrier","ArrTime")]
                    Log.info("Filtering out rows by >= from dataset AirlinesTrain and column \"DepTime\" using value 756.879579988, and also subsetting columns.")
                     filterHex <- hex[hex[,c("DepTime")] >= 756.879579988, c("DepTime")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("DepTime")] >= 756.879579988, c("Distance","IsDepDelayed_REC","DepTime","Origin","fDayofMonth","fMonth","fDayOfWeek","IsDepDelayed","fYear","Dest","UniqueCarrier","ArrTime")]
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("simpleFilterTest_ on data AirlinesTrain", simpleFilterTest_AirlinesTrain_96(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
