            ##
            # Author: Autogenerated on 2013-11-29 01:20:08
            # gitHash: 10810480518d43dd720690e729d2f3b9a0f8eba7
            # SEED: 7977475956795433203
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            simpleFilterTest_cgd_23 <- function(conn) {
                Log.info("A munge-task R unit test on data <cgd> testing the functional unit <<=> ")
                Log.info("Uploading cgd")
                hex <- h2o.uploadFile(conn, locate("../../smalldata/logreg/umass_statdata/cgd.dat"), "rcgd.hex")
                Log.info("Filtering out rows by <= from dataset cgd and column \"8\" using value 1.15920038139")
                     filterHex <- hex[hex[,c(8)] <= 1.15920038139,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"8" <= 1.15920038139,]
                Log.info("Filtering out rows by <= from dataset cgd and column \"5\" using value 5.02391416535")
                     filterHex <- hex[hex[,c(5)] <= 5.02391416535,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"5" <= 5.02391416535,]
                Log.info("Filtering out rows by <= from dataset cgd and column \"3\" using value 1.26036073188")
                     filterHex <- hex[hex[,c(3)] <= 1.26036073188,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"3" <= 1.26036073188,]
                Log.info("Filtering out rows by <= from dataset cgd and column \"8\" using value 1.40852940526")
                     filterHex <- hex[hex[,c(8)] <= 1.40852940526,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"8" <= 1.40852940526,]
                Log.info("Filtering out rows by <= from dataset cgd and column \"5\" using value 7.45657597519")
                     filterHex <- hex[hex[,c(5)] <= 7.45657597519,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"5" <= 7.45657597519,]
                Log.info("Filtering out rows by <= from dataset cgd and column \"2\" using value 26833.4646741")
                     filterHex <- hex[hex[,c(2)] <= 26833.4646741,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"2" <= 26833.4646741,]
                Log.info("Filtering out rows by <= from dataset cgd and column \"12\" using value 4.87213147672")
                     filterHex <- hex[hex[,c(12)] <= 4.87213147672,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"12" <= 4.87213147672,]
                Log.info("Filtering out rows by <= from dataset cgd and column \"8\" using value 1.95000317491")
                     filterHex <- hex[hex[,c(8)] <= 1.95000317491,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"8" <= 1.95000317491,]
                Log.info("Filtering out rows by <= from dataset cgd and column \"11\" using value 1.0909081758")
                     filterHex <- hex[hex[,c(11)] <= 1.0909081758,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"11" <= 1.0909081758,]
                    Log.info("Filtering out rows by <= from dataset cgd and column \"15\" using value 4.38887474537, and also subsetting columns.")
                     filterHex <- hex[hex[,c(15)] <= 4.38887474537, c(15)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(15)] <= 4.38887474537, c(11,10,13,12,15,14,1,3,2,5,4,7,6,9,8)]
                    Log.info("Filtering out rows by <= from dataset cgd and column \"7\" using value 76.0210092861, and also subsetting columns.")
                     filterHex <- hex[hex[,c(7)] <= 76.0210092861, c(7)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(7)] <= 76.0210092861, c(11,10,13,12,15,14,1,3,2,5,4,7,6,9,8)]
                    Log.info("Filtering out rows by <= from dataset cgd and column \"2\" using value 77944.2624045, and also subsetting columns.")
                     filterHex <- hex[hex[,c(2)] <= 77944.2624045, c(2)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(2)] <= 77944.2624045, c(11,10,13,12,15,14,1,3,2,5,4,7,6,9,8)]
                    Log.info("Filtering out rows by <= from dataset cgd and column \"14\" using value 1.90773789763, and also subsetting columns.")
                     filterHex <- hex[hex[,c(14)] <= 1.90773789763, c(14)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(14)] <= 1.90773789763, c(11,10,13,12,15,14,1,3,2,5,4,7,6,9,8)]
                    Log.info("Filtering out rows by <= from dataset cgd and column \"7\" using value 37.9291189009, and also subsetting columns.")
                     filterHex <- hex[hex[,c(7)] <= 37.9291189009, c(7)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(7)] <= 37.9291189009, c(11,10,13,12,15,14,1,3,2,5,4,7,6,9,8)]
                    Log.info("Filtering out rows by <= from dataset cgd and column \"10\" using value 1.76218729442, and also subsetting columns.")
                     filterHex <- hex[hex[,c(10)] <= 1.76218729442, c(10)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(10)] <= 1.76218729442, c(11,10,13,12,15,14,1,3,2,5,4,7,6,9,8)]
                    Log.info("Filtering out rows by <= from dataset cgd and column \"7\" using value 13.9071493221, and also subsetting columns.")
                     filterHex <- hex[hex[,c(7)] <= 13.9071493221, c(7)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(7)] <= 13.9071493221, c(11,10,13,12,15,14,1,3,2,5,4,7,6,9,8)]
                    Log.info("Filtering out rows by <= from dataset cgd and column \"1\" using value 15680.9033652, and also subsetting columns.")
                     filterHex <- hex[hex[,c(1)] <= 15680.9033652, c(1)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(1)] <= 15680.9033652, c(11,10,13,12,15,14,1,3,2,5,4,7,6,9,8)]
                    Log.info("Filtering out rows by <= from dataset cgd and column \"4\" using value 1.97905208244, and also subsetting columns.")
                     filterHex <- hex[hex[,c(4)] <= 1.97905208244, c(4)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(4)] <= 1.97905208244, c(11,10,13,12,15,14,1,3,2,5,4,7,6,9,8)]
            Log.info("End of test")
            PASSS <<- TRUE
            }
            PASSS <- FALSE
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("simpleFilterTest_ on data cgd", simpleFilterTest_cgd_23(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            if (!PASSS) FAIL("Did not reach the end of test. Check Rsandbox/errors.log for warnings and errors.")
            PASS()
