            ##
            # Author: Autogenerated on 2013-11-27 18:13:59
            # gitHash: c4ad841105ba82f4a3979e4cf1ae7e20a5905e59
            # SEED: 4663640625336856642
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            simpleFilterTest_sdss174052_130 <- function(conn) {
                Log.info("A munge-task R unit test on data <sdss174052> testing the functional unit <!=> ")
                Log.info("Uploading sdss174052")
                hex <- h2o.uploadFile(conn, locate("../../smalldata/gaussian/sdss174052.csv.gz"), "rsdss174052.hex")
                Log.info("Filtering out rows by != from dataset sdss174052 and column \"ultraviolet (double)\" using value 25.2664526984")
                     filterHex <- hex[hex[,c("ultraviolet (double)")] != 25.2664526984,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"ultraviolet (double)" != 25.2664526984,]
                Log.info("Filtering out rows by != from dataset sdss174052 and column \"green (double)\" using value -2580.15342084")
                     filterHex <- hex[hex[,c("green (double)")] != -2580.15342084,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"green (double)" != -2580.15342084,]
                Log.info("Filtering out rows by != from dataset sdss174052 and column \"green (double)\" using value -4838.86178953")
                     filterHex <- hex[hex[,c("green (double)")] != -4838.86178953,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"green (double)" != -4838.86178953,]
                Log.info("Filtering out rows by != from dataset sdss174052 and column \"ultraviolet (double)\" using value 22.1186426285")
                     filterHex <- hex[hex[,c("ultraviolet (double)")] != 22.1186426285,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"ultraviolet (double)" != 22.1186426285,]
                Log.info("Filtering out rows by != from dataset sdss174052 and column \"ultraviolet (double)\" using value 23.7605783202")
                     filterHex <- hex[hex[,c("ultraviolet (double)")] != 23.7605783202,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"ultraviolet (double)" != 23.7605783202,]
                Log.info("Filtering out rows by != from dataset sdss174052 and column \"green (double)\" using value -3559.87606539")
                     filterHex <- hex[hex[,c("green (double)")] != -3559.87606539,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"green (double)" != -3559.87606539,]
                Log.info("Filtering out rows by != from dataset sdss174052 and column \"declination (float)\" using value 24.3532868925")
                     filterHex <- hex[hex[,c("declination (float)")] != 24.3532868925,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"declination (float)" != 24.3532868925,]
                Log.info("Filtering out rows by != from dataset sdss174052 and column \"declination (float)\" using value 4.32795507509")
                     filterHex <- hex[hex[,c("declination (float)")] != 4.32795507509,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"declination (float)" != 4.32795507509,]
                Log.info("Filtering out rows by != from dataset sdss174052 and column \"right ascension (float)\" using value 279.159634471")
                     filterHex <- hex[hex[,c("right ascension (float)")] != 279.159634471,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"right ascension (float)" != 279.159634471,]
                Log.info("Filtering out rows by != from dataset sdss174052 and column \"z (double)\" using value 29.927450842")
                     filterHex <- hex[hex[,c("z (double)")] != 29.927450842,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"z (double)" != 29.927450842,]
                Log.info("Filtering out rows by != from dataset sdss174052 and column \"declination (float)\" using value 16.7934733665")
                     filterHex <- hex[hex[,c("declination (float)")] != 16.7934733665,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"declination (float)" != 16.7934733665,]
                Log.info("Filtering out rows by != from dataset sdss174052 and column \"infrared (double)\" using value 20.4309754188")
                     filterHex <- hex[hex[,c("infrared (double)")] != 20.4309754188,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"infrared (double)" != 20.4309754188,]
                    Log.info("Filtering out rows by != from dataset sdss174052 and column \"declination (float)\" using value 8.76089102039, and also subsetting columns.")
                     filterHex <- hex[hex[,c("declination (float)")] != 8.76089102039, c("declination (float)")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("declination (float)")] != 8.76089102039, c("infrared (double)","declination (float)","z (double)","red (double)","right ascension (float)","objectid (long)","ultraviolet (double)","green (double)")]
                    Log.info("Filtering out rows by != from dataset sdss174052 and column \"right ascension (float)\" using value 14.5936428722, and also subsetting columns.")
                     filterHex <- hex[hex[,c("right ascension (float)")] != 14.5936428722, c("right ascension (float)")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("right ascension (float)")] != 14.5936428722, c("infrared (double)","declination (float)","z (double)","red (double)","right ascension (float)","objectid (long)","ultraviolet (double)","green (double)")]
                    Log.info("Filtering out rows by != from dataset sdss174052 and column \"green (double)\" using value -4171.22775372, and also subsetting columns.")
                     filterHex <- hex[hex[,c("green (double)")] != -4171.22775372, c("green (double)")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("green (double)")] != -4171.22775372, c("infrared (double)","declination (float)","z (double)","red (double)","right ascension (float)","objectid (long)","ultraviolet (double)","green (double)")]
                    Log.info("Filtering out rows by != from dataset sdss174052 and column \"right ascension (float)\" using value 254.879088032, and also subsetting columns.")
                     filterHex <- hex[hex[,c("right ascension (float)")] != 254.879088032, c("right ascension (float)")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("right ascension (float)")] != 254.879088032, c("infrared (double)","declination (float)","z (double)","red (double)","right ascension (float)","objectid (long)","ultraviolet (double)","green (double)")]
                    Log.info("Filtering out rows by != from dataset sdss174052 and column \"objectid (long)\" using value 6.63947046007e+17, and also subsetting columns.")
                     filterHex <- hex[hex[,c("objectid (long)")] != 6.63947046007e+17, c("objectid (long)")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("objectid (long)")] != 6.63947046007e+17, c("infrared (double)","declination (float)","z (double)","red (double)","right ascension (float)","objectid (long)","ultraviolet (double)","green (double)")]
                    Log.info("Filtering out rows by != from dataset sdss174052 and column \"objectid (long)\" using value 6.31411005591e+17, and also subsetting columns.")
                     filterHex <- hex[hex[,c("objectid (long)")] != 6.31411005591e+17, c("objectid (long)")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("objectid (long)")] != 6.31411005591e+17, c("infrared (double)","declination (float)","z (double)","red (double)","right ascension (float)","objectid (long)","ultraviolet (double)","green (double)")]
                    Log.info("Filtering out rows by != from dataset sdss174052 and column \"declination (float)\" using value -9.74524349552, and also subsetting columns.")
                     filterHex <- hex[hex[,c("declination (float)")] != -9.74524349552, c("declination (float)")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("declination (float)")] != -9.74524349552, c("infrared (double)","declination (float)","z (double)","red (double)","right ascension (float)","objectid (long)","ultraviolet (double)","green (double)")]
                    Log.info("Filtering out rows by != from dataset sdss174052 and column \"infrared (double)\" using value 24.997762316, and also subsetting columns.")
                     filterHex <- hex[hex[,c("infrared (double)")] != 24.997762316, c("infrared (double)")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("infrared (double)")] != 24.997762316, c("infrared (double)","declination (float)","z (double)","red (double)","right ascension (float)","objectid (long)","ultraviolet (double)","green (double)")]
                    Log.info("Filtering out rows by != from dataset sdss174052 and column \"infrared (double)\" using value 30.673456301, and also subsetting columns.")
                     filterHex <- hex[hex[,c("infrared (double)")] != 30.673456301, c("infrared (double)")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("infrared (double)")] != 30.673456301, c("infrared (double)","declination (float)","z (double)","red (double)","right ascension (float)","objectid (long)","ultraviolet (double)","green (double)")]
                    Log.info("Filtering out rows by != from dataset sdss174052 and column \"objectid (long)\" using value 7.42067164523e+17, and also subsetting columns.")
                     filterHex <- hex[hex[,c("objectid (long)")] != 7.42067164523e+17, c("objectid (long)")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("objectid (long)")] != 7.42067164523e+17, c("infrared (double)","declination (float)","z (double)","red (double)","right ascension (float)","objectid (long)","ultraviolet (double)","green (double)")]
                    Log.info("Filtering out rows by != from dataset sdss174052 and column \"right ascension (float)\" using value 8.32469737506, and also subsetting columns.")
                     filterHex <- hex[hex[,c("right ascension (float)")] != 8.32469737506, c("right ascension (float)")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("right ascension (float)")] != 8.32469737506, c("infrared (double)","declination (float)","z (double)","red (double)","right ascension (float)","objectid (long)","ultraviolet (double)","green (double)")]
                    Log.info("Filtering out rows by != from dataset sdss174052 and column \"z (double)\" using value 17.8876413404, and also subsetting columns.")
                     filterHex <- hex[hex[,c("z (double)")] != 17.8876413404, c("z (double)")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("z (double)")] != 17.8876413404, c("infrared (double)","declination (float)","z (double)","red (double)","right ascension (float)","objectid (long)","ultraviolet (double)","green (double)")]
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("simpleFilterTest_ on data sdss174052", simpleFilterTest_sdss174052_130(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
