            ##
            # Author: Autogenerated on 2013-11-27 18:13:59
            # gitHash: c4ad841105ba82f4a3979e4cf1ae7e20a5905e59
            # SEED: 4663640625336856642
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            complexFilterTest_iris_wheader_147 <- function(conn) {
                Log.info("A munge-task R unit test on data <iris_wheader> testing the functional unit <['', '==']> ")
                Log.info("Uploading iris_wheader")
                hex <- h2o.uploadFile(conn, locate("../../smalldata/iris/iris_wheader.csv.gz"), "riris_wheader.hex")
            Log.info("Performing compound task ( ( hex[,c(\"petal_len\")] == 2.4241506089 ))  on dataset <iris_wheader>")
                     filterHex <- hex[( ( hex[,c("petal_len")] == 2.4241506089 )) ,]
            Log.info("Performing compound task ( ( hex[,c(\"sepal_len\")] == 6.97302946541 ))  on dataset iris_wheader, and also subsetting columns.")
                     filterHex <- hex[( ( hex[,c("sepal_len")] == 6.97302946541 )) , c("petal_wid","sepal_wid","petal_len","sepal_len")]
                Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[( ( hex[,c("sepal_len")] == 6.97302946541 )) , c("class")]
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("compoundFilterTest_ on data iris_wheader", complexFilterTest_iris_wheader_147(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
