            ##
            # Author: Autogenerated on 2013-11-27 18:13:58
            # gitHash: c4ad841105ba82f4a3979e4cf1ae7e20a5905e59
            # SEED: 4663640625336856642
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            simpleFilterTest_train_40 <- function(conn) {
                Log.info("A munge-task R unit test on data <train> testing the functional unit <<> ")
                Log.info("Uploading train")
                hex <- h2o.uploadFile(conn, locate("../../smalldata/chess/chess_2x2x1000/R/train.csv"), "rtrain.hex")
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("simpleFilterTest_ on data train", simpleFilterTest_train_40(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
