            ##
            # Author: Autogenerated on 2013-11-27 03:20:00
            # gitHash: 25eb0cfd1269362ae85d0f073d9abde2a68ac0e4
            # SEED: 4617575514352894151
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            complexFilterTest_train_208 <- function(conn) {
                Log.info("A munge-task R unit test on data <train> testing the functional unit <['!', '<=', '&', '==', '|', '>', '&', '>=', '|', '!=']> ")
                Log.info("Uploading train")
                hex <- h2o.uploadFile(conn, "../../smalldata/chess/chess_2x2x200/h2o/train.csv", "rtrain.hex")
            Log.info("Performing compound task !( ( hex[,c(\"y\")] <= 1.40330696285 ) & ( hex[,c(\"y\")] == 0.290648760206 ) | ( hex[,c(\"x\")] > 0.855773777238 ) & ( hex[,c(\"y\")] >= 0.700345323361 ) | ( ( hex[,c(\"x\")] != 1.39821038421 )) ) on dataset <train>")
                     filterHex <- hex[!( ( hex[,c("y")] <= 1.40330696285 ) & ( hex[,c("y")] == 0.290648760206 ) | ( hex[,c("x")] > 0.855773777238 ) & ( hex[,c("y")] >= 0.700345323361 ) | ( ( hex[,c("x")] != 1.39821038421 )) ),]
            Log.info("Performing compound task !( ( hex[,c(\"y\")] <= 1.4298015235 ) & ( hex[,c(\"x\")] == 0.606492871274 ) | ( hex[,c(\"y\")] > 0.664048354534 ) & ( hex[,c(\"x\")] >= 0.495174145717 ) | ( ( hex[,c(\"y\")] != 1.22950865112 )) ) on dataset train, and also subsetting columns.")
                     filterHex <- hex[!( ( hex[,c("y")] <= 1.4298015235 ) & ( hex[,c("x")] == 0.606492871274 ) | ( hex[,c("y")] > 0.664048354534 ) & ( hex[,c("x")] >= 0.495174145717 ) | ( ( hex[,c("y")] != 1.22950865112 )) ), c("x","y")]
                Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[!( ( hex[,c("y")] <= 1.4298015235 ) & ( hex[,c("x")] == 0.606492871274 ) | ( hex[,c("y")] > 0.664048354534 ) & ( hex[,c("x")] >= 0.495174145717 ) | ( ( hex[,c("y")] != 1.22950865112 )) ), c("color")]
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("compoundFilterTest_ on data train", complexFilterTest_train_208(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
