            ##
            # Author: Autogenerated on 2013-11-27 18:13:58
            # gitHash: c4ad841105ba82f4a3979e4cf1ae7e20a5905e59
            # SEED: 4663640625336856642
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            simpleFilterTest_iris_test_numeric_31 <- function(conn) {
                Log.info("A munge-task R unit test on data <iris_test_numeric> testing the functional unit <<> ")
                Log.info("Uploading iris_test_numeric")
                hex <- h2o.uploadFile(conn, locate("../../smalldata/test/classifier/iris_test_numeric.csv"), "riris_test_numeric.hex")
                Log.info("Filtering out rows by < from dataset iris_test_numeric and column \"petal_len\" using value 3.95033122934")
                     filterHex <- hex[hex[,c("petal_len")] < 3.95033122934,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"petal_len" < 3.95033122934,]
                Log.info("Filtering out rows by < from dataset iris_test_numeric and column \"petal_wid\" using value 1.95816704454")
                     filterHex <- hex[hex[,c("petal_wid")] < 1.95816704454,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"petal_wid" < 1.95816704454,]
                Log.info("Filtering out rows by < from dataset iris_test_numeric and column \"petal_wid\" using value 1.70455921097")
                     filterHex <- hex[hex[,c("petal_wid")] < 1.70455921097,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"petal_wid" < 1.70455921097,]
                Log.info("Filtering out rows by < from dataset iris_test_numeric and column \"species\" using value 0.836149191327")
                     filterHex <- hex[hex[,c("species")] < 0.836149191327,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"species" < 0.836149191327,]
                Log.info("Filtering out rows by < from dataset iris_test_numeric and column \"petal_wid\" using value 0.38050141936")
                     filterHex <- hex[hex[,c("petal_wid")] < 0.38050141936,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"petal_wid" < 0.38050141936,]
                Log.info("Filtering out rows by < from dataset iris_test_numeric and column \"petal_wid\" using value 2.20987774805")
                     filterHex <- hex[hex[,c("petal_wid")] < 2.20987774805,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"petal_wid" < 2.20987774805,]
                    Log.info("Filtering out rows by < from dataset iris_test_numeric and column \"sepal_len\" using value 6.88314452225, and also subsetting columns.")
                     filterHex <- hex[hex[,c("sepal_len")] < 6.88314452225, c("sepal_len")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("sepal_len")] < 6.88314452225, c("petal_wid","sepal_wid","petal_len","sepal_len","species")]
                    Log.info("Filtering out rows by < from dataset iris_test_numeric and column \"species\" using value 1.11906114513, and also subsetting columns.")
                     filterHex <- hex[hex[,c("species")] < 1.11906114513, c("species")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("species")] < 1.11906114513, c("petal_wid","sepal_wid","petal_len","sepal_len","species")]
                    Log.info("Filtering out rows by < from dataset iris_test_numeric and column \"species\" using value 1.58258980416, and also subsetting columns.")
                     filterHex <- hex[hex[,c("species")] < 1.58258980416, c("species")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("species")] < 1.58258980416, c("petal_wid","sepal_wid","petal_len","sepal_len","species")]
                    Log.info("Filtering out rows by < from dataset iris_test_numeric and column \"sepal_wid\" using value 4.3052150684, and also subsetting columns.")
                     filterHex <- hex[hex[,c("sepal_wid")] < 4.3052150684, c("sepal_wid")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("sepal_wid")] < 4.3052150684, c("petal_wid","sepal_wid","petal_len","sepal_len","species")]
                    Log.info("Filtering out rows by < from dataset iris_test_numeric and column \"petal_len\" using value 1.93024947266, and also subsetting columns.")
                     filterHex <- hex[hex[,c("petal_len")] < 1.93024947266, c("petal_len")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("petal_len")] < 1.93024947266, c("petal_wid","sepal_wid","petal_len","sepal_len","species")]
                    Log.info("Filtering out rows by < from dataset iris_test_numeric and column \"species\" using value 0.513916703664, and also subsetting columns.")
                     filterHex <- hex[hex[,c("species")] < 0.513916703664, c("species")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("species")] < 0.513916703664, c("petal_wid","sepal_wid","petal_len","sepal_len","species")]
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("simpleFilterTest_ on data iris_test_numeric", simpleFilterTest_iris_test_numeric_31(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
