            ##
            # Author: Autogenerated on 2013-11-27 17:26:17
            # gitHash: a4fe16d99eb5f003dd7c7d0da17f29e1712eda0f
            # SEED: 8586424275721420395
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            complexFilterTest_iris_test_numeric_missing_extra_164 <- function(conn) {
                Log.info("A munge-task R unit test on data <iris_test_numeric_missing_extra> testing the functional unit <['!', '==', '&', '>', '|', '>=']> ")
                Log.info("Uploading iris_test_numeric_missing_extra")
                hex <- h2o.uploadFile(conn, locate("../../smalldata/test/classifier/iris_test_numeric_missing_extra.csv"), "riris_test_numeric_missing_extra.hex")
            Log.info("Performing compound task !( ( hex[,c(\"species\")] == 2.95785663771 ) & ( hex[,c(\"species\")] > 3.97673908539 ) | ( ( hex[,c(\"petal_len\")] >= 4.70697293925 )) ) on dataset <iris_test_numeric_missing_extra>")
                     filterHex <- hex[!( ( hex[,c("species")] == 2.95785663771 ) & ( hex[,c("species")] > 3.97673908539 ) | ( ( hex[,c("petal_len")] >= 4.70697293925 )) ),]
            Log.info("Performing compound task !( ( hex[,c(\"sepal_wid\")] == 3.07184282089 ) & ( hex[,c(\"petal_wid\")] > 1.11685199218 ) | ( ( hex[,c(\"species\")] >= 2.50752964132 )) ) on dataset iris_test_numeric_missing_extra, and also subsetting columns.")
                     filterHex <- hex[!( ( hex[,c("sepal_wid")] == 3.07184282089 ) & ( hex[,c("petal_wid")] > 1.11685199218 ) | ( ( hex[,c("species")] >= 2.50752964132 )) ), c("petal_wid","sepal_wid","petal_len","sepal_len","species")]
                Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[!( ( hex[,c("sepal_wid")] == 3.07184282089 ) & ( hex[,c("petal_wid")] > 1.11685199218 ) | ( ( hex[,c("species")] >= 2.50752964132 )) ), c(1)]
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("compoundFilterTest_ on data iris_test_numeric_missing_extra", complexFilterTest_iris_test_numeric_missing_extra_164(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
