            ##
            # Author: Autogenerated on 2013-11-27 03:20:00
            # gitHash: 25eb0cfd1269362ae85d0f073d9abde2a68ac0e4
            # SEED: 4617575514352894151
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            complexFilterTest_test_all_raw_top10rows_193 <- function(conn) {
                Log.info("A munge-task R unit test on data <test_all_raw_top10rows> testing the functional unit <['!', '<=', '&', '==', '|', '>', '&', '>=', '|', '!=']> ")
                Log.info("Uploading test_all_raw_top10rows")
                hex <- h2o.uploadFile(conn, "../../smalldata/test/test_all_raw_top10rows.csv", "rtest_all_raw_top10rows.hex")
            Log.info("Performing compound task !( ( hex[,c(\"PersonsPerHousehold\")] <= 2.45763675784 ) & ( hex[,c(\"BusinessFirstQuarterPayroll\")] == 282101.546357 ) | ( hex[,c(\"IndianPopulation\")] > 1347.08103152 ) & ( hex[,c(\"HouseholdsPerZipCode\")] >= 32085.3161198 ) | ( ( hex[,c(\"CBSADivPop2003\")] != 3250495.94571 )) ) on dataset <test_all_raw_top10rows>")
                     filterHex <- hex[!( ( hex[,c("PersonsPerHousehold")] <= 2.45763675784 ) & ( hex[,c("BusinessFirstQuarterPayroll")] == 282101.546357 ) | ( hex[,c("IndianPopulation")] > 1347.08103152 ) & ( hex[,c("HouseholdsPerZipCode")] >= 32085.3161198 ) | ( ( hex[,c("CBSADivPop2003")] != 3250495.94571 )) ),]
            Log.info("Performing compound task !( ( hex[,c(\"TimeZone\")] <= 5.39939178657 ) & ( hex[,c(\"Day_Week\")] == 1.0 ) | ( hex[,c(\"BlackPopulation\")] > 40666.6417295 ) & ( hex[,c(\"IncomePerHousehold\")] >= 39416.9489515 ) | ( ( hex[,c(\"Choicepoint_Cx\")] != 0.0 )) ) on dataset test_all_raw_top10rows, and also subsetting columns.")
                     filterHex <- hex[!( ( hex[,c("TimeZone")] <= 5.39939178657 ) & ( hex[,c("Day_Week")] == 1.0 ) | ( hex[,c("BlackPopulation")] > 40666.6417295 ) & ( hex[,c("IncomePerHousehold")] >= 39416.9489515 ) | ( ( hex[,c("Choicepoint_Cx")] != 0.0 )) ), c("MSA","IncomePerHousehold","TimeZone","Day_Week","Choicepoint_Cx","AverageHouseValue","PersonsPerHousehold","MedianAgeFemale","BlackPopulation","hispanic_percent")]
                Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[!( ( hex[,c("TimeZone")] <= 5.39939178657 ) & ( hex[,c("Day_Week")] == 1.0 ) | ( hex[,c("BlackPopulation")] > 40666.6417295 ) & ( hex[,c("IncomePerHousehold")] >= 39416.9489515 ) | ( ( hex[,c("Choicepoint_Cx")] != 0.0 )) ), c("CBSADivPop2003","Month","Srvy_Plan2DD","WhitePopulation","PopulationEstimate","FeePlanID","CBSA_Div","HispanicPopulation","GrowthIncreasePercentage","Population","white_percent","WebApp","NumberOfEmployees","TU_pass","clientkey","HouseholdsPerZipCode","RegisteredOnline","male_percent","levelonedecisioncode","AsianPopulation","checkpointscore","region","HawaiianPopulation","DeliveryResidential","zip","BusinessFirstQuarterPayroll","BusinessAnnualPayroll","LandArea","LN_Cx","grade","GrowthHousingUnits2003","AnsweredSurvey","IndianPopulation","OnDD","DayLightSaving","Channel","age","PMSA","Activated","CityType","Experian_Cx","sex","Randm","NumberOfBusinesses","black_percent","TimeofDay","PlasticTypeID","Elevation","PlanType","Innovis_Cx","Has_bnk_AC","GrowthRank","CBSA","division","DeliveryTotal","Experian_pass","Srvy_bythngs_online","GrowthIncreaseNumber","PlasticType","female_percent","WaterArea","Choicepoint_pass","Innovis_pass","LN_pass","Appid","Verified","id","OtherPopulation","entereddate","DeliveryBusiness","FemalePopulation","MalePopulation","CSA","TU_Cx","MedianAge","MedianAgeMale","applicationid","CBSAPop2003","GrowthHousingUnits2004")]
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("compoundFilterTest_ on data test_all_raw_top10rows", complexFilterTest_test_all_raw_top10rows_193(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
