            ##
            # Author: Autogenerated on 2013-11-27 18:13:58
            # gitHash: c4ad841105ba82f4a3979e4cf1ae7e20a5905e59
            # SEED: 4663640625336856642
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            simpleFilterTest_chdage_71 <- function(conn) {
                Log.info("A munge-task R unit test on data <chdage> testing the functional unit <>> ")
                Log.info("Uploading chdage")
                hex <- h2o.uploadFile(conn, locate("../../smalldata/logreg/umass_statdata/chdage.dat"), "rchdage.hex")
                Log.info("Filtering out rows by > from dataset chdage and column \"ID\" using value 42.6753588804")
                     filterHex <- hex[hex[,c("ID")] > 42.6753588804,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"ID" > 42.6753588804,]
                Log.info("Filtering out rows by > from dataset chdage and column \"ID\" using value 13.9020141838")
                     filterHex <- hex[hex[,c("ID")] > 13.9020141838,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"ID" > 13.9020141838,]
                    Log.info("Filtering out rows by > from dataset chdage and column \"AGE\" using value 23.1166666959, and also subsetting columns.")
                     filterHex <- hex[hex[,c("AGE")] > 23.1166666959, c("AGE")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("AGE")] > 23.1166666959, c("CHD","ID","AGE")]
                    Log.info("Filtering out rows by > from dataset chdage and column \"AGE\" using value 63.9887508901, and also subsetting columns.")
                     filterHex <- hex[hex[,c("AGE")] > 63.9887508901, c("AGE")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("AGE")] > 63.9887508901, c("CHD","ID","AGE")]
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("simpleFilterTest_ on data chdage", simpleFilterTest_chdage_71(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
