            ##
            # Author: Autogenerated on 2013-11-27 18:13:58
            # gitHash: c4ad841105ba82f4a3979e4cf1ae7e20a5905e59
            # SEED: 4663640625336856642
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            simpleFilterTest_datagen1_53 <- function(conn) {
                Log.info("A munge-task R unit test on data <datagen1> testing the functional unit <<=> ")
                Log.info("Uploading datagen1")
                hex <- h2o.uploadFile(conn, locate("../../smalldata/datagen1.csv"), "rdatagen1.hex")
                Log.info("Filtering out rows by <= from dataset datagen1 and column \"0\" using value 349.494071197")
                     filterHex <- hex[hex[,c(1)] <= 349.494071197,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"0" <= 349.494071197,]
                Log.info("Filtering out rows by <= from dataset datagen1 and column \"0\" using value 856.863559974")
                     filterHex <- hex[hex[,c(1)] <= 856.863559974,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"0" <= 856.863559974,]
                Log.info("Filtering out rows by <= from dataset datagen1 and column \"0\" using value 792.778103524")
                     filterHex <- hex[hex[,c(1)] <= 792.778103524,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"0" <= 792.778103524,]
                Log.info("Filtering out rows by <= from dataset datagen1 and column \"0\" using value 429.983522116")
                     filterHex <- hex[hex[,c(1)] <= 429.983522116,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"0" <= 429.983522116,]
                Log.info("Filtering out rows by <= from dataset datagen1 and column \"0\" using value 849.935133295")
                     filterHex <- hex[hex[,c(1)] <= 849.935133295,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"0" <= 849.935133295,]
                Log.info("Filtering out rows by <= from dataset datagen1 and column \"0\" using value 36.3254266943")
                     filterHex <- hex[hex[,c(1)] <= 36.3254266943,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"0" <= 36.3254266943,]
                Log.info("Filtering out rows by <= from dataset datagen1 and column \"0\" using value 498.978298207")
                     filterHex <- hex[hex[,c(1)] <= 498.978298207,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"0" <= 498.978298207,]
                Log.info("Filtering out rows by <= from dataset datagen1 and column \"0\" using value 293.64129562")
                     filterHex <- hex[hex[,c(1)] <= 293.64129562,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"0" <= 293.64129562,]
                Log.info("Filtering out rows by <= from dataset datagen1 and column \"0\" using value 861.500147554")
                     filterHex <- hex[hex[,c(1)] <= 861.500147554,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"0" <= 861.500147554,]
                Log.info("Filtering out rows by <= from dataset datagen1 and column \"0\" using value 181.898413185")
                     filterHex <- hex[hex[,c(1)] <= 181.898413185,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"0" <= 181.898413185,]
                Log.info("Filtering out rows by <= from dataset datagen1 and column \"0\" using value 920.969070449")
                     filterHex <- hex[hex[,c(1)] <= 920.969070449,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"0" <= 920.969070449,]
                Log.info("Filtering out rows by <= from dataset datagen1 and column \"0\" using value 618.250707264")
                     filterHex <- hex[hex[,c(1)] <= 618.250707264,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"0" <= 618.250707264,]
                    Log.info("Filtering out rows by <= from dataset datagen1 and column \"0\" using value 664.165642778, and also subsetting columns.")
                     filterHex <- hex[hex[,c(1)] <= 664.165642778, c(1)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(1)] <= 664.165642778, c(1,3,2,5,4,7,6)]
                    Log.info("Filtering out rows by <= from dataset datagen1 and column \"0\" using value 473.664067076, and also subsetting columns.")
                     filterHex <- hex[hex[,c(1)] <= 473.664067076, c(1)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(1)] <= 473.664067076, c(1,3,2,5,4,7,6)]
                    Log.info("Filtering out rows by <= from dataset datagen1 and column \"0\" using value 25.1702641871, and also subsetting columns.")
                     filterHex <- hex[hex[,c(1)] <= 25.1702641871, c(1)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(1)] <= 25.1702641871, c(1,3,2,5,4,7,6)]
                    Log.info("Filtering out rows by <= from dataset datagen1 and column \"0\" using value 754.996446723, and also subsetting columns.")
                     filterHex <- hex[hex[,c(1)] <= 754.996446723, c(1)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(1)] <= 754.996446723, c(1,3,2,5,4,7,6)]
                    Log.info("Filtering out rows by <= from dataset datagen1 and column \"0\" using value 946.156326285, and also subsetting columns.")
                     filterHex <- hex[hex[,c(1)] <= 946.156326285, c(1)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(1)] <= 946.156326285, c(1,3,2,5,4,7,6)]
                    Log.info("Filtering out rows by <= from dataset datagen1 and column \"0\" using value 818.13511854, and also subsetting columns.")
                     filterHex <- hex[hex[,c(1)] <= 818.13511854, c(1)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(1)] <= 818.13511854, c(1,3,2,5,4,7,6)]
                    Log.info("Filtering out rows by <= from dataset datagen1 and column \"0\" using value 437.64382344, and also subsetting columns.")
                     filterHex <- hex[hex[,c(1)] <= 437.64382344, c(1)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(1)] <= 437.64382344, c(1,3,2,5,4,7,6)]
                    Log.info("Filtering out rows by <= from dataset datagen1 and column \"0\" using value 901.509652406, and also subsetting columns.")
                     filterHex <- hex[hex[,c(1)] <= 901.509652406, c(1)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(1)] <= 901.509652406, c(1,3,2,5,4,7,6)]
                    Log.info("Filtering out rows by <= from dataset datagen1 and column \"0\" using value 734.776073157, and also subsetting columns.")
                     filterHex <- hex[hex[,c(1)] <= 734.776073157, c(1)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(1)] <= 734.776073157, c(1,3,2,5,4,7,6)]
                    Log.info("Filtering out rows by <= from dataset datagen1 and column \"0\" using value 790.050930277, and also subsetting columns.")
                     filterHex <- hex[hex[,c(1)] <= 790.050930277, c(1)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(1)] <= 790.050930277, c(1,3,2,5,4,7,6)]
                    Log.info("Filtering out rows by <= from dataset datagen1 and column \"0\" using value 146.589954402, and also subsetting columns.")
                     filterHex <- hex[hex[,c(1)] <= 146.589954402, c(1)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(1)] <= 146.589954402, c(1,3,2,5,4,7,6)]
                    Log.info("Filtering out rows by <= from dataset datagen1 and column \"0\" using value 396.24080125, and also subsetting columns.")
                     filterHex <- hex[hex[,c(1)] <= 396.24080125, c(1)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(1)] <= 396.24080125, c(1,3,2,5,4,7,6)]
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("simpleFilterTest_ on data datagen1", simpleFilterTest_datagen1_53(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
