            ##
            # Author: Autogenerated on 2013-11-27 17:26:17
            # gitHash: a4fe16d99eb5f003dd7c7d0da17f29e1712eda0f
            # SEED: 8586424275721420395
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            complexFilterTest_tnc6_159 <- function(conn) {
                Log.info("A munge-task R unit test on data <tnc6> testing the functional unit <['!', '==', '&', '>', '|', '>=']> ")
                Log.info("Uploading tnc6")
                hex <- h2o.uploadFile(conn, locate("../../smalldata/tnc6.csv"), "rtnc6.hex")
            Log.info("Performing compound task !( ( hex[,c(\"fare\")] == 195.287805033 ) & ( hex[,c(\"fare\")] > 206.049163726 ) | ( ( hex[,c(\"survived\")] >= 0.301806576359 )) ) on dataset <tnc6>")
                     filterHex <- hex[!( ( hex[,c("fare")] == 195.287805033 ) & ( hex[,c("fare")] > 206.049163726 ) | ( ( hex[,c("survived")] >= 0.301806576359 )) ),]
            Log.info("Performing compound task !( ( hex[,c(\"cabin\")] == -1.0 ) & ( hex[,c(\"survived\")] > 0.144427662335 ) | ( ( hex[,c(\"home.dest\")] >= -1.0 )) ) on dataset tnc6, and also subsetting columns.")
                     filterHex <- hex[!( ( hex[,c("cabin")] == -1.0 ) & ( hex[,c("survived")] > 0.144427662335 ) | ( ( hex[,c("home.dest")] >= -1.0 )) ), c("boat","fare","ticket","survived","cabin","home.dest","body","embarked")]
                Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[!( ( hex[,c("cabin")] == -1.0 ) & ( hex[,c("survived")] > 0.144427662335 ) | ( ( hex[,c("home.dest")] >= -1.0 )) ), c(1)]
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("compoundFilterTest_ on data tnc6", complexFilterTest_tnc6_159(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
