            ##
            # Author: Autogenerated on 2013-11-27 03:20:00
            # gitHash: 25eb0cfd1269362ae85d0f073d9abde2a68ac0e4
            # SEED: 4617575514352894151
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            complexFilterTest_test_manycol_tree_158 <- function(conn) {
                Log.info("A munge-task R unit test on data <test_manycol_tree> testing the functional unit <['!', '>', '&', '<=', '&', '!|', '!', '==']> ")
                Log.info("Uploading test_manycol_tree")
                hex <- h2o.uploadFile(conn, "../../smalldata/test/test_manycol_tree.csv", "rtest_manycol_tree.hex")
            Log.info("Performing compound task !( ( hex[,c(\"B\")] > 2.94905426306 ) & ( hex[,c(\"B\")] <= 2.48143901466 ) & ( hex[,c(\"A\")] !| 1.24024066793 ) ! ( hex[,c(\"B\")] == 2.62954647412 )) on dataset <test_manycol_tree>")
                     filterHex <- hex[!( ( hex[,c("B")] > 2.94905426306 ) & ( hex[,c("B")] <= 2.48143901466 ) & ( hex[,c("A")] !| 1.24024066793 ) ! ( hex[,c("B")] == 2.62954647412 )),]
            Log.info("Performing compound task !( ( hex[,c(\"C\")] > 1.12065680968 ) & ( hex[,c(\"C\")] <= 1.11774852597 ) & ( hex[,c(\"D\")] !| 1.85054751104 ) ! ( hex[,c(\"X\")] == 1.64701555652 )) on dataset test_manycol_tree, and also subsetting columns.")
                     filterHex <- hex[!( ( hex[,c("C")] > 1.12065680968 ) & ( hex[,c("C")] <= 1.11774852597 ) & ( hex[,c("D")] !| 1.85054751104 ) ! ( hex[,c("X")] == 1.64701555652 )), c("X","B","C","D")]
                Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[!( ( hex[,c("C")] > 1.12065680968 ) & ( hex[,c("C")] <= 1.11774852597 ) & ( hex[,c("D")] !| 1.85054751104 ) ! ( hex[,c("X")] == 1.64701555652 )), c("response","A")]
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("compoundFilterTest_ on data test_manycol_tree", complexFilterTest_test_manycol_tree_158(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
