            ##
            # Author: Autogenerated on 2013-11-27 18:13:59
            # gitHash: c4ad841105ba82f4a3979e4cf1ae7e20a5905e59
            # SEED: 4663640625336856642
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            complexFilterTest_badchars_150 <- function(conn) {
                Log.info("A munge-task R unit test on data <badchars> testing the functional unit <['', '==']> ")
                Log.info("Uploading badchars")
                hex <- h2o.uploadFile(conn, locate("../../smalldata/badchars.csv"), "rbadchars.hex")
            Log.info("Performing compound task ( ( hex[,c(2)] == 16.7845057115 ))  on dataset <badchars>")
                     filterHex <- hex[( ( hex[,c(2)] == 16.7845057115 )) ,]
            Log.info("Performing compound task ( ( hex[,c(16)] == 0.0 ))  on dataset badchars, and also subsetting columns.")
                     filterHex <- hex[( ( hex[,c(16)] == 0.0 )) , c(42,43,35,24,25,48,49,46,44,45,28,29,41,3,5,4,6,12,11,38,15,16,33,32,30,37,53)]
                Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[( ( hex[,c(16)] == 0.0 )) , c(50,52,26,27,20,21,22,23,47,40,1,2,7,9,8,39,10,13,14,17,19,18,31,51,36,34,54)]
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("compoundFilterTest_ on data badchars", complexFilterTest_badchars_150(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
