            ##
            # Author: Autogenerated on 2013-11-27 18:13:58
            # gitHash: c4ad841105ba82f4a3979e4cf1ae7e20a5905e59
            # SEED: 4663640625336856642
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            simpleFilterTest_poker100_26 <- function(conn) {
                Log.info("A munge-task R unit test on data <poker100> testing the functional unit <<> ")
                Log.info("Uploading poker100")
                hex <- h2o.uploadFile(conn, locate("../../smalldata/poker/poker100"), "rpoker100.hex")
                Log.info("Filtering out rows by < from dataset poker100 and column \"7\" using value 4.4774809288")
                     filterHex <- hex[hex[,c(7)] < 4.4774809288,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"7" < 4.4774809288,]
                Log.info("Filtering out rows by < from dataset poker100 and column \"9\" using value 3.02313378699")
                     filterHex <- hex[hex[,c(9)] < 3.02313378699,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"9" < 3.02313378699,]
                Log.info("Filtering out rows by < from dataset poker100 and column \"6\" using value 1.0")
                     filterHex <- hex[hex[,c(6)] < 1.0,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"6" < 1.0,]
                Log.info("Filtering out rows by < from dataset poker100 and column \"5\" using value 3.0")
                     filterHex <- hex[hex[,c(5)] < 3.0,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"5" < 3.0,]
                    Log.info("Filtering out rows by < from dataset poker100 and column \"6\" using value 1.0, and also subsetting columns.")
                     filterHex <- hex[hex[,c(6)] < 1.0, c(6)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(6)] < 1.0, c(10,1,3,2,5,4,7,6,9,8)]
                    Log.info("Filtering out rows by < from dataset poker100 and column \"5\" using value 3.0, and also subsetting columns.")
                     filterHex <- hex[hex[,c(5)] < 3.0, c(5)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(5)] < 3.0, c(10,1,3,2,5,4,7,6,9,8)]
                    Log.info("Filtering out rows by < from dataset poker100 and column \"7\" using value 5.33371247923, and also subsetting columns.")
                     filterHex <- hex[hex[,c(7)] < 5.33371247923, c(7)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(7)] < 5.33371247923, c(10,1,3,2,5,4,7,6,9,8)]
                    Log.info("Filtering out rows by < from dataset poker100 and column \"8\" using value 2.35834113568, and also subsetting columns.")
                     filterHex <- hex[hex[,c(8)] < 2.35834113568, c(8)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(8)] < 2.35834113568, c(10,1,3,2,5,4,7,6,9,8)]
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("simpleFilterTest_ on data poker100", simpleFilterTest_poker100_26(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
