            ##
            # Author: Autogenerated on 2013-11-27 03:20:00
            # gitHash: 25eb0cfd1269362ae85d0f073d9abde2a68ac0e4
            # SEED: 4617575514352894151
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            sliceTest_pros_5 <- function(conn) {
                Log.info("A munge-task R unit test on data <pros> testing the functional unit <[> ")
                Log.info("Uploading pros")
                hex <- h2o.uploadFile(conn, "../../smalldata/logreg/umass_statdata/pros.dat", "rpros.hex")
                Log.info("Performing a column slice of pros using these columns: c(1)")
                slicedHex <- hex[,c(1)]
                    Log.info("Performing a 1-by-1 column slice of pros using these columns: ")
                    Log.info("Performing a 1-by-1 row slice of pros using these rows: ")
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("sliceTest_ on data pros", sliceTest_pros_5(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
