            ##
            # Author: Autogenerated on 2013-11-27 18:13:58
            # gitHash: c4ad841105ba82f4a3979e4cf1ae7e20a5905e59
            # SEED: 4663640625336856642
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            simpleFilterTest_stego_training_modified_92 <- function(conn) {
                Log.info("A munge-task R unit test on data <stego_training_modified> testing the functional unit <>=> ")
                Log.info("Uploading stego_training_modified")
                hex <- h2o.uploadFile(conn, locate("../../smalldata/stego/stego_training_modified.data"), "rstego_training_modified.hex")
                Log.info("Filtering out rows by >= from dataset stego_training_modified and column \"106\" using value 0.104790732433")
                     filterHex <- hex[hex[,c(106)] >= 0.104790732433,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"106" >= 0.104790732433,]
                Log.info("Filtering out rows by >= from dataset stego_training_modified and column \"116\" using value 0.0814302849021")
                     filterHex <- hex[hex[,c(116)] >= 0.0814302849021,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"116" >= 0.0814302849021,]
                    Log.info("Filtering out rows by >= from dataset stego_training_modified and column \"105\" using value 0.132764328671, and also subsetting columns.")
                     filterHex <- hex[hex[,c(105)] >= 0.132764328671, c(105)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(105)] >= 0.132764328671, c(133,132,131,130,137,136,135,134,139,138,24,25,26,27,20,21,22,23,160,28,29,161,4,8,163,119,120,121,122,123,124,125,126,127,128,129,118,59,58,55,54,57,56,51,50,53,52,115,114,88,89,111,110,113,112,82,83,80,81,86,87,84,85,3,7,108,109,102,103,100,101,106,107,104,105,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,162,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,117,116,151,150,153,152,155,154,157,156,159,158,48,49,46,47,44,45,42,43,40,41,1,5,9,146,147,144,145,142,143,140,141,148,149,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by >= from dataset stego_training_modified and column \"62\" using value 0.220151091554, and also subsetting columns.")
                     filterHex <- hex[hex[,c(62)] >= 0.220151091554, c(62)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(62)] >= 0.220151091554, c(133,132,131,130,137,136,135,134,139,138,24,25,26,27,20,21,22,23,160,28,29,161,4,8,163,119,120,121,122,123,124,125,126,127,128,129,118,59,58,55,54,57,56,51,50,53,52,115,114,88,89,111,110,113,112,82,83,80,81,86,87,84,85,3,7,108,109,102,103,100,101,106,107,104,105,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,162,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,117,116,151,150,153,152,155,154,157,156,159,158,48,49,46,47,44,45,42,43,40,41,1,5,9,146,147,144,145,142,143,140,141,148,149,77,76,75,74,73,72,71,70,79,78)]
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("simpleFilterTest_ on data stego_training_modified", simpleFilterTest_stego_training_modified_92(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
