            ##
            # Author: Autogenerated on 2013-11-27 17:26:17
            # gitHash: a4fe16d99eb5f003dd7c7d0da17f29e1712eda0f
            # SEED: 8586424275721420395
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            sliceTest_hex_443_10 <- function(conn) {
                Log.info("A munge-task R unit test on data <hex_443> testing the functional unit <[> ")
                Log.info("Uploading hex_443")
                hex <- h2o.uploadFile(conn, locate("../../smalldata/hex-443.parsetmp_1_0_0_0.data"), "rhex_443.hex")
                    Log.info("Performing a row & column slice of hex-443 using these rows & columns: c(\"MiddleInitials\",\"DateofBirth\") & c(24,10,13,12,20,22,25,33,32,31,16,5,4,7,6,9)")
                slicedHex <- hex[c(24,10,13,12,20,22,25,33,32,31,16,5,4,7,6,9),c("MiddleInitials","DateofBirth")]
                    Log.info("Performing a 1-by-1 column slice of hex-443 using these columns: ")
                    Log.info("Performing a 1-by-1 row slice of hex-443 using these rows: ")
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("sliceTest_ on data hex-443", sliceTest_hex_443_10(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
