            ##
            # Author: Autogenerated on 2013-11-27 17:26:17
            # gitHash: a4fe16d99eb5f003dd7c7d0da17f29e1712eda0f
            # SEED: 8586424275721420395
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            sliceTest_40k_categoricals_12 <- function(conn) {
                Log.info("A munge-task R unit test on data <40k_categoricals> testing the functional unit <[> ")
                Log.info("Uploading 40k_categoricals")
                hex <- h2o.uploadFile(conn, locate("../../smalldata/categoricals/40k_categoricals.csv.gz"), "r40k_categoricals.hex")
                Log.info("Performing a column slice of 40k_categoricals using these columns: c(1)")
                slicedHex <- hex[,c(1)]
                    Log.info("Performing a 1-by-1 column slice of 40k_categoricals using these columns: ")
                    Log.info("Performing a 1-by-1 row slice of 40k_categoricals using these rows: ")
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("sliceTest_ on data 40k_categoricals", sliceTest_40k_categoricals_12(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
