            ##
            # Author: Autogenerated on 2013-11-27 17:26:17
            # gitHash: a4fe16d99eb5f003dd7c7d0da17f29e1712eda0f
            # SEED: 8586424275721420395
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            complexFilterTest_iris_test_189 <- function(conn) {
                Log.info("A munge-task R unit test on data <iris_test> testing the functional unit <['', '==', '|', '==', '&', '<']> ")
                Log.info("Uploading iris_test")
                hex <- h2o.uploadFile(conn, locate("../../smalldata/iris/iris_test.csv"), "riris_test.hex")
            Log.info("Performing compound task ( hex[,c(\"petal_len\")] == 3.9172839638 ) | ( hex[,c(\"sepal_wid\")] == 3.45129167072 ) & ( ( hex[,c(\"petal_len\")] < 5.72677304302 ))  on dataset <iris_test>")
                     filterHex <- hex[( hex[,c("petal_len")] == 3.9172839638 ) | ( hex[,c("sepal_wid")] == 3.45129167072 ) & ( ( hex[,c("petal_len")] < 5.72677304302 )) ,]
            Log.info("Performing compound task ( hex[,c(\"petal_len\")] == 6.00605750834 ) | ( hex[,c(\"petal_len\")] == 1.88428999838 ) & ( ( hex[,c(\"petal_len\")] < 6.04158822857 ))  on dataset iris_test, and also subsetting columns.")
                     filterHex <- hex[( hex[,c("petal_len")] == 6.00605750834 ) | ( hex[,c("petal_len")] == 1.88428999838 ) & ( ( hex[,c("petal_len")] < 6.04158822857 )) , c("petal_wid","sepal_wid","petal_len","sepal_len")]
                Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[( hex[,c("petal_len")] == 6.00605750834 ) | ( hex[,c("petal_len")] == 1.88428999838 ) & ( ( hex[,c("petal_len")] < 6.04158822857 )) , c("species")]
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("compoundFilterTest_ on data iris_test", complexFilterTest_iris_test_189(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
