            ##
            # Author: Autogenerated on 2013-11-27 17:26:17
            # gitHash: a4fe16d99eb5f003dd7c7d0da17f29e1712eda0f
            # SEED: 8586424275721420395
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            complexFilterTest_stego_testing_199 <- function(conn) {
                Log.info("A munge-task R unit test on data <stego_testing> testing the functional unit <['', '<', '&', '==', '|', '<', '&', '!=', '|', '>']> ")
                Log.info("Uploading stego_testing")
                hex <- h2o.uploadFile(conn, locate("../../smalldata/stego/stego_testing.data"), "rstego_testing.hex")
            Log.info("Performing compound task ( hex[,c(64)] < 0.0807909494259 ) & ( hex[,c(11)] == 0.0750246212182 ) | ( hex[,c(141)] < 0.271265438819 ) & ( hex[,c(139)] != 0.0510994359671 ) | ( ( hex[,c(126)] > 0.00721551599962 ))  on dataset <stego_testing>")
                     filterHex <- hex[( hex[,c(64)] < 0.0807909494259 ) & ( hex[,c(11)] == 0.0750246212182 ) | ( hex[,c(141)] < 0.271265438819 ) & ( hex[,c(139)] != 0.0510994359671 ) | ( ( hex[,c(126)] > 0.00721551599962 )) ,]
            Log.info("Performing compound task ( hex[,c(33)] < 0.271762898618 ) & ( hex[,c(68)] == 0.161976301882 ) | ( hex[,c(107)] < 0.336759294667 ) & ( hex[,c(136)] != 0.056489968735 ) | ( ( hex[,c(136)] > 0.0555878493938 ))  on dataset stego_testing, and also subsetting columns.")
                     filterHex <- hex[( hex[,c(33)] < 0.271762898618 ) & ( hex[,c(68)] == 0.161976301882 ) | ( hex[,c(107)] < 0.336759294667 ) & ( hex[,c(136)] != 0.056489968735 ) | ( ( hex[,c(136)] > 0.0555878493938 )) , c(153,155,114,88,136,113,68,69,87,25,7,147,121,123,127,128,103,92,107,79,38,98,33,65)]
                Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[( hex[,c(33)] < 0.271762898618 ) & ( hex[,c(68)] == 0.161976301882 ) | ( hex[,c(107)] < 0.336759294667 ) & ( hex[,c(136)] != 0.056489968735 ) | ( ( hex[,c(136)] > 0.0555878493938 )) , c(133,132,131,130,137,135,134,139,138,24,26,27,20,21,22,23,160,28,29,161,4,8,163,119,120,122,124,125,126,129,59,58,55,54,57,56,51,50,53,52,115,117,89,111,110,112,82,83,80,81,86,118,84,85,3,108,109,102,100,101,106,104,105,39,32,31,30,37,36,35,34,60,61,62,63,64,66,67,2,162,6,99,91,90,93,95,94,97,96,11,10,13,12,15,14,17,16,19,18,116,151,150,152,154,157,156,159,158,48,49,46,47,44,45,42,43,40,41,1,5,9,146,144,145,142,143,140,141,148,149,77,76,75,74,73,72,71,70,78)]
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("compoundFilterTest_ on data stego_testing", complexFilterTest_stego_testing_199(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
