            ##
            # Author: Autogenerated on 2013-11-27 18:13:58
            # gitHash: c4ad841105ba82f4a3979e4cf1ae7e20a5905e59
            # SEED: 4663640625336856642
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            sliceTest_lowbwt_13 <- function(conn) {
                Log.info("A munge-task R unit test on data <lowbwt> testing the functional unit <[> ")
                Log.info("Uploading lowbwt")
                hex <- h2o.uploadFile(conn, locate("../../smalldata/logreg/umass_statdata/lowbwt.dat"), "rlowbwt.hex")
                Log.info("Performing a column slice of lowbwt using these columns: c(1)")
                slicedHex <- hex[,c(1)]
                    Log.info("Performing a row & column slice of lowbwt using these rows & columns: c(\"LWT\",\"ID\",\"UI\",\"RACE\") & c(154,158,104,82,88,116,111,136,135,67,177,83,80,174,139,24,27,20,21,22,175,42,40,107,182,180,187,185,189,28,146,145,137,140,100,149,99,121,73,72,126,103,166,94,97,78,39,17,98,19,30,37,50,33,89,168)")
                slicedHex <- hex[c(154,158,104,82,88,116,111,136,135,67,177,83,80,174,139,24,27,20,21,22,175,42,40,107,182,180,187,185,189,28,146,145,137,140,100,149,99,121,73,72,126,103,166,94,97,78,39,17,98,19,30,37,50,33,89,168),c("LWT","ID","UI","RACE")]
                    Log.info("Performing a 1-by-1 column slice of lowbwt using these columns: ")
                    Log.info("Performing a 1-by-1 row slice of lowbwt using these rows: ")
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("sliceTest_ on data lowbwt", sliceTest_lowbwt_13(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
