            ##
            # Author: Autogenerated on 2013-11-27 18:13:59
            # gitHash: c4ad841105ba82f4a3979e4cf1ae7e20a5905e59
            # SEED: 4663640625336856642
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            complexFilterTest_prostate_2_166 <- function(conn) {
                Log.info("A munge-task R unit test on data <prostate_2> testing the functional unit <['!', '>', '&', '==', '&', '<=']> ")
                Log.info("Uploading prostate_2")
                hex <- h2o.uploadFile(conn, locate("../../smalldata/parse_folder_test/prostate_2.csv"), "rprostate_2.hex")
            Log.info("Performing compound task !( ( hex[,c(5)] > 1.0 ) & ( hex[,c(6)] == 62.3113939033 ) & ( ( hex[,c(8)] <= 5.51809003832 )) ) on dataset <prostate_2>")
                     filterHex <- hex[!( ( hex[,c(5)] > 1.0 ) & ( hex[,c(6)] == 62.3113939033 ) & ( ( hex[,c(8)] <= 5.51809003832 )) ),]
            Log.info("Performing compound task !( ( hex[,c(6)] > 33.5458974326 ) & ( hex[,c(2)] == 59.7783189066 ) & ( ( hex[,c(6)] <= 24.4214073915 )) ) on dataset prostate_2, and also subsetting columns.")
                     filterHex <- hex[!( ( hex[,c(6)] > 33.5458974326 ) & ( hex[,c(2)] == 59.7783189066 ) & ( ( hex[,c(6)] <= 24.4214073915 )) ), c(1,2,5,4,7,6,8)]
                Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[!( ( hex[,c(6)] > 33.5458974326 ) & ( hex[,c(2)] == 59.7783189066 ) & ( ( hex[,c(6)] <= 24.4214073915 )) ), c(3)]
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("compoundFilterTest_ on data prostate_2", complexFilterTest_prostate_2_166(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
