            ##
            # Author: Autogenerated on 2013-11-27 18:13:59
            # gitHash: c4ad841105ba82f4a3979e4cf1ae7e20a5905e59
            # SEED: 4663640625336856642
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            simpleFilterTest_chess_2x2_500_int_111 <- function(conn) {
                Log.info("A munge-task R unit test on data <chess_2x2_500_int> testing the functional unit <==> ")
                Log.info("Uploading chess_2x2_500_int")
                hex <- h2o.uploadFile(conn, locate("../../smalldata/chess/chess_2x2x500/h2o/chess_2x2_500_int.csv"), "rchess_2x2_500_int.hex")
                Log.info("Filtering out rows by == from dataset chess_2x2_500_int and column \"x\" using value 729125.453833")
                     filterHex <- hex[hex[,c("x")] == 729125.453833,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"x" == 729125.453833,]
                Log.info("Filtering out rows by == from dataset chess_2x2_500_int and column \"y\" using value 1670393.15106")
                     filterHex <- hex[hex[,c("y")] == 1670393.15106,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"y" == 1670393.15106,]
                Log.info("Filtering out rows by == from dataset chess_2x2_500_int and column \"y\" using value 1370174.97141")
                     filterHex <- hex[hex[,c("y")] == 1370174.97141,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"y" == 1370174.97141,]
                Log.info("Filtering out rows by == from dataset chess_2x2_500_int and column \"y\" using value 1658868.35486")
                     filterHex <- hex[hex[,c("y")] == 1658868.35486,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"y" == 1658868.35486,]
                    Log.info("Filtering out rows by == from dataset chess_2x2_500_int and column \"y\" using value 17823.8675301, and also subsetting columns.")
                     filterHex <- hex[hex[,c("y")] == 17823.8675301, c("y")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("y")] == 17823.8675301, c("color","x","y")]
                    Log.info("Filtering out rows by == from dataset chess_2x2_500_int and column \"y\" using value 1500023.80135, and also subsetting columns.")
                     filterHex <- hex[hex[,c("y")] == 1500023.80135, c("y")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("y")] == 1500023.80135, c("color","x","y")]
                    Log.info("Filtering out rows by == from dataset chess_2x2_500_int and column \"y\" using value 1018930.23243, and also subsetting columns.")
                     filterHex <- hex[hex[,c("y")] == 1018930.23243, c("y")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("y")] == 1018930.23243, c("color","x","y")]
                    Log.info("Filtering out rows by == from dataset chess_2x2_500_int and column \"x\" using value 1742987.48751, and also subsetting columns.")
                     filterHex <- hex[hex[,c("x")] == 1742987.48751, c("x")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("x")] == 1742987.48751, c("color","x","y")]
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("simpleFilterTest_ on data chess_2x2_500_int", simpleFilterTest_chess_2x2_500_int_111(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
