            ##
            # Author: Autogenerated on 2013-11-27 17:26:17
            # gitHash: a4fe16d99eb5f003dd7c7d0da17f29e1712eda0f
            # SEED: 8586424275721420395
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            simpleFilterTest_train_95 <- function(conn) {
                Log.info("A munge-task R unit test on data <train> testing the functional unit <>=> ")
                Log.info("Uploading train")
                hex <- h2o.uploadFile(conn, locate("../../smalldata/chess/chess_2x2x200/R/train.csv"), "rtrain.hex")
                Log.info("Filtering out rows by >= from dataset train and column \"y\" using value 1.92417647352")
                     filterHex <- hex[hex[,c("y")] >= 1.92417647352,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"y" >= 1.92417647352,]
                Log.info("Filtering out rows by >= from dataset train and column \"y\" using value 0.361257700162")
                     filterHex <- hex[hex[,c("y")] >= 0.361257700162,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"y" >= 0.361257700162,]
                Log.info("Filtering out rows by >= from dataset train and column \"x\" using value 1.0691587696")
                     filterHex <- hex[hex[,c("x")] >= 1.0691587696,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"x" >= 1.0691587696,]
                Log.info("Filtering out rows by >= from dataset train and column \"y\" using value 0.229083325087")
                     filterHex <- hex[hex[,c("y")] >= 0.229083325087,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"y" >= 0.229083325087,]
                Log.info("Filtering out rows by >= from dataset train and column \"y\" using value 0.184051236565")
                     filterHex <- hex[hex[,c("y")] >= 0.184051236565,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"y" >= 0.184051236565,]
                    Log.info("Filtering out rows by >= from dataset train and column \"x\" using value 0.598954780404, and also subsetting columns.")
                     filterHex <- hex[hex[,c("x")] >= 0.598954780404, c("x")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("x")] >= 0.598954780404, c("color","x","y")]
                    Log.info("Filtering out rows by >= from dataset train and column \"x\" using value 1.6751027076, and also subsetting columns.")
                     filterHex <- hex[hex[,c("x")] >= 1.6751027076, c("x")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("x")] >= 1.6751027076, c("color","x","y")]
                    Log.info("Filtering out rows by >= from dataset train and column \"x\" using value 1.73285807484, and also subsetting columns.")
                     filterHex <- hex[hex[,c("x")] >= 1.73285807484, c("x")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("x")] >= 1.73285807484, c("color","x","y")]
                    Log.info("Filtering out rows by >= from dataset train and column \"x\" using value 1.86745867582, and also subsetting columns.")
                     filterHex <- hex[hex[,c("x")] >= 1.86745867582, c("x")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("x")] >= 1.86745867582, c("color","x","y")]
                    Log.info("Filtering out rows by >= from dataset train and column \"y\" using value 1.70695238971, and also subsetting columns.")
                     filterHex <- hex[hex[,c("y")] >= 1.70695238971, c("y")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("y")] >= 1.70695238971, c("color","x","y")]
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("simpleFilterTest_ on data train", simpleFilterTest_train_95(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
