            ##
            # Author: Autogenerated on 2013-11-27 18:13:58
            # gitHash: c4ad841105ba82f4a3979e4cf1ae7e20a5905e59
            # SEED: 4663640625336856642
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            simpleFilterTest_test_62 <- function(conn) {
                Log.info("A munge-task R unit test on data <test> testing the functional unit <>> ")
                Log.info("Uploading test")
                hex <- h2o.uploadFile(conn, locate("../../smalldata/chess/chess_2x2x1000/R/test.csv"), "rtest.hex")
                Log.info("Filtering out rows by > from dataset test and column \"y\" using value 0.861998902611")
                     filterHex <- hex[hex[,c("y")] > 0.861998902611,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"y" > 0.861998902611,]
                    Log.info("Filtering out rows by > from dataset test and column \"x\" using value 0.60665176767, and also subsetting columns.")
                     filterHex <- hex[hex[,c("x")] > 0.60665176767, c("x")]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c("x")] > 0.60665176767, c("color","x","y")]
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("simpleFilterTest_ on data test", simpleFilterTest_test_62(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
