            ##
            # Author: Autogenerated on 2013-11-27 03:20:00
            # gitHash: 25eb0cfd1269362ae85d0f073d9abde2a68ac0e4
            # SEED: 4617575514352894151
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            complexFilterTest_datagen1_184 <- function(conn) {
                Log.info("A munge-task R unit test on data <datagen1> testing the functional unit <['!', '!=', '|', '<', '|', '>=']> ")
                Log.info("Uploading datagen1")
                hex <- h2o.uploadFile(conn, "../../smalldata/datagen1.csv", "rdatagen1.hex")
            Log.info("Performing compound task !( ( hex[,c(1)] != 975.014739968 ) | ( hex[,c(1)] < 872.537666253 ) | ( ( hex[,c(1)] >= 727.298374469 )) ) on dataset <datagen1>")
                     filterHex <- hex[!( ( hex[,c(1)] != 975.014739968 ) | ( hex[,c(1)] < 872.537666253 ) | ( ( hex[,c(1)] >= 727.298374469 )) ),]
            Log.info("Performing compound task !( ( hex[,c(1)] != 668.521913097 ) | ( hex[,c(1)] < 815.079358493 ) | ( ( hex[,c(1)] >= 203.237616878 )) ) on dataset datagen1, and also subsetting columns.")
                     filterHex <- hex[!( ( hex[,c(1)] != 668.521913097 ) | ( hex[,c(1)] < 815.079358493 ) | ( ( hex[,c(1)] >= 203.237616878 )) ), c(1)]
                Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[!( ( hex[,c(1)] != 668.521913097 ) | ( hex[,c(1)] < 815.079358493 ) | ( ( hex[,c(1)] >= 203.237616878 )) ), c(1,3,2,5,4,7,6)]
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("compoundFilterTest_ on data datagen1", complexFilterTest_datagen1_184(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
