            ##
            # Author: Autogenerated on 2013-11-27 03:20:00
            # gitHash: 25eb0cfd1269362ae85d0f073d9abde2a68ac0e4
            # SEED: 4617575514352894151
            ##
            source('./findNSourceUtils.R')
            Log.info("======================== Begin Test ===========================")
            complexFilterTest_train_186 <- function(conn) {
                Log.info("A munge-task R unit test on data <train> testing the functional unit <['!', '!=', '|', '<', '|', '>=']> ")
                Log.info("Uploading train")
                hex <- h2o.uploadFile(conn, "../../smalldata/chess/chess_1x2x1000/h2o/train.csv", "rtrain.hex")
            Log.info("Performing compound task !( ( hex[,c(\"x\")] != 0.626874119976 ) | ( hex[,c(\"x\")] < 0.670158095498 ) | ( ( hex[,c(\"y\")] >= 1.9040609854 )) ) on dataset <train>")
                     filterHex <- hex[!( ( hex[,c("x")] != 0.626874119976 ) | ( hex[,c("x")] < 0.670158095498 ) | ( ( hex[,c("y")] >= 1.9040609854 )) ),]
            Log.info("Performing compound task !( ( hex[,c(\"x\")] != 0.0941488916652 ) | ( hex[,c(\"x\")] < 0.211736522803 ) | ( ( hex[,c(\"y\")] >= 0.352217296231 )) ) on dataset train, and also subsetting columns.")
                     filterHex <- hex[!( ( hex[,c("x")] != 0.0941488916652 ) | ( hex[,c("x")] < 0.211736522803 ) | ( ( hex[,c("y")] >= 0.352217296231 )) ), c("x","y")]
                Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[!( ( hex[,c("x")] != 0.0941488916652 ) | ( hex[,c("x")] < 0.211736522803 ) | ( ( hex[,c("y")] >= 0.352217296231 )) ), c("color")]
            }
            conn = new("H2OClient", ip=myIP, port=myPort)
            tryCatch(test_that("compoundFilterTest_ on data train", complexFilterTest_train_186(conn)), warning = function(w) WARN(w), error = function(e) FAIL(e))
            PASS()
