#!/bin/bash

echo
echo Please read hadoop/README.txt
echo
echo After building, the hadoop driver jars live in the hadoop directory of 
echo the h2o zip file.
echo
echo For more info, look at docs/H2O_on_Hadoop_0xdata.pdf
echo
